-- ==============================================================
-- Generated by Vitis HLS v2025.2.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_10_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_12_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_13_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_14_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_16_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_17_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_18_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_19_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_20_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_21_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_22_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_23_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_24_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_25_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_26_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_27_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_28_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_29_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_30_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_31_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv26_4C8 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010011001000";
    constant ap_const_lv26_3FFFAA5 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111101010100101";
    constant ap_const_lv26_3FFF979 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111100101111001";
    constant ap_const_lv26_3FFFDBF : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110111111";
    constant ap_const_lv26_11F : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000100011111";
    constant ap_const_lv26_3FFFE4B : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111001001011";
    constant ap_const_lv26_3FFFD85 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110000101";
    constant ap_const_lv26_3FFFE46 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111001000110";
    constant ap_const_lv26_3FFFEE4 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111011100100";
    constant ap_const_lv26_236 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000110110";
    constant ap_const_lv26_3FFFD8A : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110001010";
    constant ap_const_lv26_307 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001100000111";
    constant ap_const_lv26_3FFFB7A : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111101101111010";
    constant ap_const_lv25_1FFFF62 : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111101100010";
    constant ap_const_lv26_176 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000101110110";
    constant ap_const_lv25_1FFFF32 : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111100110010";
    constant ap_const_lv26_52E : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010100101110";
    constant ap_const_lv26_287 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010000111";
    constant ap_const_lv26_3FFFE0D : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111000001101";
    constant ap_const_lv26_12C : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000100101100";
    constant ap_const_lv26_3FFFE69 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111001101001";
    constant ap_const_lv26_348 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001101001000";
    constant ap_const_lv26_4E9 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010011101001";
    constant ap_const_lv26_3FFFDA2 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110100010";
    constant ap_const_lv26_3FFFD87 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110000111";
    constant ap_const_lv26_193 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000110010011";
    constant ap_const_lv26_1F6 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000111110110";
    constant ap_const_lv26_3FFFCBA : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110010111010";
    constant ap_const_lv26_3A4 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001110100100";
    constant ap_const_lv26_3FFFC27 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110000100111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv16_64 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001100100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal add_ln58_fu_4981_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_reg_5162 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln58_1_fu_4987_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_1_reg_5167 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_5_fu_5005_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_5_reg_5172 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_7_fu_5011_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_7_reg_5177 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_8_fu_5017_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_8_reg_5182 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_12_fu_5035_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_12_reg_5187 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_17_fu_5053_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_17_reg_5192 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_20_fu_5071_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_20_reg_5197 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_22_fu_5077_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_22_reg_5202 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_23_fu_5083_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_23_reg_5207 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_28_fu_5107_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_28_reg_5212 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_10_fu_364_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mul_ln42_9_fu_365_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln42_6_fu_366_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln42_16_fu_367_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_1_fu_368_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln73_9_fu_369_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln42_11_fu_370_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_6_fu_371_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln73_4_fu_372_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln42_7_fu_373_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_1_fu_374_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_14_fu_375_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_fu_376_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln73_fu_377_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_5_fu_378_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln73_11_fu_379_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln42_4_fu_380_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln42_3_fu_381_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_7_fu_382_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln73_2_fu_383_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln73_8_fu_384_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln42_17_fu_385_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_8_fu_386_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln42_12_fu_387_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_5_fu_388_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_10_fu_390_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln73_3_fu_391_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln42_2_fu_392_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_15_fu_393_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_13_fu_394_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_fu_376_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_1_fu_374_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_2_fu_392_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_fu_377_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln42_3_fu_4497_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln73_1_fu_368_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_3_fu_381_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_4_fu_380_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_5_fu_388_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_fu_4571_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_5_fu_4583_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln73_1_fu_4591_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln73_fu_4579_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sub_ln73_fu_4595_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln42_8_fu_4601_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln42_6_fu_366_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_7_fu_373_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_8_fu_386_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_9_fu_365_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_10_fu_364_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_11_fu_370_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_2_fu_383_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_3_fu_391_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_12_fu_387_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_13_fu_394_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_4_fu_372_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_5_fu_378_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_6_fu_371_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_6_fu_4810_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln73_2_fu_4818_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sub_ln73_1_fu_4822_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln42_21_fu_4828_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln73_7_fu_382_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_8_fu_384_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_9_fu_369_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_14_fu_375_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_10_fu_390_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_15_fu_393_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_16_fu_367_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_11_fu_379_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln42_29_fu_4952_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln42_17_fu_385_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln_fu_4452_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_1_fu_4467_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_2_fu_4482_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_3_fu_4507_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_4_fu_4516_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_5_fu_4531_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_6_fu_4546_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_7_fu_4561_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_4_fu_4999_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_3_fu_4993_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_7_fu_4611_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_9_fu_4620_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_s_fu_4635_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_10_fu_4650_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_11_fu_4665_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_12_fu_4680_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_13_fu_4695_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_14_fu_4710_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_11_fu_5029_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_10_fu_5023_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_15_fu_4725_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_16_fu_4740_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_17_fu_4755_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_18_fu_4770_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_16_fu_5047_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_15_fu_5041_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_19_fu_4785_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_20_fu_4800_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_16_fu_4838_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_22_fu_4847_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_19_fu_5065_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_18_fu_5059_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_23_fu_4862_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_24_fu_4877_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_25_fu_4892_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_26_fu_4907_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_27_fu_4922_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_28_fu_4937_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_30_fu_4971_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_26_fu_5095_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_20_fu_4962_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_27_fu_5101_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_25_fu_5089_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_2_fu_5113_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_9_fu_5122_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_13_fu_5126_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_6_fu_5117_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_24_fu_5141_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_29_fu_5145_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_21_fu_5137_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_30_fu_5150_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_14_fu_5131_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_init_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_16s_12ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_12s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_11s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_10ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_10s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_11ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_9s_25_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;



begin
    mul_16s_12ns_26_1_1_U324 : component myproject_mul_16s_12ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        din0 => data_13_val,
        din1 => mul_ln42_10_fu_364_p1,
        dout => mul_ln42_10_fu_364_p2);

    mul_16s_12s_26_1_1_U325 : component myproject_mul_16s_12s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        din0 => data_12_val,
        din1 => mul_ln42_9_fu_365_p1,
        dout => mul_ln42_9_fu_365_p2);

    mul_16s_12s_26_1_1_U326 : component myproject_mul_16s_12s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        din0 => data_9_val,
        din1 => mul_ln42_6_fu_366_p1,
        dout => mul_ln42_6_fu_366_p2);

    mul_16s_11s_26_1_1_U327 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => data_29_val,
        din1 => mul_ln42_16_fu_367_p1,
        dout => mul_ln42_16_fu_367_p2);

    mul_16s_10ns_26_1_1_U328 : component myproject_mul_16s_10ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => data_4_val,
        din1 => mul_ln73_1_fu_368_p1,
        dout => mul_ln73_1_fu_368_p2);

    mul_16s_10s_26_1_1_U329 : component myproject_mul_16s_10s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => data_25_val,
        din1 => mul_ln73_9_fu_369_p1,
        dout => mul_ln73_9_fu_369_p2);

    mul_16s_11s_26_1_1_U330 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => data_14_val,
        din1 => mul_ln42_11_fu_370_p1,
        dout => mul_ln42_11_fu_370_p2);

    mul_16s_10s_26_1_1_U331 : component myproject_mul_16s_10s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => data_21_val,
        din1 => mul_ln73_6_fu_371_p1,
        dout => mul_ln73_6_fu_371_p2);

    mul_16s_10s_26_1_1_U332 : component myproject_mul_16s_10s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => data_19_val,
        din1 => mul_ln73_4_fu_372_p1,
        dout => mul_ln73_4_fu_372_p2);

    mul_16s_11ns_26_1_1_U333 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => data_10_val,
        din1 => mul_ln42_7_fu_373_p1,
        dout => mul_ln42_7_fu_373_p2);

    mul_16s_11s_26_1_1_U334 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => data_1_val,
        din1 => mul_ln42_1_fu_374_p1,
        dout => mul_ln42_1_fu_374_p2);

    mul_16s_11ns_26_1_1_U335 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => data_26_val,
        din1 => mul_ln42_14_fu_375_p1,
        dout => mul_ln42_14_fu_375_p2);

    mul_16s_12s_26_1_1_U336 : component myproject_mul_16s_12s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        din0 => data_0_val,
        din1 => mul_ln42_fu_376_p1,
        dout => mul_ln42_fu_376_p2);

    mul_16s_9s_25_1_1_U337 : component myproject_mul_16s_9s_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 25)
    port map (
        din0 => data_3_val,
        din1 => mul_ln73_fu_377_p1,
        dout => mul_ln73_fu_377_p2);

    mul_16s_10ns_26_1_1_U338 : component myproject_mul_16s_10ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => data_20_val,
        din1 => mul_ln73_5_fu_378_p1,
        dout => mul_ln73_5_fu_378_p2);

    mul_16s_9s_25_1_1_U339 : component myproject_mul_16s_9s_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 25)
    port map (
        din0 => data_30_val,
        din1 => mul_ln73_11_fu_379_p1,
        dout => mul_ln73_11_fu_379_p2);

    mul_16s_12ns_26_1_1_U340 : component myproject_mul_16s_12ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        din0 => data_6_val,
        din1 => mul_ln42_4_fu_380_p1,
        dout => mul_ln42_4_fu_380_p2);

    mul_16s_11ns_26_1_1_U341 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => data_5_val,
        din1 => mul_ln42_3_fu_381_p1,
        dout => mul_ln42_3_fu_381_p2);

    mul_16s_10s_26_1_1_U342 : component myproject_mul_16s_10s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => data_23_val,
        din1 => mul_ln73_7_fu_382_p1,
        dout => mul_ln73_7_fu_382_p2);

    mul_16s_10ns_26_1_1_U343 : component myproject_mul_16s_10ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => data_15_val,
        din1 => mul_ln73_2_fu_383_p1,
        dout => mul_ln73_2_fu_383_p2);

    mul_16s_10s_26_1_1_U344 : component myproject_mul_16s_10s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => data_24_val,
        din1 => mul_ln73_8_fu_384_p1,
        dout => mul_ln73_8_fu_384_p2);

    mul_16s_11ns_26_1_1_U345 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => data_31_val,
        din1 => mul_ln42_17_fu_385_p1,
        dout => mul_ln42_17_fu_385_p2);

    mul_16s_12ns_26_1_1_U346 : component myproject_mul_16s_12ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        din0 => data_11_val,
        din1 => mul_ln42_8_fu_386_p1,
        dout => mul_ln42_8_fu_386_p2);

    mul_16s_11s_26_1_1_U347 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => data_17_val,
        din1 => mul_ln42_12_fu_387_p1,
        dout => mul_ln42_12_fu_387_p2);

    mul_16s_11s_26_1_1_U348 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => data_7_val,
        din1 => mul_ln42_5_fu_388_p1,
        dout => mul_ln42_5_fu_388_p2);

    mul_16s_10ns_26_1_1_U349 : component myproject_mul_16s_10ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => data_27_val,
        din1 => mul_ln73_10_fu_390_p1,
        dout => mul_ln73_10_fu_390_p2);

    mul_16s_10ns_26_1_1_U350 : component myproject_mul_16s_10ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => data_16_val,
        din1 => mul_ln73_3_fu_391_p1,
        dout => mul_ln73_3_fu_391_p2);

    mul_16s_11s_26_1_1_U351 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => data_2_val,
        din1 => mul_ln42_2_fu_392_p1,
        dout => mul_ln42_2_fu_392_p2);

    mul_16s_11ns_26_1_1_U352 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => data_28_val,
        din1 => mul_ln42_15_fu_393_p1,
        dout => mul_ln42_15_fu_393_p2);

    mul_16s_11s_26_1_1_U353 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => data_18_val,
        din1 => mul_ln42_13_fu_394_p1,
        dout => mul_ln42_13_fu_394_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln58_12_reg_5187 <= add_ln58_12_fu_5035_p2;
                add_ln58_17_reg_5192 <= add_ln58_17_fu_5053_p2;
                add_ln58_1_reg_5167 <= add_ln58_1_fu_4987_p2;
                add_ln58_20_reg_5197 <= add_ln58_20_fu_5071_p2;
                add_ln58_22_reg_5202 <= add_ln58_22_fu_5077_p2;
                add_ln58_23_reg_5207 <= add_ln58_23_fu_5083_p2;
                add_ln58_28_reg_5212 <= add_ln58_28_fu_5107_p2;
                add_ln58_5_reg_5172 <= add_ln58_5_fu_5005_p2;
                add_ln58_7_reg_5177 <= add_ln58_7_fu_5011_p2;
                add_ln58_8_reg_5182 <= add_ln58_8_fu_5017_p2;
                add_ln58_reg_5162 <= add_ln58_fu_4981_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_init_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln58_10_fu_5023_p2 <= std_logic_vector(unsigned(trunc_ln42_11_fu_4665_p4) + unsigned(trunc_ln42_12_fu_4680_p4));
    add_ln58_11_fu_5029_p2 <= std_logic_vector(unsigned(trunc_ln42_13_fu_4695_p4) + unsigned(trunc_ln42_14_fu_4710_p4));
    add_ln58_12_fu_5035_p2 <= std_logic_vector(unsigned(add_ln58_11_fu_5029_p2) + unsigned(add_ln58_10_fu_5023_p2));
    add_ln58_13_fu_5126_p2 <= std_logic_vector(unsigned(add_ln58_12_reg_5187) + unsigned(add_ln58_9_fu_5122_p2));
    add_ln58_14_fu_5131_p2 <= std_logic_vector(unsigned(add_ln58_13_fu_5126_p2) + unsigned(add_ln58_6_fu_5117_p2));
    add_ln58_15_fu_5041_p2 <= std_logic_vector(unsigned(trunc_ln42_15_fu_4725_p4) + unsigned(trunc_ln42_16_fu_4740_p4));
    add_ln58_16_fu_5047_p2 <= std_logic_vector(unsigned(trunc_ln42_17_fu_4755_p4) + unsigned(trunc_ln42_18_fu_4770_p4));
    add_ln58_17_fu_5053_p2 <= std_logic_vector(unsigned(add_ln58_16_fu_5047_p2) + unsigned(add_ln58_15_fu_5041_p2));
    add_ln58_18_fu_5059_p2 <= std_logic_vector(unsigned(trunc_ln42_19_fu_4785_p4) + unsigned(trunc_ln42_20_fu_4800_p4));
    add_ln58_19_fu_5065_p2 <= std_logic_vector(signed(sext_ln42_16_fu_4838_p1) + signed(trunc_ln42_22_fu_4847_p4));
    add_ln58_1_fu_4987_p2 <= std_logic_vector(unsigned(trunc_ln42_2_fu_4482_p4) + unsigned(sext_ln42_3_fu_4507_p1));
    add_ln58_20_fu_5071_p2 <= std_logic_vector(unsigned(add_ln58_19_fu_5065_p2) + unsigned(add_ln58_18_fu_5059_p2));
    add_ln58_21_fu_5137_p2 <= std_logic_vector(unsigned(add_ln58_20_reg_5197) + unsigned(add_ln58_17_reg_5192));
    add_ln58_22_fu_5077_p2 <= std_logic_vector(unsigned(trunc_ln42_23_fu_4862_p4) + unsigned(trunc_ln42_24_fu_4877_p4));
    add_ln58_23_fu_5083_p2 <= std_logic_vector(unsigned(trunc_ln42_25_fu_4892_p4) + unsigned(trunc_ln42_26_fu_4907_p4));
    add_ln58_24_fu_5141_p2 <= std_logic_vector(unsigned(add_ln58_23_reg_5207) + unsigned(add_ln58_22_reg_5202));
    add_ln58_25_fu_5089_p2 <= std_logic_vector(unsigned(trunc_ln42_27_fu_4922_p4) + unsigned(trunc_ln42_28_fu_4937_p4));
    add_ln58_26_fu_5095_p2 <= std_logic_vector(unsigned(trunc_ln42_30_fu_4971_p4) + unsigned(ap_const_lv16_64));
    add_ln58_27_fu_5101_p2 <= std_logic_vector(unsigned(add_ln58_26_fu_5095_p2) + unsigned(sext_ln42_20_fu_4962_p1));
    add_ln58_28_fu_5107_p2 <= std_logic_vector(unsigned(add_ln58_27_fu_5101_p2) + unsigned(add_ln58_25_fu_5089_p2));
    add_ln58_29_fu_5145_p2 <= std_logic_vector(unsigned(add_ln58_28_reg_5212) + unsigned(add_ln58_24_fu_5141_p2));
    add_ln58_2_fu_5113_p2 <= std_logic_vector(unsigned(add_ln58_1_reg_5167) + unsigned(add_ln58_reg_5162));
    add_ln58_30_fu_5150_p2 <= std_logic_vector(unsigned(add_ln58_29_fu_5145_p2) + unsigned(add_ln58_21_fu_5137_p2));
    add_ln58_3_fu_4993_p2 <= std_logic_vector(unsigned(trunc_ln42_4_fu_4516_p4) + unsigned(trunc_ln42_5_fu_4531_p4));
    add_ln58_4_fu_4999_p2 <= std_logic_vector(unsigned(trunc_ln42_6_fu_4546_p4) + unsigned(trunc_ln42_7_fu_4561_p4));
    add_ln58_5_fu_5005_p2 <= std_logic_vector(unsigned(add_ln58_4_fu_4999_p2) + unsigned(add_ln58_3_fu_4993_p2));
    add_ln58_6_fu_5117_p2 <= std_logic_vector(unsigned(add_ln58_5_reg_5172) + unsigned(add_ln58_2_fu_5113_p2));
    add_ln58_7_fu_5011_p2 <= std_logic_vector(signed(sext_ln42_7_fu_4611_p1) + signed(trunc_ln42_9_fu_4620_p4));
    add_ln58_8_fu_5017_p2 <= std_logic_vector(unsigned(trunc_ln42_s_fu_4635_p4) + unsigned(trunc_ln42_10_fu_4650_p4));
    add_ln58_9_fu_5122_p2 <= std_logic_vector(unsigned(add_ln58_8_reg_5182) + unsigned(add_ln58_7_reg_5177));
    add_ln58_fu_4981_p2 <= std_logic_vector(unsigned(trunc_ln_fu_4452_p4) + unsigned(trunc_ln42_1_fu_4467_p4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_init_pp0_assign_proc : process(ap_idle_pp0_0to0)
    begin
        if ((ap_idle_pp0_0to0 = ap_const_logic_1)) then 
            ap_reset_init_pp0 <= ap_const_logic_1;
        else 
            ap_reset_init_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= std_logic_vector(unsigned(add_ln58_30_fu_5150_p2) + unsigned(add_ln58_14_fu_5131_p2));
    mul_ln42_10_fu_364_p1 <= ap_const_lv26_4C8(12 - 1 downto 0);
    mul_ln42_11_fu_370_p1 <= ap_const_lv26_3FFFD85(11 - 1 downto 0);
    mul_ln42_12_fu_387_p1 <= ap_const_lv26_3FFFDA2(11 - 1 downto 0);
    mul_ln42_13_fu_394_p1 <= ap_const_lv26_3FFFC27(11 - 1 downto 0);
    mul_ln42_14_fu_375_p1 <= ap_const_lv26_307(11 - 1 downto 0);
    mul_ln42_15_fu_393_p1 <= ap_const_lv26_3A4(11 - 1 downto 0);
    mul_ln42_16_fu_367_p1 <= ap_const_lv26_3FFFDBF(11 - 1 downto 0);
    mul_ln42_17_fu_385_p1 <= ap_const_lv26_348(11 - 1 downto 0);
    mul_ln42_1_fu_374_p1 <= ap_const_lv26_3FFFD8A(11 - 1 downto 0);
    mul_ln42_2_fu_392_p1 <= ap_const_lv26_3FFFCBA(11 - 1 downto 0);
    mul_ln42_3_fu_381_p1 <= ap_const_lv26_287(11 - 1 downto 0);
    mul_ln42_4_fu_380_p1 <= ap_const_lv26_52E(12 - 1 downto 0);
    mul_ln42_5_fu_388_p1 <= ap_const_lv26_3FFFD87(11 - 1 downto 0);
    mul_ln42_6_fu_366_p1 <= ap_const_lv26_3FFF979(12 - 1 downto 0);
    mul_ln42_7_fu_373_p1 <= ap_const_lv26_236(11 - 1 downto 0);
    mul_ln42_8_fu_386_p1 <= ap_const_lv26_4E9(12 - 1 downto 0);
    mul_ln42_9_fu_365_p1 <= ap_const_lv26_3FFFAA5(12 - 1 downto 0);
    mul_ln42_fu_376_p1 <= ap_const_lv26_3FFFB7A(12 - 1 downto 0);
    mul_ln73_10_fu_390_p1 <= ap_const_lv26_193(10 - 1 downto 0);
    mul_ln73_11_fu_379_p1 <= ap_const_lv25_1FFFF32(9 - 1 downto 0);
    mul_ln73_1_fu_368_p1 <= ap_const_lv26_11F(10 - 1 downto 0);
    mul_ln73_2_fu_383_p1 <= ap_const_lv26_12C(10 - 1 downto 0);
    mul_ln73_3_fu_391_p1 <= ap_const_lv26_1F6(10 - 1 downto 0);
    mul_ln73_4_fu_372_p1 <= ap_const_lv26_3FFFEE4(10 - 1 downto 0);
    mul_ln73_5_fu_378_p1 <= ap_const_lv26_176(10 - 1 downto 0);
    mul_ln73_6_fu_371_p1 <= ap_const_lv26_3FFFE46(10 - 1 downto 0);
    mul_ln73_7_fu_382_p1 <= ap_const_lv26_3FFFE0D(10 - 1 downto 0);
    mul_ln73_8_fu_384_p1 <= ap_const_lv26_3FFFE69(10 - 1 downto 0);
    mul_ln73_9_fu_369_p1 <= ap_const_lv26_3FFFE4B(10 - 1 downto 0);
    mul_ln73_fu_377_p1 <= ap_const_lv25_1FFFF62(9 - 1 downto 0);
        sext_ln42_16_fu_4838_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_21_fu_4828_p4),16));

        sext_ln42_20_fu_4962_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_29_fu_4952_p4),16));

        sext_ln42_3_fu_4507_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_3_fu_4497_p4),16));

        sext_ln42_7_fu_4611_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_8_fu_4601_p4),16));

        sext_ln73_1_fu_4591_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_4583_p3),25));

        sext_ln73_2_fu_4818_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_4810_p3),24));

        sext_ln73_fu_4579_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_4571_p3),25));

    sub_ln73_1_fu_4822_p2 <= std_logic_vector(unsigned(ap_const_lv24_0) - unsigned(sext_ln73_2_fu_4818_p1));
    sub_ln73_fu_4595_p2 <= std_logic_vector(signed(sext_ln73_1_fu_4591_p1) - signed(sext_ln73_fu_4579_p1));
    tmp_5_fu_4583_p3 <= (data_8_val & ap_const_lv5_0);
    tmp_6_fu_4810_p3 <= (data_22_val & ap_const_lv7_0);
    tmp_fu_4571_p3 <= (data_8_val & ap_const_lv8_0);
    trunc_ln42_10_fu_4650_p4 <= mul_ln42_8_fu_386_p2(25 downto 10);
    trunc_ln42_11_fu_4665_p4 <= mul_ln42_9_fu_365_p2(25 downto 10);
    trunc_ln42_12_fu_4680_p4 <= mul_ln42_10_fu_364_p2(25 downto 10);
    trunc_ln42_13_fu_4695_p4 <= mul_ln42_11_fu_370_p2(25 downto 10);
    trunc_ln42_14_fu_4710_p4 <= mul_ln73_2_fu_383_p2(25 downto 10);
    trunc_ln42_15_fu_4725_p4 <= mul_ln73_3_fu_391_p2(25 downto 10);
    trunc_ln42_16_fu_4740_p4 <= mul_ln42_12_fu_387_p2(25 downto 10);
    trunc_ln42_17_fu_4755_p4 <= mul_ln42_13_fu_394_p2(25 downto 10);
    trunc_ln42_18_fu_4770_p4 <= mul_ln73_4_fu_372_p2(25 downto 10);
    trunc_ln42_19_fu_4785_p4 <= mul_ln73_5_fu_378_p2(25 downto 10);
    trunc_ln42_1_fu_4467_p4 <= mul_ln42_1_fu_374_p2(25 downto 10);
    trunc_ln42_20_fu_4800_p4 <= mul_ln73_6_fu_371_p2(25 downto 10);
    trunc_ln42_21_fu_4828_p4 <= sub_ln73_1_fu_4822_p2(23 downto 10);
    trunc_ln42_22_fu_4847_p4 <= mul_ln73_7_fu_382_p2(25 downto 10);
    trunc_ln42_23_fu_4862_p4 <= mul_ln73_8_fu_384_p2(25 downto 10);
    trunc_ln42_24_fu_4877_p4 <= mul_ln73_9_fu_369_p2(25 downto 10);
    trunc_ln42_25_fu_4892_p4 <= mul_ln42_14_fu_375_p2(25 downto 10);
    trunc_ln42_26_fu_4907_p4 <= mul_ln73_10_fu_390_p2(25 downto 10);
    trunc_ln42_27_fu_4922_p4 <= mul_ln42_15_fu_393_p2(25 downto 10);
    trunc_ln42_28_fu_4937_p4 <= mul_ln42_16_fu_367_p2(25 downto 10);
    trunc_ln42_29_fu_4952_p4 <= mul_ln73_11_fu_379_p2(24 downto 10);
    trunc_ln42_2_fu_4482_p4 <= mul_ln42_2_fu_392_p2(25 downto 10);
    trunc_ln42_30_fu_4971_p4 <= mul_ln42_17_fu_385_p2(25 downto 10);
    trunc_ln42_3_fu_4497_p4 <= mul_ln73_fu_377_p2(24 downto 10);
    trunc_ln42_4_fu_4516_p4 <= mul_ln73_1_fu_368_p2(25 downto 10);
    trunc_ln42_5_fu_4531_p4 <= mul_ln42_3_fu_381_p2(25 downto 10);
    trunc_ln42_6_fu_4546_p4 <= mul_ln42_4_fu_380_p2(25 downto 10);
    trunc_ln42_7_fu_4561_p4 <= mul_ln42_5_fu_388_p2(25 downto 10);
    trunc_ln42_8_fu_4601_p4 <= sub_ln73_fu_4595_p2(24 downto 10);
    trunc_ln42_9_fu_4620_p4 <= mul_ln42_6_fu_366_p2(25 downto 10);
    trunc_ln42_s_fu_4635_p4 <= mul_ln42_7_fu_373_p2(25 downto 10);
    trunc_ln_fu_4452_p4 <= mul_ln42_fu_376_p2(25 downto 10);
end behav;
