-- ==============================================================
-- Generated by Vitis HLS v2023.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject is
port (
    input_1_TDATA : IN STD_LOGIC_VECTOR (159 downto 0);
    layer5_out_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_1_TVALID : IN STD_LOGIC;
    input_1_TREADY : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    layer5_out_TVALID : OUT STD_LOGIC;
    layer5_out_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of myproject is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "myproject_myproject,hls_ip_2023_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.556000,HLS_SYN_LAT=26,HLS_SYN_TPT=7,HLS_SYN_MEM=34,HLS_SYN_DSP=0,HLS_SYN_FF=12830,HLS_SYN_LUT=5942,HLS_VERSION=2023_1_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_start : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_done : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_continue : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_idle : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_ready : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_layer2_out_din : STD_LOGIC_VECTOR (511 downto 0);
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_layer2_out_write : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_start_out : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_start_write : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_input_1_TREADY : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_start_out : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_start_write : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_layer2_out_read : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_layer3_out_din : STD_LOGIC_VECTOR (511 downto 0);
    signal relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_layer3_out_write : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_start : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_done : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_continue : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_idle : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_ready : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_layer3_out_read : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_layer4_out_din : STD_LOGIC_VECTOR (15 downto 0);
    signal dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_layer4_out_write : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_start_out : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_start_write : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_start : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_done : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_continue : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_idle : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_ready : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_layer4_out_read : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_layer5_out_TDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_layer5_out_TVALID : STD_LOGIC;
    signal layer2_out_full_n : STD_LOGIC;
    signal layer2_out_dout : STD_LOGIC_VECTOR (511 downto 0);
    signal layer2_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer2_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer2_out_empty_n : STD_LOGIC;
    signal layer3_out_full_n : STD_LOGIC;
    signal layer3_out_dout : STD_LOGIC_VECTOR (511 downto 0);
    signal layer3_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer3_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer3_out_empty_n : STD_LOGIC;
    signal layer4_out_full_n : STD_LOGIC;
    signal layer4_out_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer4_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer4_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer4_out_empty_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_empty_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_full_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_empty_n : STD_LOGIC;
    signal start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_full_n : STD_LOGIC;
    signal start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_empty_n : STD_LOGIC;

    component myproject_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_1_TVALID : IN STD_LOGIC;
        layer2_out_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer2_out_full_n : IN STD_LOGIC;
        layer2_out_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        input_1_TDATA : IN STD_LOGIC_VECTOR (159 downto 0);
        input_1_TREADY : OUT STD_LOGIC );
    end component;


    component myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer2_out_dout : IN STD_LOGIC_VECTOR (511 downto 0);
        layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer2_out_empty_n : IN STD_LOGIC;
        layer2_out_read : OUT STD_LOGIC;
        layer3_out_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer3_out_full_n : IN STD_LOGIC;
        layer3_out_write : OUT STD_LOGIC );
    end component;


    component myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer3_out_dout : IN STD_LOGIC_VECTOR (511 downto 0);
        layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer3_out_empty_n : IN STD_LOGIC;
        layer3_out_read : OUT STD_LOGIC;
        layer4_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer4_out_full_n : IN STD_LOGIC;
        layer4_out_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC );
    end component;


    component myproject_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer4_out_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer4_out_empty_n : IN STD_LOGIC;
        layer4_out_read : OUT STD_LOGIC;
        layer5_out_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        layer5_out_TVALID : OUT STD_LOGIC;
        layer5_out_TREADY : IN STD_LOGIC );
    end component;


    component myproject_fifo_w512_d1_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (511 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (511 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_fifo_w16_d1_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0 : component myproject_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_start,
        start_full_n => start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_full_n,
        ap_done => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_done,
        ap_continue => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_continue,
        ap_idle => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_idle,
        ap_ready => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_ready,
        input_1_TVALID => input_1_TVALID,
        layer2_out_din => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_layer2_out_din,
        layer2_out_num_data_valid => layer2_out_num_data_valid,
        layer2_out_fifo_cap => layer2_out_fifo_cap,
        layer2_out_full_n => layer2_out_full_n,
        layer2_out_write => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_layer2_out_write,
        start_out => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_start_out,
        start_write => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_start_write,
        input_1_TDATA => input_1_TDATA,
        input_1_TREADY => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_input_1_TREADY);

    relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0 : component myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_start,
        start_full_n => start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_full_n,
        ap_done => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_done,
        ap_continue => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_continue,
        ap_idle => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_idle,
        ap_ready => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_ready,
        start_out => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_start_out,
        start_write => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_start_write,
        layer2_out_dout => layer2_out_dout,
        layer2_out_num_data_valid => layer2_out_num_data_valid,
        layer2_out_fifo_cap => layer2_out_fifo_cap,
        layer2_out_empty_n => layer2_out_empty_n,
        layer2_out_read => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_layer2_out_read,
        layer3_out_din => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_layer3_out_din,
        layer3_out_num_data_valid => layer3_out_num_data_valid,
        layer3_out_fifo_cap => layer3_out_fifo_cap,
        layer3_out_full_n => layer3_out_full_n,
        layer3_out_write => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_layer3_out_write);

    dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0 : component myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_start,
        start_full_n => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_full_n,
        ap_done => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_done,
        ap_continue => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_continue,
        ap_idle => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_idle,
        ap_ready => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_ready,
        layer3_out_dout => layer3_out_dout,
        layer3_out_num_data_valid => layer3_out_num_data_valid,
        layer3_out_fifo_cap => layer3_out_fifo_cap,
        layer3_out_empty_n => layer3_out_empty_n,
        layer3_out_read => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_layer3_out_read,
        layer4_out_din => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_layer4_out_din,
        layer4_out_num_data_valid => layer4_out_num_data_valid,
        layer4_out_fifo_cap => layer4_out_fifo_cap,
        layer4_out_full_n => layer4_out_full_n,
        layer4_out_write => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_layer4_out_write,
        start_out => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_start_out,
        start_write => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_start_write);

    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0 : component myproject_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_start,
        ap_done => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_done,
        ap_continue => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_continue,
        ap_idle => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_idle,
        ap_ready => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_ready,
        layer4_out_dout => layer4_out_dout,
        layer4_out_num_data_valid => layer4_out_num_data_valid,
        layer4_out_fifo_cap => layer4_out_fifo_cap,
        layer4_out_empty_n => layer4_out_empty_n,
        layer4_out_read => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_layer4_out_read,
        layer5_out_TDATA => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_layer5_out_TDATA,
        layer5_out_TVALID => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_layer5_out_TVALID,
        layer5_out_TREADY => layer5_out_TREADY);

    layer2_out_U : component myproject_fifo_w512_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_layer2_out_din,
        if_full_n => layer2_out_full_n,
        if_write => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_layer2_out_write,
        if_dout => layer2_out_dout,
        if_num_data_valid => layer2_out_num_data_valid,
        if_fifo_cap => layer2_out_fifo_cap,
        if_empty_n => layer2_out_empty_n,
        if_read => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_layer2_out_read);

    layer3_out_U : component myproject_fifo_w512_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_layer3_out_din,
        if_full_n => layer3_out_full_n,
        if_write => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_layer3_out_write,
        if_dout => layer3_out_dout,
        if_num_data_valid => layer3_out_num_data_valid,
        if_fifo_cap => layer3_out_fifo_cap,
        if_empty_n => layer3_out_empty_n,
        if_read => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_layer3_out_read);

    layer4_out_U : component myproject_fifo_w16_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_layer4_out_din,
        if_full_n => layer4_out_full_n,
        if_write => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_layer4_out_write,
        if_dout => layer4_out_dout,
        if_num_data_valid => layer4_out_num_data_valid,
        if_fifo_cap => layer4_out_fifo_cap,
        if_empty_n => layer4_out_empty_n,
        if_read => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_layer4_out_read);

    start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_U : component myproject_start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_din,
        if_full_n => start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_full_n,
        if_write => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_start_write,
        if_dout => start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_dout,
        if_empty_n => start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_empty_n,
        if_read => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_ready);

    start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_U : component myproject_start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_din,
        if_full_n => start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_full_n,
        if_write => relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_start_write,
        if_dout => start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_dout,
        if_empty_n => start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_empty_n,
        if_read => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_ready);

    start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_U : component myproject_start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_din,
        if_full_n => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_full_n,
        if_write => dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_start_write,
        if_dout => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_dout,
        if_empty_n => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_empty_n,
        if_read => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_ready);




    ap_done <= sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_done;
    ap_idle <= (sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_idle and relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_idle and dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_idle and dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_idle);
    ap_ready <= dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_continue <= ap_const_logic_1;
    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_ap_start <= ap_start;
    dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_continue <= ap_const_logic_1;
    dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_ap_start <= start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_empty_n;
    input_1_TREADY <= dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_U0_input_1_TREADY;
    layer5_out_TDATA <= sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_layer5_out_TDATA;
    layer5_out_TVALID <= sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_layer5_out_TVALID;
    relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_ap_start <= start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_empty_n;
    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_continue <= ap_const_logic_1;
    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_ap_start <= start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_empty_n;
    start_for_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_1u_config4_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config3_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
