// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_64u_relu_config3_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer2_out_dout,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap,
        layer2_out_empty_n,
        layer2_out_read,
        layer3_out_din,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap,
        layer3_out_full_n,
        layer3_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [1023:0] layer2_out_dout;
input  [1:0] layer2_out_num_data_valid;
input  [1:0] layer2_out_fifo_cap;
input   layer2_out_empty_n;
output   layer2_out_read;
output  [1023:0] layer3_out_din;
input  [1:0] layer3_out_num_data_valid;
input  [1:0] layer3_out_fifo_cap;
input   layer3_out_full_n;
output   layer3_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer2_out_read;
reg layer3_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer2_out_blk_n;
reg    layer3_out_blk_n;
wire    ap_CS_fsm_state3;
wire   [15:0] in_data_fu_419_p1;
reg   [15:0] in_data_reg_2780;
reg    ap_block_state1;
wire   [14:0] trunc_ln44_1_fu_423_p1;
reg   [14:0] trunc_ln44_1_reg_2785;
reg   [15:0] trunc_ln44_2_reg_2790;
reg   [15:0] trunc_ln44_3_reg_2795;
reg   [15:0] in_data_4_reg_2800;
reg   [14:0] trunc_ln44_s_reg_2805;
reg   [15:0] in_data_5_reg_2810;
reg   [14:0] trunc_ln44_4_reg_2815;
reg   [15:0] in_data_6_reg_2820;
reg   [14:0] trunc_ln44_5_reg_2825;
reg   [15:0] tmp_reg_2830;
reg   [14:0] trunc_ln44_6_reg_2835;
reg   [15:0] tmp_s_reg_2840;
reg   [14:0] trunc_ln44_7_reg_2845;
reg   [15:0] tmp_7_reg_2850;
reg   [14:0] trunc_ln44_8_reg_2855;
reg   [15:0] tmp_8_reg_2860;
reg   [14:0] trunc_ln44_9_reg_2865;
reg   [15:0] tmp_9_reg_2870;
reg   [14:0] trunc_ln44_10_reg_2875;
reg   [15:0] tmp_1_reg_2880;
reg   [14:0] trunc_ln44_11_reg_2885;
reg   [15:0] tmp_2_reg_2890;
reg   [14:0] trunc_ln44_12_reg_2895;
reg   [15:0] tmp_3_reg_2900;
reg   [14:0] trunc_ln44_13_reg_2905;
reg   [15:0] tmp_4_reg_2910;
reg   [14:0] trunc_ln44_14_reg_2915;
reg   [15:0] tmp_5_reg_2920;
reg   [14:0] trunc_ln44_15_reg_2925;
reg   [15:0] tmp_6_reg_2930;
reg   [14:0] trunc_ln44_16_reg_2935;
reg   [15:0] tmp_10_reg_2940;
reg   [14:0] trunc_ln44_17_reg_2945;
reg   [15:0] tmp_11_reg_2950;
reg   [14:0] trunc_ln44_18_reg_2955;
reg   [15:0] tmp_12_reg_2960;
reg   [14:0] trunc_ln44_19_reg_2965;
reg   [15:0] tmp_13_reg_2970;
reg   [14:0] trunc_ln44_20_reg_2975;
reg   [15:0] tmp_14_reg_2980;
reg   [14:0] trunc_ln44_21_reg_2985;
reg   [15:0] tmp_15_reg_2990;
reg   [14:0] trunc_ln44_22_reg_2995;
reg   [15:0] tmp_16_reg_3000;
reg   [14:0] trunc_ln44_23_reg_3005;
reg   [15:0] tmp_17_reg_3010;
reg   [14:0] trunc_ln44_24_reg_3015;
reg   [15:0] tmp_18_reg_3020;
reg   [14:0] trunc_ln44_25_reg_3025;
reg   [15:0] tmp_19_reg_3030;
reg   [14:0] trunc_ln44_26_reg_3035;
reg   [15:0] tmp_20_reg_3040;
reg   [14:0] trunc_ln44_27_reg_3045;
reg   [15:0] tmp_21_reg_3050;
reg   [14:0] trunc_ln44_28_reg_3055;
reg   [15:0] tmp_22_reg_3060;
reg   [14:0] trunc_ln44_29_reg_3065;
reg   [15:0] tmp_23_reg_3070;
reg   [14:0] trunc_ln44_30_reg_3075;
reg   [15:0] tmp_24_reg_3080;
reg   [14:0] trunc_ln44_31_reg_3085;
reg   [15:0] tmp_25_reg_3090;
reg   [14:0] trunc_ln44_32_reg_3095;
reg   [15:0] tmp_26_reg_3100;
reg   [14:0] trunc_ln44_33_reg_3105;
reg   [15:0] tmp_27_reg_3110;
reg   [14:0] trunc_ln44_34_reg_3115;
reg   [15:0] tmp_28_reg_3120;
reg   [14:0] trunc_ln44_35_reg_3125;
reg   [15:0] tmp_29_reg_3130;
reg   [14:0] trunc_ln44_36_reg_3135;
reg   [15:0] tmp_30_reg_3140;
reg   [14:0] trunc_ln44_37_reg_3145;
reg   [15:0] tmp_31_reg_3150;
reg   [14:0] trunc_ln44_38_reg_3155;
reg   [15:0] tmp_32_reg_3160;
reg   [14:0] trunc_ln44_39_reg_3165;
reg   [15:0] tmp_33_reg_3170;
reg   [14:0] trunc_ln44_40_reg_3175;
reg   [15:0] tmp_34_reg_3180;
reg   [14:0] trunc_ln44_41_reg_3185;
reg   [15:0] tmp_35_reg_3190;
reg   [14:0] trunc_ln44_42_reg_3195;
reg   [15:0] tmp_36_reg_3200;
reg   [14:0] trunc_ln44_43_reg_3205;
reg   [15:0] tmp_37_reg_3210;
reg   [14:0] trunc_ln44_44_reg_3215;
reg   [15:0] tmp_38_reg_3220;
reg   [14:0] trunc_ln44_45_reg_3225;
reg   [15:0] tmp_39_reg_3230;
reg   [14:0] trunc_ln44_46_reg_3235;
reg   [15:0] tmp_40_reg_3240;
reg   [14:0] trunc_ln44_47_reg_3245;
reg   [15:0] tmp_41_reg_3250;
reg   [14:0] trunc_ln44_48_reg_3255;
reg   [15:0] tmp_42_reg_3260;
reg   [14:0] trunc_ln44_49_reg_3265;
reg   [15:0] tmp_43_reg_3270;
reg   [14:0] trunc_ln44_50_reg_3275;
reg   [15:0] tmp_44_reg_3280;
reg   [14:0] trunc_ln44_51_reg_3285;
reg   [15:0] tmp_45_reg_3290;
reg   [14:0] trunc_ln44_52_reg_3295;
reg   [15:0] tmp_46_reg_3300;
reg   [14:0] trunc_ln44_53_reg_3305;
reg   [15:0] tmp_47_reg_3310;
reg   [14:0] trunc_ln44_54_reg_3315;
reg   [15:0] tmp_48_reg_3320;
reg   [14:0] trunc_ln44_55_reg_3325;
reg   [15:0] tmp_49_reg_3330;
reg   [14:0] trunc_ln44_56_reg_3335;
reg   [15:0] tmp_50_reg_3340;
reg   [14:0] trunc_ln44_57_reg_3345;
reg   [15:0] tmp_51_reg_3350;
reg   [14:0] trunc_ln44_58_reg_3355;
reg   [15:0] tmp_52_reg_3360;
reg   [14:0] trunc_ln44_59_reg_3365;
reg   [15:0] tmp_53_reg_3370;
reg   [14:0] trunc_ln44_60_reg_3375;
reg   [15:0] tmp_54_reg_3380;
reg   [14:0] trunc_ln44_61_reg_3385;
reg   [15:0] tmp_55_reg_3390;
reg   [14:0] trunc_ln44_62_reg_3395;
reg   [15:0] tmp_56_reg_3400;
reg   [14:0] trunc_ln44_63_reg_3405;
reg   [14:0] trunc_ln44_64_reg_3410;
reg   [14:0] trunc_ln_reg_3415;
wire   [14:0] select_ln51_fu_1692_p3;
reg   [14:0] select_ln51_reg_3420;
wire    ap_CS_fsm_state2;
wire   [14:0] select_ln51_1_fu_1704_p3;
reg   [14:0] select_ln51_1_reg_3425;
wire   [14:0] select_ln51_2_fu_1716_p3;
reg   [14:0] select_ln51_2_reg_3430;
wire   [14:0] select_ln51_3_fu_1728_p3;
reg   [14:0] select_ln51_3_reg_3435;
wire   [14:0] select_ln51_4_fu_1740_p3;
reg   [14:0] select_ln51_4_reg_3440;
wire   [14:0] select_ln51_5_fu_1752_p3;
reg   [14:0] select_ln51_5_reg_3445;
wire   [14:0] select_ln51_6_fu_1764_p3;
reg   [14:0] select_ln51_6_reg_3450;
wire   [14:0] select_ln51_7_fu_1776_p3;
reg   [14:0] select_ln51_7_reg_3455;
wire   [14:0] select_ln51_8_fu_1788_p3;
reg   [14:0] select_ln51_8_reg_3460;
wire   [14:0] select_ln51_9_fu_1800_p3;
reg   [14:0] select_ln51_9_reg_3465;
wire   [14:0] select_ln51_10_fu_1812_p3;
reg   [14:0] select_ln51_10_reg_3470;
wire   [14:0] select_ln51_11_fu_1824_p3;
reg   [14:0] select_ln51_11_reg_3475;
wire   [14:0] select_ln51_12_fu_1836_p3;
reg   [14:0] select_ln51_12_reg_3480;
wire   [14:0] select_ln51_13_fu_1848_p3;
reg   [14:0] select_ln51_13_reg_3485;
wire   [14:0] select_ln51_14_fu_1860_p3;
reg   [14:0] select_ln51_14_reg_3490;
wire   [14:0] select_ln51_15_fu_1872_p3;
reg   [14:0] select_ln51_15_reg_3495;
wire   [14:0] select_ln51_16_fu_1884_p3;
reg   [14:0] select_ln51_16_reg_3500;
wire   [14:0] select_ln51_17_fu_1896_p3;
reg   [14:0] select_ln51_17_reg_3505;
wire   [14:0] select_ln51_18_fu_1908_p3;
reg   [14:0] select_ln51_18_reg_3510;
wire   [14:0] select_ln51_19_fu_1920_p3;
reg   [14:0] select_ln51_19_reg_3515;
wire   [14:0] select_ln51_20_fu_1932_p3;
reg   [14:0] select_ln51_20_reg_3520;
wire   [14:0] select_ln51_21_fu_1944_p3;
reg   [14:0] select_ln51_21_reg_3525;
wire   [14:0] select_ln51_22_fu_1956_p3;
reg   [14:0] select_ln51_22_reg_3530;
wire   [14:0] select_ln51_23_fu_1968_p3;
reg   [14:0] select_ln51_23_reg_3535;
wire   [14:0] select_ln51_24_fu_1980_p3;
reg   [14:0] select_ln51_24_reg_3540;
wire   [14:0] select_ln51_25_fu_1992_p3;
reg   [14:0] select_ln51_25_reg_3545;
wire   [14:0] select_ln51_26_fu_2004_p3;
reg   [14:0] select_ln51_26_reg_3550;
wire   [14:0] select_ln51_27_fu_2016_p3;
reg   [14:0] select_ln51_27_reg_3555;
wire   [14:0] select_ln51_28_fu_2028_p3;
reg   [14:0] select_ln51_28_reg_3560;
wire   [14:0] select_ln51_29_fu_2040_p3;
reg   [14:0] select_ln51_29_reg_3565;
wire   [14:0] select_ln51_30_fu_2052_p3;
reg   [14:0] select_ln51_30_reg_3570;
wire   [14:0] select_ln51_31_fu_2064_p3;
reg   [14:0] select_ln51_31_reg_3575;
wire   [14:0] select_ln51_32_fu_2076_p3;
reg   [14:0] select_ln51_32_reg_3580;
wire   [14:0] select_ln51_33_fu_2088_p3;
reg   [14:0] select_ln51_33_reg_3585;
wire   [14:0] select_ln51_34_fu_2100_p3;
reg   [14:0] select_ln51_34_reg_3590;
wire   [14:0] select_ln51_35_fu_2112_p3;
reg   [14:0] select_ln51_35_reg_3595;
wire   [14:0] select_ln51_36_fu_2124_p3;
reg   [14:0] select_ln51_36_reg_3600;
wire   [14:0] select_ln51_37_fu_2136_p3;
reg   [14:0] select_ln51_37_reg_3605;
wire   [14:0] select_ln51_38_fu_2148_p3;
reg   [14:0] select_ln51_38_reg_3610;
wire   [14:0] select_ln51_39_fu_2160_p3;
reg   [14:0] select_ln51_39_reg_3615;
wire   [14:0] select_ln51_40_fu_2172_p3;
reg   [14:0] select_ln51_40_reg_3620;
wire   [14:0] select_ln51_41_fu_2184_p3;
reg   [14:0] select_ln51_41_reg_3625;
wire   [14:0] select_ln51_42_fu_2196_p3;
reg   [14:0] select_ln51_42_reg_3630;
wire   [14:0] select_ln51_43_fu_2208_p3;
reg   [14:0] select_ln51_43_reg_3635;
wire   [14:0] select_ln51_44_fu_2220_p3;
reg   [14:0] select_ln51_44_reg_3640;
wire   [14:0] select_ln51_45_fu_2232_p3;
reg   [14:0] select_ln51_45_reg_3645;
wire   [14:0] select_ln51_46_fu_2244_p3;
reg   [14:0] select_ln51_46_reg_3650;
wire   [14:0] select_ln51_47_fu_2256_p3;
reg   [14:0] select_ln51_47_reg_3655;
wire   [14:0] select_ln51_48_fu_2268_p3;
reg   [14:0] select_ln51_48_reg_3660;
wire   [14:0] select_ln51_49_fu_2280_p3;
reg   [14:0] select_ln51_49_reg_3665;
wire   [14:0] select_ln51_50_fu_2292_p3;
reg   [14:0] select_ln51_50_reg_3670;
wire   [14:0] select_ln51_51_fu_2304_p3;
reg   [14:0] select_ln51_51_reg_3675;
wire   [14:0] select_ln51_52_fu_2316_p3;
reg   [14:0] select_ln51_52_reg_3680;
wire   [14:0] select_ln51_53_fu_2328_p3;
reg   [14:0] select_ln51_53_reg_3685;
wire   [14:0] select_ln51_54_fu_2340_p3;
reg   [14:0] select_ln51_54_reg_3690;
wire   [14:0] select_ln51_55_fu_2352_p3;
reg   [14:0] select_ln51_55_reg_3695;
wire   [14:0] select_ln51_56_fu_2364_p3;
reg   [14:0] select_ln51_56_reg_3700;
wire   [14:0] select_ln51_57_fu_2376_p3;
reg   [14:0] select_ln51_57_reg_3705;
wire   [14:0] select_ln51_58_fu_2388_p3;
reg   [14:0] select_ln51_58_reg_3710;
wire   [14:0] select_ln51_59_fu_2400_p3;
reg   [14:0] select_ln51_59_reg_3715;
wire   [14:0] select_ln51_60_fu_2412_p3;
reg   [14:0] select_ln51_60_reg_3720;
wire   [14:0] select_ln51_61_fu_2424_p3;
reg   [14:0] select_ln51_61_reg_3725;
wire   [14:0] select_ln51_62_fu_2436_p3;
reg   [14:0] select_ln51_62_reg_3730;
wire   [14:0] select_ln51_63_fu_2448_p3;
reg   [14:0] select_ln51_63_reg_3735;
wire   [0:0] icmp_ln51_fu_1687_p2;
wire   [0:0] icmp_ln51_1_fu_1699_p2;
wire   [0:0] icmp_ln51_2_fu_1711_p2;
wire   [0:0] icmp_ln51_3_fu_1723_p2;
wire   [0:0] icmp_ln51_4_fu_1735_p2;
wire   [0:0] icmp_ln51_5_fu_1747_p2;
wire   [0:0] icmp_ln51_6_fu_1759_p2;
wire   [0:0] icmp_ln51_7_fu_1771_p2;
wire   [0:0] icmp_ln51_8_fu_1783_p2;
wire   [0:0] icmp_ln51_9_fu_1795_p2;
wire   [0:0] icmp_ln51_10_fu_1807_p2;
wire   [0:0] icmp_ln51_11_fu_1819_p2;
wire   [0:0] icmp_ln51_12_fu_1831_p2;
wire   [0:0] icmp_ln51_13_fu_1843_p2;
wire   [0:0] icmp_ln51_14_fu_1855_p2;
wire   [0:0] icmp_ln51_15_fu_1867_p2;
wire   [0:0] icmp_ln51_16_fu_1879_p2;
wire   [0:0] icmp_ln51_17_fu_1891_p2;
wire   [0:0] icmp_ln51_18_fu_1903_p2;
wire   [0:0] icmp_ln51_19_fu_1915_p2;
wire   [0:0] icmp_ln51_20_fu_1927_p2;
wire   [0:0] icmp_ln51_21_fu_1939_p2;
wire   [0:0] icmp_ln51_22_fu_1951_p2;
wire   [0:0] icmp_ln51_23_fu_1963_p2;
wire   [0:0] icmp_ln51_24_fu_1975_p2;
wire   [0:0] icmp_ln51_25_fu_1987_p2;
wire   [0:0] icmp_ln51_26_fu_1999_p2;
wire   [0:0] icmp_ln51_27_fu_2011_p2;
wire   [0:0] icmp_ln51_28_fu_2023_p2;
wire   [0:0] icmp_ln51_29_fu_2035_p2;
wire   [0:0] icmp_ln51_30_fu_2047_p2;
wire   [0:0] icmp_ln51_31_fu_2059_p2;
wire   [0:0] icmp_ln51_32_fu_2071_p2;
wire   [0:0] icmp_ln51_33_fu_2083_p2;
wire   [0:0] icmp_ln51_34_fu_2095_p2;
wire   [0:0] icmp_ln51_35_fu_2107_p2;
wire   [0:0] icmp_ln51_36_fu_2119_p2;
wire   [0:0] icmp_ln51_37_fu_2131_p2;
wire   [0:0] icmp_ln51_38_fu_2143_p2;
wire   [0:0] icmp_ln51_39_fu_2155_p2;
wire   [0:0] icmp_ln51_40_fu_2167_p2;
wire   [0:0] icmp_ln51_41_fu_2179_p2;
wire   [0:0] icmp_ln51_42_fu_2191_p2;
wire   [0:0] icmp_ln51_43_fu_2203_p2;
wire   [0:0] icmp_ln51_44_fu_2215_p2;
wire   [0:0] icmp_ln51_45_fu_2227_p2;
wire   [0:0] icmp_ln51_46_fu_2239_p2;
wire   [0:0] icmp_ln51_47_fu_2251_p2;
wire   [0:0] icmp_ln51_48_fu_2263_p2;
wire   [0:0] icmp_ln51_49_fu_2275_p2;
wire   [0:0] icmp_ln51_50_fu_2287_p2;
wire   [0:0] icmp_ln51_51_fu_2299_p2;
wire   [0:0] icmp_ln51_52_fu_2311_p2;
wire   [0:0] icmp_ln51_53_fu_2323_p2;
wire   [0:0] icmp_ln51_54_fu_2335_p2;
wire   [0:0] icmp_ln51_55_fu_2347_p2;
wire   [0:0] icmp_ln51_56_fu_2359_p2;
wire   [0:0] icmp_ln51_57_fu_2371_p2;
wire   [0:0] icmp_ln51_58_fu_2383_p2;
wire   [0:0] icmp_ln51_59_fu_2395_p2;
wire   [0:0] icmp_ln51_60_fu_2407_p2;
wire   [0:0] icmp_ln51_61_fu_2419_p2;
wire   [0:0] icmp_ln51_62_fu_2431_p2;
wire   [0:0] icmp_ln51_63_fu_2443_p2;
wire   [15:0] zext_ln51_63_fu_2641_p1;
wire   [15:0] zext_ln51_62_fu_2638_p1;
wire   [15:0] zext_ln51_61_fu_2635_p1;
wire   [15:0] zext_ln51_60_fu_2632_p1;
wire   [15:0] zext_ln51_59_fu_2629_p1;
wire   [15:0] zext_ln51_58_fu_2626_p1;
wire   [15:0] zext_ln51_57_fu_2623_p1;
wire   [15:0] zext_ln51_56_fu_2620_p1;
wire   [15:0] zext_ln51_55_fu_2617_p1;
wire   [15:0] zext_ln51_54_fu_2614_p1;
wire   [15:0] zext_ln51_53_fu_2611_p1;
wire   [15:0] zext_ln51_52_fu_2608_p1;
wire   [15:0] zext_ln51_51_fu_2605_p1;
wire   [15:0] zext_ln51_50_fu_2602_p1;
wire   [15:0] zext_ln51_49_fu_2599_p1;
wire   [15:0] zext_ln51_48_fu_2596_p1;
wire   [15:0] zext_ln51_47_fu_2593_p1;
wire   [15:0] zext_ln51_46_fu_2590_p1;
wire   [15:0] zext_ln51_45_fu_2587_p1;
wire   [15:0] zext_ln51_44_fu_2584_p1;
wire   [15:0] zext_ln51_43_fu_2581_p1;
wire   [15:0] zext_ln51_42_fu_2578_p1;
wire   [15:0] zext_ln51_41_fu_2575_p1;
wire   [15:0] zext_ln51_40_fu_2572_p1;
wire   [15:0] zext_ln51_39_fu_2569_p1;
wire   [15:0] zext_ln51_38_fu_2566_p1;
wire   [15:0] zext_ln51_37_fu_2563_p1;
wire   [15:0] zext_ln51_36_fu_2560_p1;
wire   [15:0] zext_ln51_35_fu_2557_p1;
wire   [15:0] zext_ln51_34_fu_2554_p1;
wire   [15:0] zext_ln51_33_fu_2551_p1;
wire   [15:0] zext_ln51_32_fu_2548_p1;
wire   [15:0] zext_ln51_31_fu_2545_p1;
wire   [15:0] zext_ln51_30_fu_2542_p1;
wire   [15:0] zext_ln51_29_fu_2539_p1;
wire   [15:0] zext_ln51_28_fu_2536_p1;
wire   [15:0] zext_ln51_27_fu_2533_p1;
wire   [15:0] zext_ln51_26_fu_2530_p1;
wire   [15:0] zext_ln51_25_fu_2527_p1;
wire   [15:0] zext_ln51_24_fu_2524_p1;
wire   [15:0] zext_ln51_23_fu_2521_p1;
wire   [15:0] zext_ln51_22_fu_2518_p1;
wire   [15:0] zext_ln51_21_fu_2515_p1;
wire   [15:0] zext_ln51_20_fu_2512_p1;
wire   [15:0] zext_ln51_19_fu_2509_p1;
wire   [15:0] zext_ln51_18_fu_2506_p1;
wire   [15:0] zext_ln51_17_fu_2503_p1;
wire   [15:0] zext_ln51_16_fu_2500_p1;
wire   [15:0] zext_ln51_15_fu_2497_p1;
wire   [15:0] zext_ln51_14_fu_2494_p1;
wire   [15:0] zext_ln51_13_fu_2491_p1;
wire   [15:0] zext_ln51_12_fu_2488_p1;
wire   [15:0] zext_ln51_11_fu_2485_p1;
wire   [15:0] zext_ln51_10_fu_2482_p1;
wire   [15:0] zext_ln51_9_fu_2479_p1;
wire   [15:0] zext_ln51_8_fu_2476_p1;
wire   [15:0] zext_ln51_7_fu_2473_p1;
wire   [15:0] zext_ln51_6_fu_2470_p1;
wire   [15:0] zext_ln51_5_fu_2467_p1;
wire   [15:0] zext_ln51_4_fu_2464_p1;
wire   [15:0] zext_ln51_3_fu_2461_p1;
wire   [15:0] zext_ln51_2_fu_2458_p1;
wire   [15:0] zext_ln51_fu_2455_p1;
wire   [1022:0] or_ln57_s_fu_2644_p65;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer3_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (layer2_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        in_data_4_reg_2800 <= {{layer2_out_dout[31:16]}};
        in_data_5_reg_2810 <= {{layer2_out_dout[47:32]}};
        in_data_6_reg_2820 <= {{layer2_out_dout[63:48]}};
        in_data_reg_2780 <= in_data_fu_419_p1;
        tmp_10_reg_2940 <= {{layer2_out_dout[255:240]}};
        tmp_11_reg_2950 <= {{layer2_out_dout[271:256]}};
        tmp_12_reg_2960 <= {{layer2_out_dout[287:272]}};
        tmp_13_reg_2970 <= {{layer2_out_dout[303:288]}};
        tmp_14_reg_2980 <= {{layer2_out_dout[319:304]}};
        tmp_15_reg_2990 <= {{layer2_out_dout[335:320]}};
        tmp_16_reg_3000 <= {{layer2_out_dout[351:336]}};
        tmp_17_reg_3010 <= {{layer2_out_dout[367:352]}};
        tmp_18_reg_3020 <= {{layer2_out_dout[383:368]}};
        tmp_19_reg_3030 <= {{layer2_out_dout[399:384]}};
        tmp_1_reg_2880 <= {{layer2_out_dout[159:144]}};
        tmp_20_reg_3040 <= {{layer2_out_dout[415:400]}};
        tmp_21_reg_3050 <= {{layer2_out_dout[431:416]}};
        tmp_22_reg_3060 <= {{layer2_out_dout[447:432]}};
        tmp_23_reg_3070 <= {{layer2_out_dout[463:448]}};
        tmp_24_reg_3080 <= {{layer2_out_dout[479:464]}};
        tmp_25_reg_3090 <= {{layer2_out_dout[495:480]}};
        tmp_26_reg_3100 <= {{layer2_out_dout[511:496]}};
        tmp_27_reg_3110 <= {{layer2_out_dout[527:512]}};
        tmp_28_reg_3120 <= {{layer2_out_dout[543:528]}};
        tmp_29_reg_3130 <= {{layer2_out_dout[559:544]}};
        tmp_2_reg_2890 <= {{layer2_out_dout[175:160]}};
        tmp_30_reg_3140 <= {{layer2_out_dout[575:560]}};
        tmp_31_reg_3150 <= {{layer2_out_dout[591:576]}};
        tmp_32_reg_3160 <= {{layer2_out_dout[607:592]}};
        tmp_33_reg_3170 <= {{layer2_out_dout[623:608]}};
        tmp_34_reg_3180 <= {{layer2_out_dout[639:624]}};
        tmp_35_reg_3190 <= {{layer2_out_dout[655:640]}};
        tmp_36_reg_3200 <= {{layer2_out_dout[671:656]}};
        tmp_37_reg_3210 <= {{layer2_out_dout[687:672]}};
        tmp_38_reg_3220 <= {{layer2_out_dout[703:688]}};
        tmp_39_reg_3230 <= {{layer2_out_dout[719:704]}};
        tmp_3_reg_2900 <= {{layer2_out_dout[191:176]}};
        tmp_40_reg_3240 <= {{layer2_out_dout[735:720]}};
        tmp_41_reg_3250 <= {{layer2_out_dout[751:736]}};
        tmp_42_reg_3260 <= {{layer2_out_dout[767:752]}};
        tmp_43_reg_3270 <= {{layer2_out_dout[783:768]}};
        tmp_44_reg_3280 <= {{layer2_out_dout[799:784]}};
        tmp_45_reg_3290 <= {{layer2_out_dout[815:800]}};
        tmp_46_reg_3300 <= {{layer2_out_dout[831:816]}};
        tmp_47_reg_3310 <= {{layer2_out_dout[847:832]}};
        tmp_48_reg_3320 <= {{layer2_out_dout[863:848]}};
        tmp_49_reg_3330 <= {{layer2_out_dout[879:864]}};
        tmp_4_reg_2910 <= {{layer2_out_dout[207:192]}};
        tmp_50_reg_3340 <= {{layer2_out_dout[895:880]}};
        tmp_51_reg_3350 <= {{layer2_out_dout[911:896]}};
        tmp_52_reg_3360 <= {{layer2_out_dout[927:912]}};
        tmp_53_reg_3370 <= {{layer2_out_dout[943:928]}};
        tmp_54_reg_3380 <= {{layer2_out_dout[959:944]}};
        tmp_55_reg_3390 <= {{layer2_out_dout[975:960]}};
        tmp_56_reg_3400 <= {{layer2_out_dout[991:976]}};
        tmp_5_reg_2920 <= {{layer2_out_dout[223:208]}};
        tmp_6_reg_2930 <= {{layer2_out_dout[239:224]}};
        tmp_7_reg_2850 <= {{layer2_out_dout[111:96]}};
        tmp_8_reg_2860 <= {{layer2_out_dout[127:112]}};
        tmp_9_reg_2870 <= {{layer2_out_dout[143:128]}};
        tmp_reg_2830 <= {{layer2_out_dout[79:64]}};
        tmp_s_reg_2840 <= {{layer2_out_dout[95:80]}};
        trunc_ln44_10_reg_2875 <= {{layer2_out_dout[142:128]}};
        trunc_ln44_11_reg_2885 <= {{layer2_out_dout[158:144]}};
        trunc_ln44_12_reg_2895 <= {{layer2_out_dout[174:160]}};
        trunc_ln44_13_reg_2905 <= {{layer2_out_dout[190:176]}};
        trunc_ln44_14_reg_2915 <= {{layer2_out_dout[206:192]}};
        trunc_ln44_15_reg_2925 <= {{layer2_out_dout[222:208]}};
        trunc_ln44_16_reg_2935 <= {{layer2_out_dout[238:224]}};
        trunc_ln44_17_reg_2945 <= {{layer2_out_dout[254:240]}};
        trunc_ln44_18_reg_2955 <= {{layer2_out_dout[270:256]}};
        trunc_ln44_19_reg_2965 <= {{layer2_out_dout[286:272]}};
        trunc_ln44_1_reg_2785 <= trunc_ln44_1_fu_423_p1;
        trunc_ln44_20_reg_2975 <= {{layer2_out_dout[302:288]}};
        trunc_ln44_21_reg_2985 <= {{layer2_out_dout[318:304]}};
        trunc_ln44_22_reg_2995 <= {{layer2_out_dout[334:320]}};
        trunc_ln44_23_reg_3005 <= {{layer2_out_dout[350:336]}};
        trunc_ln44_24_reg_3015 <= {{layer2_out_dout[366:352]}};
        trunc_ln44_25_reg_3025 <= {{layer2_out_dout[382:368]}};
        trunc_ln44_26_reg_3035 <= {{layer2_out_dout[398:384]}};
        trunc_ln44_27_reg_3045 <= {{layer2_out_dout[414:400]}};
        trunc_ln44_28_reg_3055 <= {{layer2_out_dout[430:416]}};
        trunc_ln44_29_reg_3065 <= {{layer2_out_dout[446:432]}};
        trunc_ln44_2_reg_2790 <= {{layer2_out_dout[1007:992]}};
        trunc_ln44_30_reg_3075 <= {{layer2_out_dout[462:448]}};
        trunc_ln44_31_reg_3085 <= {{layer2_out_dout[478:464]}};
        trunc_ln44_32_reg_3095 <= {{layer2_out_dout[494:480]}};
        trunc_ln44_33_reg_3105 <= {{layer2_out_dout[510:496]}};
        trunc_ln44_34_reg_3115 <= {{layer2_out_dout[526:512]}};
        trunc_ln44_35_reg_3125 <= {{layer2_out_dout[542:528]}};
        trunc_ln44_36_reg_3135 <= {{layer2_out_dout[558:544]}};
        trunc_ln44_37_reg_3145 <= {{layer2_out_dout[574:560]}};
        trunc_ln44_38_reg_3155 <= {{layer2_out_dout[590:576]}};
        trunc_ln44_39_reg_3165 <= {{layer2_out_dout[606:592]}};
        trunc_ln44_3_reg_2795 <= {{layer2_out_dout[1023:1008]}};
        trunc_ln44_40_reg_3175 <= {{layer2_out_dout[622:608]}};
        trunc_ln44_41_reg_3185 <= {{layer2_out_dout[638:624]}};
        trunc_ln44_42_reg_3195 <= {{layer2_out_dout[654:640]}};
        trunc_ln44_43_reg_3205 <= {{layer2_out_dout[670:656]}};
        trunc_ln44_44_reg_3215 <= {{layer2_out_dout[686:672]}};
        trunc_ln44_45_reg_3225 <= {{layer2_out_dout[702:688]}};
        trunc_ln44_46_reg_3235 <= {{layer2_out_dout[718:704]}};
        trunc_ln44_47_reg_3245 <= {{layer2_out_dout[734:720]}};
        trunc_ln44_48_reg_3255 <= {{layer2_out_dout[750:736]}};
        trunc_ln44_49_reg_3265 <= {{layer2_out_dout[766:752]}};
        trunc_ln44_4_reg_2815 <= {{layer2_out_dout[46:32]}};
        trunc_ln44_50_reg_3275 <= {{layer2_out_dout[782:768]}};
        trunc_ln44_51_reg_3285 <= {{layer2_out_dout[798:784]}};
        trunc_ln44_52_reg_3295 <= {{layer2_out_dout[814:800]}};
        trunc_ln44_53_reg_3305 <= {{layer2_out_dout[830:816]}};
        trunc_ln44_54_reg_3315 <= {{layer2_out_dout[846:832]}};
        trunc_ln44_55_reg_3325 <= {{layer2_out_dout[862:848]}};
        trunc_ln44_56_reg_3335 <= {{layer2_out_dout[878:864]}};
        trunc_ln44_57_reg_3345 <= {{layer2_out_dout[894:880]}};
        trunc_ln44_58_reg_3355 <= {{layer2_out_dout[910:896]}};
        trunc_ln44_59_reg_3365 <= {{layer2_out_dout[926:912]}};
        trunc_ln44_5_reg_2825 <= {{layer2_out_dout[62:48]}};
        trunc_ln44_60_reg_3375 <= {{layer2_out_dout[942:928]}};
        trunc_ln44_61_reg_3385 <= {{layer2_out_dout[958:944]}};
        trunc_ln44_62_reg_3395 <= {{layer2_out_dout[974:960]}};
        trunc_ln44_63_reg_3405 <= {{layer2_out_dout[990:976]}};
        trunc_ln44_64_reg_3410 <= {{layer2_out_dout[1006:992]}};
        trunc_ln44_6_reg_2835 <= {{layer2_out_dout[78:64]}};
        trunc_ln44_7_reg_2845 <= {{layer2_out_dout[94:80]}};
        trunc_ln44_8_reg_2855 <= {{layer2_out_dout[110:96]}};
        trunc_ln44_9_reg_2865 <= {{layer2_out_dout[126:112]}};
        trunc_ln44_s_reg_2805 <= {{layer2_out_dout[30:16]}};
        trunc_ln_reg_3415 <= {{layer2_out_dout[1022:1008]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln51_10_reg_3470 <= select_ln51_10_fu_1812_p3;
        select_ln51_11_reg_3475 <= select_ln51_11_fu_1824_p3;
        select_ln51_12_reg_3480 <= select_ln51_12_fu_1836_p3;
        select_ln51_13_reg_3485 <= select_ln51_13_fu_1848_p3;
        select_ln51_14_reg_3490 <= select_ln51_14_fu_1860_p3;
        select_ln51_15_reg_3495 <= select_ln51_15_fu_1872_p3;
        select_ln51_16_reg_3500 <= select_ln51_16_fu_1884_p3;
        select_ln51_17_reg_3505 <= select_ln51_17_fu_1896_p3;
        select_ln51_18_reg_3510 <= select_ln51_18_fu_1908_p3;
        select_ln51_19_reg_3515 <= select_ln51_19_fu_1920_p3;
        select_ln51_1_reg_3425 <= select_ln51_1_fu_1704_p3;
        select_ln51_20_reg_3520 <= select_ln51_20_fu_1932_p3;
        select_ln51_21_reg_3525 <= select_ln51_21_fu_1944_p3;
        select_ln51_22_reg_3530 <= select_ln51_22_fu_1956_p3;
        select_ln51_23_reg_3535 <= select_ln51_23_fu_1968_p3;
        select_ln51_24_reg_3540 <= select_ln51_24_fu_1980_p3;
        select_ln51_25_reg_3545 <= select_ln51_25_fu_1992_p3;
        select_ln51_26_reg_3550 <= select_ln51_26_fu_2004_p3;
        select_ln51_27_reg_3555 <= select_ln51_27_fu_2016_p3;
        select_ln51_28_reg_3560 <= select_ln51_28_fu_2028_p3;
        select_ln51_29_reg_3565 <= select_ln51_29_fu_2040_p3;
        select_ln51_2_reg_3430 <= select_ln51_2_fu_1716_p3;
        select_ln51_30_reg_3570 <= select_ln51_30_fu_2052_p3;
        select_ln51_31_reg_3575 <= select_ln51_31_fu_2064_p3;
        select_ln51_32_reg_3580 <= select_ln51_32_fu_2076_p3;
        select_ln51_33_reg_3585 <= select_ln51_33_fu_2088_p3;
        select_ln51_34_reg_3590 <= select_ln51_34_fu_2100_p3;
        select_ln51_35_reg_3595 <= select_ln51_35_fu_2112_p3;
        select_ln51_36_reg_3600 <= select_ln51_36_fu_2124_p3;
        select_ln51_37_reg_3605 <= select_ln51_37_fu_2136_p3;
        select_ln51_38_reg_3610 <= select_ln51_38_fu_2148_p3;
        select_ln51_39_reg_3615 <= select_ln51_39_fu_2160_p3;
        select_ln51_3_reg_3435 <= select_ln51_3_fu_1728_p3;
        select_ln51_40_reg_3620 <= select_ln51_40_fu_2172_p3;
        select_ln51_41_reg_3625 <= select_ln51_41_fu_2184_p3;
        select_ln51_42_reg_3630 <= select_ln51_42_fu_2196_p3;
        select_ln51_43_reg_3635 <= select_ln51_43_fu_2208_p3;
        select_ln51_44_reg_3640 <= select_ln51_44_fu_2220_p3;
        select_ln51_45_reg_3645 <= select_ln51_45_fu_2232_p3;
        select_ln51_46_reg_3650 <= select_ln51_46_fu_2244_p3;
        select_ln51_47_reg_3655 <= select_ln51_47_fu_2256_p3;
        select_ln51_48_reg_3660 <= select_ln51_48_fu_2268_p3;
        select_ln51_49_reg_3665 <= select_ln51_49_fu_2280_p3;
        select_ln51_4_reg_3440 <= select_ln51_4_fu_1740_p3;
        select_ln51_50_reg_3670 <= select_ln51_50_fu_2292_p3;
        select_ln51_51_reg_3675 <= select_ln51_51_fu_2304_p3;
        select_ln51_52_reg_3680 <= select_ln51_52_fu_2316_p3;
        select_ln51_53_reg_3685 <= select_ln51_53_fu_2328_p3;
        select_ln51_54_reg_3690 <= select_ln51_54_fu_2340_p3;
        select_ln51_55_reg_3695 <= select_ln51_55_fu_2352_p3;
        select_ln51_56_reg_3700 <= select_ln51_56_fu_2364_p3;
        select_ln51_57_reg_3705 <= select_ln51_57_fu_2376_p3;
        select_ln51_58_reg_3710 <= select_ln51_58_fu_2388_p3;
        select_ln51_59_reg_3715 <= select_ln51_59_fu_2400_p3;
        select_ln51_5_reg_3445 <= select_ln51_5_fu_1752_p3;
        select_ln51_60_reg_3720 <= select_ln51_60_fu_2412_p3;
        select_ln51_61_reg_3725 <= select_ln51_61_fu_2424_p3;
        select_ln51_62_reg_3730 <= select_ln51_62_fu_2436_p3;
        select_ln51_63_reg_3735 <= select_ln51_63_fu_2448_p3;
        select_ln51_6_reg_3450 <= select_ln51_6_fu_1764_p3;
        select_ln51_7_reg_3455 <= select_ln51_7_fu_1776_p3;
        select_ln51_8_reg_3460 <= select_ln51_8_fu_1788_p3;
        select_ln51_9_reg_3465 <= select_ln51_9_fu_1800_p3;
        select_ln51_reg_3420 <= select_ln51_fu_1692_p3;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (layer2_out_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((layer3_out_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer3_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer3_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_blk_n = layer2_out_empty_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (layer2_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_read = 1'b1;
    end else begin
        layer2_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer3_out_blk_n = layer3_out_full_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer3_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer3_out_write = 1'b1;
    end else begin
        layer3_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (layer2_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((layer3_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer2_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_10_fu_1807_p2 = (($signed(tmp_2_reg_2890) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_1819_p2 = (($signed(tmp_3_reg_2900) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_1831_p2 = (($signed(tmp_4_reg_2910) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_1843_p2 = (($signed(tmp_5_reg_2920) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_1855_p2 = (($signed(tmp_6_reg_2930) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_15_fu_1867_p2 = (($signed(tmp_10_reg_2940) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_16_fu_1879_p2 = (($signed(tmp_11_reg_2950) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_17_fu_1891_p2 = (($signed(tmp_12_reg_2960) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_18_fu_1903_p2 = (($signed(tmp_13_reg_2970) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_19_fu_1915_p2 = (($signed(tmp_14_reg_2980) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_1699_p2 = (($signed(in_data_4_reg_2800) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_20_fu_1927_p2 = (($signed(tmp_15_reg_2990) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_21_fu_1939_p2 = (($signed(tmp_16_reg_3000) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_22_fu_1951_p2 = (($signed(tmp_17_reg_3010) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_23_fu_1963_p2 = (($signed(tmp_18_reg_3020) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_24_fu_1975_p2 = (($signed(tmp_19_reg_3030) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_25_fu_1987_p2 = (($signed(tmp_20_reg_3040) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_26_fu_1999_p2 = (($signed(tmp_21_reg_3050) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_27_fu_2011_p2 = (($signed(tmp_22_reg_3060) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_28_fu_2023_p2 = (($signed(tmp_23_reg_3070) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_29_fu_2035_p2 = (($signed(tmp_24_reg_3080) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_1711_p2 = (($signed(in_data_5_reg_2810) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_30_fu_2047_p2 = (($signed(tmp_25_reg_3090) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_31_fu_2059_p2 = (($signed(tmp_26_reg_3100) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_32_fu_2071_p2 = (($signed(tmp_27_reg_3110) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_33_fu_2083_p2 = (($signed(tmp_28_reg_3120) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_34_fu_2095_p2 = (($signed(tmp_29_reg_3130) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_35_fu_2107_p2 = (($signed(tmp_30_reg_3140) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_36_fu_2119_p2 = (($signed(tmp_31_reg_3150) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_37_fu_2131_p2 = (($signed(tmp_32_reg_3160) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_38_fu_2143_p2 = (($signed(tmp_33_reg_3170) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_39_fu_2155_p2 = (($signed(tmp_34_reg_3180) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_1723_p2 = (($signed(in_data_6_reg_2820) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_40_fu_2167_p2 = (($signed(tmp_35_reg_3190) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_41_fu_2179_p2 = (($signed(tmp_36_reg_3200) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_42_fu_2191_p2 = (($signed(tmp_37_reg_3210) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_43_fu_2203_p2 = (($signed(tmp_38_reg_3220) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_44_fu_2215_p2 = (($signed(tmp_39_reg_3230) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_45_fu_2227_p2 = (($signed(tmp_40_reg_3240) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_46_fu_2239_p2 = (($signed(tmp_41_reg_3250) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_47_fu_2251_p2 = (($signed(tmp_42_reg_3260) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_48_fu_2263_p2 = (($signed(tmp_43_reg_3270) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_49_fu_2275_p2 = (($signed(tmp_44_reg_3280) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_1735_p2 = (($signed(tmp_reg_2830) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_50_fu_2287_p2 = (($signed(tmp_45_reg_3290) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_51_fu_2299_p2 = (($signed(tmp_46_reg_3300) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_52_fu_2311_p2 = (($signed(tmp_47_reg_3310) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_53_fu_2323_p2 = (($signed(tmp_48_reg_3320) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_54_fu_2335_p2 = (($signed(tmp_49_reg_3330) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_55_fu_2347_p2 = (($signed(tmp_50_reg_3340) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_56_fu_2359_p2 = (($signed(tmp_51_reg_3350) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_57_fu_2371_p2 = (($signed(tmp_52_reg_3360) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_58_fu_2383_p2 = (($signed(tmp_53_reg_3370) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_59_fu_2395_p2 = (($signed(tmp_54_reg_3380) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_1747_p2 = (($signed(tmp_s_reg_2840) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_60_fu_2407_p2 = (($signed(tmp_55_reg_3390) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_61_fu_2419_p2 = (($signed(tmp_56_reg_3400) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_62_fu_2431_p2 = (($signed(trunc_ln44_2_reg_2790) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_63_fu_2443_p2 = (($signed(trunc_ln44_3_reg_2795) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_1759_p2 = (($signed(tmp_7_reg_2850) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_7_fu_1771_p2 = (($signed(tmp_8_reg_2860) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_1783_p2 = (($signed(tmp_9_reg_2870) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_1795_p2 = (($signed(tmp_1_reg_2880) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_1687_p2 = (($signed(in_data_reg_2780) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign in_data_fu_419_p1 = layer2_out_dout[15:0];

assign layer3_out_din = or_ln57_s_fu_2644_p65;

assign or_ln57_s_fu_2644_p65 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_63_reg_3735}, {zext_ln51_63_fu_2641_p1}}, {zext_ln51_62_fu_2638_p1}}, {zext_ln51_61_fu_2635_p1}}, {zext_ln51_60_fu_2632_p1}}, {zext_ln51_59_fu_2629_p1}}, {zext_ln51_58_fu_2626_p1}}, {zext_ln51_57_fu_2623_p1}}, {zext_ln51_56_fu_2620_p1}}, {zext_ln51_55_fu_2617_p1}}, {zext_ln51_54_fu_2614_p1}}, {zext_ln51_53_fu_2611_p1}}, {zext_ln51_52_fu_2608_p1}}, {zext_ln51_51_fu_2605_p1}}, {zext_ln51_50_fu_2602_p1}}, {zext_ln51_49_fu_2599_p1}}, {zext_ln51_48_fu_2596_p1}}, {zext_ln51_47_fu_2593_p1}}, {zext_ln51_46_fu_2590_p1}}, {zext_ln51_45_fu_2587_p1}}, {zext_ln51_44_fu_2584_p1}}, {zext_ln51_43_fu_2581_p1}}, {zext_ln51_42_fu_2578_p1}}, {zext_ln51_41_fu_2575_p1}}, {zext_ln51_40_fu_2572_p1}}, {zext_ln51_39_fu_2569_p1}}, {zext_ln51_38_fu_2566_p1}}, {zext_ln51_37_fu_2563_p1}}, {zext_ln51_36_fu_2560_p1}}, {zext_ln51_35_fu_2557_p1}}, {zext_ln51_34_fu_2554_p1}}, {zext_ln51_33_fu_2551_p1}}, {zext_ln51_32_fu_2548_p1}}, {zext_ln51_31_fu_2545_p1}}, {zext_ln51_30_fu_2542_p1}}, 
    {zext_ln51_29_fu_2539_p1}}, {zext_ln51_28_fu_2536_p1}}, {zext_ln51_27_fu_2533_p1}}, {zext_ln51_26_fu_2530_p1}}, {zext_ln51_25_fu_2527_p1}}, {zext_ln51_24_fu_2524_p1}}, {zext_ln51_23_fu_2521_p1}}, {zext_ln51_22_fu_2518_p1}}, {zext_ln51_21_fu_2515_p1}}, {zext_ln51_20_fu_2512_p1}}, {zext_ln51_19_fu_2509_p1}}, {zext_ln51_18_fu_2506_p1}}, {zext_ln51_17_fu_2503_p1}}, {zext_ln51_16_fu_2500_p1}}, {zext_ln51_15_fu_2497_p1}}, {zext_ln51_14_fu_2494_p1}}, {zext_ln51_13_fu_2491_p1}}, {zext_ln51_12_fu_2488_p1}}, {zext_ln51_11_fu_2485_p1}}, {zext_ln51_10_fu_2482_p1}}, {zext_ln51_9_fu_2479_p1}}, {zext_ln51_8_fu_2476_p1}}, {zext_ln51_7_fu_2473_p1}}, {zext_ln51_6_fu_2470_p1}}, {zext_ln51_5_fu_2467_p1}}, {zext_ln51_4_fu_2464_p1}}, {zext_ln51_3_fu_2461_p1}}, {zext_ln51_2_fu_2458_p1}}, {zext_ln51_fu_2455_p1}};

assign select_ln51_10_fu_1812_p3 = ((icmp_ln51_10_fu_1807_p2[0:0] == 1'b1) ? trunc_ln44_12_reg_2895 : 15'd0);

assign select_ln51_11_fu_1824_p3 = ((icmp_ln51_11_fu_1819_p2[0:0] == 1'b1) ? trunc_ln44_13_reg_2905 : 15'd0);

assign select_ln51_12_fu_1836_p3 = ((icmp_ln51_12_fu_1831_p2[0:0] == 1'b1) ? trunc_ln44_14_reg_2915 : 15'd0);

assign select_ln51_13_fu_1848_p3 = ((icmp_ln51_13_fu_1843_p2[0:0] == 1'b1) ? trunc_ln44_15_reg_2925 : 15'd0);

assign select_ln51_14_fu_1860_p3 = ((icmp_ln51_14_fu_1855_p2[0:0] == 1'b1) ? trunc_ln44_16_reg_2935 : 15'd0);

assign select_ln51_15_fu_1872_p3 = ((icmp_ln51_15_fu_1867_p2[0:0] == 1'b1) ? trunc_ln44_17_reg_2945 : 15'd0);

assign select_ln51_16_fu_1884_p3 = ((icmp_ln51_16_fu_1879_p2[0:0] == 1'b1) ? trunc_ln44_18_reg_2955 : 15'd0);

assign select_ln51_17_fu_1896_p3 = ((icmp_ln51_17_fu_1891_p2[0:0] == 1'b1) ? trunc_ln44_19_reg_2965 : 15'd0);

assign select_ln51_18_fu_1908_p3 = ((icmp_ln51_18_fu_1903_p2[0:0] == 1'b1) ? trunc_ln44_20_reg_2975 : 15'd0);

assign select_ln51_19_fu_1920_p3 = ((icmp_ln51_19_fu_1915_p2[0:0] == 1'b1) ? trunc_ln44_21_reg_2985 : 15'd0);

assign select_ln51_1_fu_1704_p3 = ((icmp_ln51_1_fu_1699_p2[0:0] == 1'b1) ? trunc_ln44_s_reg_2805 : 15'd0);

assign select_ln51_20_fu_1932_p3 = ((icmp_ln51_20_fu_1927_p2[0:0] == 1'b1) ? trunc_ln44_22_reg_2995 : 15'd0);

assign select_ln51_21_fu_1944_p3 = ((icmp_ln51_21_fu_1939_p2[0:0] == 1'b1) ? trunc_ln44_23_reg_3005 : 15'd0);

assign select_ln51_22_fu_1956_p3 = ((icmp_ln51_22_fu_1951_p2[0:0] == 1'b1) ? trunc_ln44_24_reg_3015 : 15'd0);

assign select_ln51_23_fu_1968_p3 = ((icmp_ln51_23_fu_1963_p2[0:0] == 1'b1) ? trunc_ln44_25_reg_3025 : 15'd0);

assign select_ln51_24_fu_1980_p3 = ((icmp_ln51_24_fu_1975_p2[0:0] == 1'b1) ? trunc_ln44_26_reg_3035 : 15'd0);

assign select_ln51_25_fu_1992_p3 = ((icmp_ln51_25_fu_1987_p2[0:0] == 1'b1) ? trunc_ln44_27_reg_3045 : 15'd0);

assign select_ln51_26_fu_2004_p3 = ((icmp_ln51_26_fu_1999_p2[0:0] == 1'b1) ? trunc_ln44_28_reg_3055 : 15'd0);

assign select_ln51_27_fu_2016_p3 = ((icmp_ln51_27_fu_2011_p2[0:0] == 1'b1) ? trunc_ln44_29_reg_3065 : 15'd0);

assign select_ln51_28_fu_2028_p3 = ((icmp_ln51_28_fu_2023_p2[0:0] == 1'b1) ? trunc_ln44_30_reg_3075 : 15'd0);

assign select_ln51_29_fu_2040_p3 = ((icmp_ln51_29_fu_2035_p2[0:0] == 1'b1) ? trunc_ln44_31_reg_3085 : 15'd0);

assign select_ln51_2_fu_1716_p3 = ((icmp_ln51_2_fu_1711_p2[0:0] == 1'b1) ? trunc_ln44_4_reg_2815 : 15'd0);

assign select_ln51_30_fu_2052_p3 = ((icmp_ln51_30_fu_2047_p2[0:0] == 1'b1) ? trunc_ln44_32_reg_3095 : 15'd0);

assign select_ln51_31_fu_2064_p3 = ((icmp_ln51_31_fu_2059_p2[0:0] == 1'b1) ? trunc_ln44_33_reg_3105 : 15'd0);

assign select_ln51_32_fu_2076_p3 = ((icmp_ln51_32_fu_2071_p2[0:0] == 1'b1) ? trunc_ln44_34_reg_3115 : 15'd0);

assign select_ln51_33_fu_2088_p3 = ((icmp_ln51_33_fu_2083_p2[0:0] == 1'b1) ? trunc_ln44_35_reg_3125 : 15'd0);

assign select_ln51_34_fu_2100_p3 = ((icmp_ln51_34_fu_2095_p2[0:0] == 1'b1) ? trunc_ln44_36_reg_3135 : 15'd0);

assign select_ln51_35_fu_2112_p3 = ((icmp_ln51_35_fu_2107_p2[0:0] == 1'b1) ? trunc_ln44_37_reg_3145 : 15'd0);

assign select_ln51_36_fu_2124_p3 = ((icmp_ln51_36_fu_2119_p2[0:0] == 1'b1) ? trunc_ln44_38_reg_3155 : 15'd0);

assign select_ln51_37_fu_2136_p3 = ((icmp_ln51_37_fu_2131_p2[0:0] == 1'b1) ? trunc_ln44_39_reg_3165 : 15'd0);

assign select_ln51_38_fu_2148_p3 = ((icmp_ln51_38_fu_2143_p2[0:0] == 1'b1) ? trunc_ln44_40_reg_3175 : 15'd0);

assign select_ln51_39_fu_2160_p3 = ((icmp_ln51_39_fu_2155_p2[0:0] == 1'b1) ? trunc_ln44_41_reg_3185 : 15'd0);

assign select_ln51_3_fu_1728_p3 = ((icmp_ln51_3_fu_1723_p2[0:0] == 1'b1) ? trunc_ln44_5_reg_2825 : 15'd0);

assign select_ln51_40_fu_2172_p3 = ((icmp_ln51_40_fu_2167_p2[0:0] == 1'b1) ? trunc_ln44_42_reg_3195 : 15'd0);

assign select_ln51_41_fu_2184_p3 = ((icmp_ln51_41_fu_2179_p2[0:0] == 1'b1) ? trunc_ln44_43_reg_3205 : 15'd0);

assign select_ln51_42_fu_2196_p3 = ((icmp_ln51_42_fu_2191_p2[0:0] == 1'b1) ? trunc_ln44_44_reg_3215 : 15'd0);

assign select_ln51_43_fu_2208_p3 = ((icmp_ln51_43_fu_2203_p2[0:0] == 1'b1) ? trunc_ln44_45_reg_3225 : 15'd0);

assign select_ln51_44_fu_2220_p3 = ((icmp_ln51_44_fu_2215_p2[0:0] == 1'b1) ? trunc_ln44_46_reg_3235 : 15'd0);

assign select_ln51_45_fu_2232_p3 = ((icmp_ln51_45_fu_2227_p2[0:0] == 1'b1) ? trunc_ln44_47_reg_3245 : 15'd0);

assign select_ln51_46_fu_2244_p3 = ((icmp_ln51_46_fu_2239_p2[0:0] == 1'b1) ? trunc_ln44_48_reg_3255 : 15'd0);

assign select_ln51_47_fu_2256_p3 = ((icmp_ln51_47_fu_2251_p2[0:0] == 1'b1) ? trunc_ln44_49_reg_3265 : 15'd0);

assign select_ln51_48_fu_2268_p3 = ((icmp_ln51_48_fu_2263_p2[0:0] == 1'b1) ? trunc_ln44_50_reg_3275 : 15'd0);

assign select_ln51_49_fu_2280_p3 = ((icmp_ln51_49_fu_2275_p2[0:0] == 1'b1) ? trunc_ln44_51_reg_3285 : 15'd0);

assign select_ln51_4_fu_1740_p3 = ((icmp_ln51_4_fu_1735_p2[0:0] == 1'b1) ? trunc_ln44_6_reg_2835 : 15'd0);

assign select_ln51_50_fu_2292_p3 = ((icmp_ln51_50_fu_2287_p2[0:0] == 1'b1) ? trunc_ln44_52_reg_3295 : 15'd0);

assign select_ln51_51_fu_2304_p3 = ((icmp_ln51_51_fu_2299_p2[0:0] == 1'b1) ? trunc_ln44_53_reg_3305 : 15'd0);

assign select_ln51_52_fu_2316_p3 = ((icmp_ln51_52_fu_2311_p2[0:0] == 1'b1) ? trunc_ln44_54_reg_3315 : 15'd0);

assign select_ln51_53_fu_2328_p3 = ((icmp_ln51_53_fu_2323_p2[0:0] == 1'b1) ? trunc_ln44_55_reg_3325 : 15'd0);

assign select_ln51_54_fu_2340_p3 = ((icmp_ln51_54_fu_2335_p2[0:0] == 1'b1) ? trunc_ln44_56_reg_3335 : 15'd0);

assign select_ln51_55_fu_2352_p3 = ((icmp_ln51_55_fu_2347_p2[0:0] == 1'b1) ? trunc_ln44_57_reg_3345 : 15'd0);

assign select_ln51_56_fu_2364_p3 = ((icmp_ln51_56_fu_2359_p2[0:0] == 1'b1) ? trunc_ln44_58_reg_3355 : 15'd0);

assign select_ln51_57_fu_2376_p3 = ((icmp_ln51_57_fu_2371_p2[0:0] == 1'b1) ? trunc_ln44_59_reg_3365 : 15'd0);

assign select_ln51_58_fu_2388_p3 = ((icmp_ln51_58_fu_2383_p2[0:0] == 1'b1) ? trunc_ln44_60_reg_3375 : 15'd0);

assign select_ln51_59_fu_2400_p3 = ((icmp_ln51_59_fu_2395_p2[0:0] == 1'b1) ? trunc_ln44_61_reg_3385 : 15'd0);

assign select_ln51_5_fu_1752_p3 = ((icmp_ln51_5_fu_1747_p2[0:0] == 1'b1) ? trunc_ln44_7_reg_2845 : 15'd0);

assign select_ln51_60_fu_2412_p3 = ((icmp_ln51_60_fu_2407_p2[0:0] == 1'b1) ? trunc_ln44_62_reg_3395 : 15'd0);

assign select_ln51_61_fu_2424_p3 = ((icmp_ln51_61_fu_2419_p2[0:0] == 1'b1) ? trunc_ln44_63_reg_3405 : 15'd0);

assign select_ln51_62_fu_2436_p3 = ((icmp_ln51_62_fu_2431_p2[0:0] == 1'b1) ? trunc_ln44_64_reg_3410 : 15'd0);

assign select_ln51_63_fu_2448_p3 = ((icmp_ln51_63_fu_2443_p2[0:0] == 1'b1) ? trunc_ln_reg_3415 : 15'd0);

assign select_ln51_6_fu_1764_p3 = ((icmp_ln51_6_fu_1759_p2[0:0] == 1'b1) ? trunc_ln44_8_reg_2855 : 15'd0);

assign select_ln51_7_fu_1776_p3 = ((icmp_ln51_7_fu_1771_p2[0:0] == 1'b1) ? trunc_ln44_9_reg_2865 : 15'd0);

assign select_ln51_8_fu_1788_p3 = ((icmp_ln51_8_fu_1783_p2[0:0] == 1'b1) ? trunc_ln44_10_reg_2875 : 15'd0);

assign select_ln51_9_fu_1800_p3 = ((icmp_ln51_9_fu_1795_p2[0:0] == 1'b1) ? trunc_ln44_11_reg_2885 : 15'd0);

assign select_ln51_fu_1692_p3 = ((icmp_ln51_fu_1687_p2[0:0] == 1'b1) ? trunc_ln44_1_reg_2785 : 15'd0);

assign start_out = real_start;

assign trunc_ln44_1_fu_423_p1 = layer2_out_dout[14:0];

assign zext_ln51_10_fu_2482_p1 = select_ln51_9_reg_3465;

assign zext_ln51_11_fu_2485_p1 = select_ln51_10_reg_3470;

assign zext_ln51_12_fu_2488_p1 = select_ln51_11_reg_3475;

assign zext_ln51_13_fu_2491_p1 = select_ln51_12_reg_3480;

assign zext_ln51_14_fu_2494_p1 = select_ln51_13_reg_3485;

assign zext_ln51_15_fu_2497_p1 = select_ln51_14_reg_3490;

assign zext_ln51_16_fu_2500_p1 = select_ln51_15_reg_3495;

assign zext_ln51_17_fu_2503_p1 = select_ln51_16_reg_3500;

assign zext_ln51_18_fu_2506_p1 = select_ln51_17_reg_3505;

assign zext_ln51_19_fu_2509_p1 = select_ln51_18_reg_3510;

assign zext_ln51_20_fu_2512_p1 = select_ln51_19_reg_3515;

assign zext_ln51_21_fu_2515_p1 = select_ln51_20_reg_3520;

assign zext_ln51_22_fu_2518_p1 = select_ln51_21_reg_3525;

assign zext_ln51_23_fu_2521_p1 = select_ln51_22_reg_3530;

assign zext_ln51_24_fu_2524_p1 = select_ln51_23_reg_3535;

assign zext_ln51_25_fu_2527_p1 = select_ln51_24_reg_3540;

assign zext_ln51_26_fu_2530_p1 = select_ln51_25_reg_3545;

assign zext_ln51_27_fu_2533_p1 = select_ln51_26_reg_3550;

assign zext_ln51_28_fu_2536_p1 = select_ln51_27_reg_3555;

assign zext_ln51_29_fu_2539_p1 = select_ln51_28_reg_3560;

assign zext_ln51_2_fu_2458_p1 = select_ln51_1_reg_3425;

assign zext_ln51_30_fu_2542_p1 = select_ln51_29_reg_3565;

assign zext_ln51_31_fu_2545_p1 = select_ln51_30_reg_3570;

assign zext_ln51_32_fu_2548_p1 = select_ln51_31_reg_3575;

assign zext_ln51_33_fu_2551_p1 = select_ln51_32_reg_3580;

assign zext_ln51_34_fu_2554_p1 = select_ln51_33_reg_3585;

assign zext_ln51_35_fu_2557_p1 = select_ln51_34_reg_3590;

assign zext_ln51_36_fu_2560_p1 = select_ln51_35_reg_3595;

assign zext_ln51_37_fu_2563_p1 = select_ln51_36_reg_3600;

assign zext_ln51_38_fu_2566_p1 = select_ln51_37_reg_3605;

assign zext_ln51_39_fu_2569_p1 = select_ln51_38_reg_3610;

assign zext_ln51_3_fu_2461_p1 = select_ln51_2_reg_3430;

assign zext_ln51_40_fu_2572_p1 = select_ln51_39_reg_3615;

assign zext_ln51_41_fu_2575_p1 = select_ln51_40_reg_3620;

assign zext_ln51_42_fu_2578_p1 = select_ln51_41_reg_3625;

assign zext_ln51_43_fu_2581_p1 = select_ln51_42_reg_3630;

assign zext_ln51_44_fu_2584_p1 = select_ln51_43_reg_3635;

assign zext_ln51_45_fu_2587_p1 = select_ln51_44_reg_3640;

assign zext_ln51_46_fu_2590_p1 = select_ln51_45_reg_3645;

assign zext_ln51_47_fu_2593_p1 = select_ln51_46_reg_3650;

assign zext_ln51_48_fu_2596_p1 = select_ln51_47_reg_3655;

assign zext_ln51_49_fu_2599_p1 = select_ln51_48_reg_3660;

assign zext_ln51_4_fu_2464_p1 = select_ln51_3_reg_3435;

assign zext_ln51_50_fu_2602_p1 = select_ln51_49_reg_3665;

assign zext_ln51_51_fu_2605_p1 = select_ln51_50_reg_3670;

assign zext_ln51_52_fu_2608_p1 = select_ln51_51_reg_3675;

assign zext_ln51_53_fu_2611_p1 = select_ln51_52_reg_3680;

assign zext_ln51_54_fu_2614_p1 = select_ln51_53_reg_3685;

assign zext_ln51_55_fu_2617_p1 = select_ln51_54_reg_3690;

assign zext_ln51_56_fu_2620_p1 = select_ln51_55_reg_3695;

assign zext_ln51_57_fu_2623_p1 = select_ln51_56_reg_3700;

assign zext_ln51_58_fu_2626_p1 = select_ln51_57_reg_3705;

assign zext_ln51_59_fu_2629_p1 = select_ln51_58_reg_3710;

assign zext_ln51_5_fu_2467_p1 = select_ln51_4_reg_3440;

assign zext_ln51_60_fu_2632_p1 = select_ln51_59_reg_3715;

assign zext_ln51_61_fu_2635_p1 = select_ln51_60_reg_3720;

assign zext_ln51_62_fu_2638_p1 = select_ln51_61_reg_3725;

assign zext_ln51_63_fu_2641_p1 = select_ln51_62_reg_3730;

assign zext_ln51_6_fu_2470_p1 = select_ln51_5_reg_3445;

assign zext_ln51_7_fu_2473_p1 = select_ln51_6_reg_3450;

assign zext_ln51_8_fu_2476_p1 = select_ln51_7_reg_3455;

assign zext_ln51_9_fu_2479_p1 = select_ln51_8_reg_3460;

assign zext_ln51_fu_2455_p1 = select_ln51_reg_3420;

endmodule //myproject_relu_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_64u_relu_config3_s
