// ==============================================================
// Generated by Vitis HLS v2025.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
input  [15:0] data_16_val;
input  [15:0] data_17_val;
input  [15:0] data_18_val;
input  [15:0] data_19_val;
input  [15:0] data_20_val;
input  [15:0] data_21_val;
input  [15:0] data_22_val;
input  [15:0] data_23_val;
input  [15:0] data_24_val;
input  [15:0] data_25_val;
input  [15:0] data_26_val;
input  [15:0] data_27_val;
input  [15:0] data_28_val;
input  [15:0] data_29_val;
input  [15:0] data_30_val;
input  [15:0] data_31_val;
output  [15:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [15:0] add_ln58_fu_4981_p2;
reg   [15:0] add_ln58_reg_5162;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] add_ln58_1_fu_4987_p2;
reg   [15:0] add_ln58_1_reg_5167;
wire   [15:0] add_ln58_5_fu_5005_p2;
reg   [15:0] add_ln58_5_reg_5172;
wire   [15:0] add_ln58_7_fu_5011_p2;
reg   [15:0] add_ln58_7_reg_5177;
wire   [15:0] add_ln58_8_fu_5017_p2;
reg   [15:0] add_ln58_8_reg_5182;
wire   [15:0] add_ln58_12_fu_5035_p2;
reg   [15:0] add_ln58_12_reg_5187;
wire   [15:0] add_ln58_17_fu_5053_p2;
reg   [15:0] add_ln58_17_reg_5192;
wire   [15:0] add_ln58_20_fu_5071_p2;
reg   [15:0] add_ln58_20_reg_5197;
wire   [15:0] add_ln58_22_fu_5077_p2;
reg   [15:0] add_ln58_22_reg_5202;
wire   [15:0] add_ln58_23_fu_5083_p2;
reg   [15:0] add_ln58_23_reg_5207;
wire   [15:0] add_ln58_28_fu_5107_p2;
reg   [15:0] add_ln58_28_reg_5212;
wire   [11:0] mul_ln42_10_fu_364_p1;
wire    ap_block_pp0_stage0;
wire  signed [11:0] mul_ln42_9_fu_365_p1;
wire  signed [11:0] mul_ln42_6_fu_366_p1;
wire  signed [10:0] mul_ln42_16_fu_367_p1;
wire   [9:0] mul_ln73_1_fu_368_p1;
wire  signed [9:0] mul_ln73_9_fu_369_p1;
wire  signed [10:0] mul_ln42_11_fu_370_p1;
wire  signed [9:0] mul_ln73_6_fu_371_p1;
wire  signed [9:0] mul_ln73_4_fu_372_p1;
wire   [10:0] mul_ln42_7_fu_373_p1;
wire  signed [10:0] mul_ln42_1_fu_374_p1;
wire   [10:0] mul_ln42_14_fu_375_p1;
wire  signed [11:0] mul_ln42_fu_376_p1;
wire  signed [8:0] mul_ln73_fu_377_p1;
wire   [9:0] mul_ln73_5_fu_378_p1;
wire  signed [8:0] mul_ln73_11_fu_379_p1;
wire   [11:0] mul_ln42_4_fu_380_p1;
wire   [10:0] mul_ln42_3_fu_381_p1;
wire  signed [9:0] mul_ln73_7_fu_382_p1;
wire   [9:0] mul_ln73_2_fu_383_p1;
wire  signed [9:0] mul_ln73_8_fu_384_p1;
wire   [10:0] mul_ln42_17_fu_385_p1;
wire   [11:0] mul_ln42_8_fu_386_p1;
wire  signed [10:0] mul_ln42_12_fu_387_p1;
wire  signed [10:0] mul_ln42_5_fu_388_p1;
wire   [9:0] mul_ln73_10_fu_390_p1;
wire   [9:0] mul_ln73_3_fu_391_p1;
wire  signed [10:0] mul_ln42_2_fu_392_p1;
wire   [10:0] mul_ln42_15_fu_393_p1;
wire  signed [10:0] mul_ln42_13_fu_394_p1;
wire   [25:0] mul_ln42_fu_376_p2;
wire   [25:0] mul_ln42_1_fu_374_p2;
wire   [25:0] mul_ln42_2_fu_392_p2;
wire   [24:0] mul_ln73_fu_377_p2;
wire   [14:0] trunc_ln42_3_fu_4497_p4;
wire   [25:0] mul_ln73_1_fu_368_p2;
wire   [25:0] mul_ln42_3_fu_381_p2;
wire   [25:0] mul_ln42_4_fu_380_p2;
wire   [25:0] mul_ln42_5_fu_388_p2;
wire   [23:0] tmp_fu_4571_p3;
wire   [20:0] tmp_5_fu_4583_p3;
wire  signed [24:0] sext_ln73_1_fu_4591_p1;
wire  signed [24:0] sext_ln73_fu_4579_p1;
wire   [24:0] sub_ln73_fu_4595_p2;
wire   [14:0] trunc_ln42_8_fu_4601_p4;
wire   [25:0] mul_ln42_6_fu_366_p2;
wire   [25:0] mul_ln42_7_fu_373_p2;
wire   [25:0] mul_ln42_8_fu_386_p2;
wire   [25:0] mul_ln42_9_fu_365_p2;
wire   [25:0] mul_ln42_10_fu_364_p2;
wire   [25:0] mul_ln42_11_fu_370_p2;
wire   [25:0] mul_ln73_2_fu_383_p2;
wire   [25:0] mul_ln73_3_fu_391_p2;
wire   [25:0] mul_ln42_12_fu_387_p2;
wire   [25:0] mul_ln42_13_fu_394_p2;
wire   [25:0] mul_ln73_4_fu_372_p2;
wire   [25:0] mul_ln73_5_fu_378_p2;
wire   [25:0] mul_ln73_6_fu_371_p2;
wire   [22:0] tmp_6_fu_4810_p3;
wire  signed [23:0] sext_ln73_2_fu_4818_p1;
wire   [23:0] sub_ln73_1_fu_4822_p2;
wire   [13:0] trunc_ln42_21_fu_4828_p4;
wire   [25:0] mul_ln73_7_fu_382_p2;
wire   [25:0] mul_ln73_8_fu_384_p2;
wire   [25:0] mul_ln73_9_fu_369_p2;
wire   [25:0] mul_ln42_14_fu_375_p2;
wire   [25:0] mul_ln73_10_fu_390_p2;
wire   [25:0] mul_ln42_15_fu_393_p2;
wire   [25:0] mul_ln42_16_fu_367_p2;
wire   [24:0] mul_ln73_11_fu_379_p2;
wire   [14:0] trunc_ln42_29_fu_4952_p4;
wire   [25:0] mul_ln42_17_fu_385_p2;
wire   [15:0] trunc_ln_fu_4452_p4;
wire   [15:0] trunc_ln42_1_fu_4467_p4;
wire   [15:0] trunc_ln42_2_fu_4482_p4;
wire  signed [15:0] sext_ln42_3_fu_4507_p1;
wire   [15:0] trunc_ln42_4_fu_4516_p4;
wire   [15:0] trunc_ln42_5_fu_4531_p4;
wire   [15:0] trunc_ln42_6_fu_4546_p4;
wire   [15:0] trunc_ln42_7_fu_4561_p4;
wire   [15:0] add_ln58_4_fu_4999_p2;
wire   [15:0] add_ln58_3_fu_4993_p2;
wire  signed [15:0] sext_ln42_7_fu_4611_p1;
wire   [15:0] trunc_ln42_9_fu_4620_p4;
wire   [15:0] trunc_ln42_s_fu_4635_p4;
wire   [15:0] trunc_ln42_10_fu_4650_p4;
wire   [15:0] trunc_ln42_11_fu_4665_p4;
wire   [15:0] trunc_ln42_12_fu_4680_p4;
wire   [15:0] trunc_ln42_13_fu_4695_p4;
wire   [15:0] trunc_ln42_14_fu_4710_p4;
wire   [15:0] add_ln58_11_fu_5029_p2;
wire   [15:0] add_ln58_10_fu_5023_p2;
wire   [15:0] trunc_ln42_15_fu_4725_p4;
wire   [15:0] trunc_ln42_16_fu_4740_p4;
wire   [15:0] trunc_ln42_17_fu_4755_p4;
wire   [15:0] trunc_ln42_18_fu_4770_p4;
wire   [15:0] add_ln58_16_fu_5047_p2;
wire   [15:0] add_ln58_15_fu_5041_p2;
wire   [15:0] trunc_ln42_19_fu_4785_p4;
wire   [15:0] trunc_ln42_20_fu_4800_p4;
wire  signed [15:0] sext_ln42_16_fu_4838_p1;
wire   [15:0] trunc_ln42_22_fu_4847_p4;
wire   [15:0] add_ln58_19_fu_5065_p2;
wire   [15:0] add_ln58_18_fu_5059_p2;
wire   [15:0] trunc_ln42_23_fu_4862_p4;
wire   [15:0] trunc_ln42_24_fu_4877_p4;
wire   [15:0] trunc_ln42_25_fu_4892_p4;
wire   [15:0] trunc_ln42_26_fu_4907_p4;
wire   [15:0] trunc_ln42_27_fu_4922_p4;
wire   [15:0] trunc_ln42_28_fu_4937_p4;
wire   [15:0] trunc_ln42_30_fu_4971_p4;
wire   [15:0] add_ln58_26_fu_5095_p2;
wire  signed [15:0] sext_ln42_20_fu_4962_p1;
wire   [15:0] add_ln58_27_fu_5101_p2;
wire   [15:0] add_ln58_25_fu_5089_p2;
wire   [15:0] add_ln58_2_fu_5113_p2;
wire   [15:0] add_ln58_9_fu_5122_p2;
wire   [15:0] add_ln58_13_fu_5126_p2;
wire   [15:0] add_ln58_6_fu_5117_p2;
wire   [15:0] add_ln58_24_fu_5141_p2;
wire   [15:0] add_ln58_29_fu_5145_p2;
wire   [15:0] add_ln58_21_fu_5137_p2;
wire   [15:0] add_ln58_30_fu_5150_p2;
wire   [15:0] add_ln58_14_fu_5131_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_init_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

myproject_mul_16s_12ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_1_1_U324(
    .din0(data_13_val),
    .din1(mul_ln42_10_fu_364_p1),
    .dout(mul_ln42_10_fu_364_p2)
);

myproject_mul_16s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_1_1_U325(
    .din0(data_12_val),
    .din1(mul_ln42_9_fu_365_p1),
    .dout(mul_ln42_9_fu_365_p2)
);

myproject_mul_16s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_1_1_U326(
    .din0(data_9_val),
    .din1(mul_ln42_6_fu_366_p1),
    .dout(mul_ln42_6_fu_366_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U327(
    .din0(data_29_val),
    .din1(mul_ln42_16_fu_367_p1),
    .dout(mul_ln42_16_fu_367_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U328(
    .din0(data_4_val),
    .din1(mul_ln73_1_fu_368_p1),
    .dout(mul_ln73_1_fu_368_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U329(
    .din0(data_25_val),
    .din1(mul_ln73_9_fu_369_p1),
    .dout(mul_ln73_9_fu_369_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U330(
    .din0(data_14_val),
    .din1(mul_ln42_11_fu_370_p1),
    .dout(mul_ln42_11_fu_370_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U331(
    .din0(data_21_val),
    .din1(mul_ln73_6_fu_371_p1),
    .dout(mul_ln73_6_fu_371_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U332(
    .din0(data_19_val),
    .din1(mul_ln73_4_fu_372_p1),
    .dout(mul_ln73_4_fu_372_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U333(
    .din0(data_10_val),
    .din1(mul_ln42_7_fu_373_p1),
    .dout(mul_ln42_7_fu_373_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U334(
    .din0(data_1_val),
    .din1(mul_ln42_1_fu_374_p1),
    .dout(mul_ln42_1_fu_374_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U335(
    .din0(data_26_val),
    .din1(mul_ln42_14_fu_375_p1),
    .dout(mul_ln42_14_fu_375_p2)
);

myproject_mul_16s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_1_1_U336(
    .din0(data_0_val),
    .din1(mul_ln42_fu_376_p1),
    .dout(mul_ln42_fu_376_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U337(
    .din0(data_3_val),
    .din1(mul_ln73_fu_377_p1),
    .dout(mul_ln73_fu_377_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U338(
    .din0(data_20_val),
    .din1(mul_ln73_5_fu_378_p1),
    .dout(mul_ln73_5_fu_378_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U339(
    .din0(data_30_val),
    .din1(mul_ln73_11_fu_379_p1),
    .dout(mul_ln73_11_fu_379_p2)
);

myproject_mul_16s_12ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_1_1_U340(
    .din0(data_6_val),
    .din1(mul_ln42_4_fu_380_p1),
    .dout(mul_ln42_4_fu_380_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U341(
    .din0(data_5_val),
    .din1(mul_ln42_3_fu_381_p1),
    .dout(mul_ln42_3_fu_381_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U342(
    .din0(data_23_val),
    .din1(mul_ln73_7_fu_382_p1),
    .dout(mul_ln73_7_fu_382_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U343(
    .din0(data_15_val),
    .din1(mul_ln73_2_fu_383_p1),
    .dout(mul_ln73_2_fu_383_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U344(
    .din0(data_24_val),
    .din1(mul_ln73_8_fu_384_p1),
    .dout(mul_ln73_8_fu_384_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U345(
    .din0(data_31_val),
    .din1(mul_ln42_17_fu_385_p1),
    .dout(mul_ln42_17_fu_385_p2)
);

myproject_mul_16s_12ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_1_1_U346(
    .din0(data_11_val),
    .din1(mul_ln42_8_fu_386_p1),
    .dout(mul_ln42_8_fu_386_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U347(
    .din0(data_17_val),
    .din1(mul_ln42_12_fu_387_p1),
    .dout(mul_ln42_12_fu_387_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U348(
    .din0(data_7_val),
    .din1(mul_ln42_5_fu_388_p1),
    .dout(mul_ln42_5_fu_388_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U349(
    .din0(data_27_val),
    .din1(mul_ln73_10_fu_390_p1),
    .dout(mul_ln73_10_fu_390_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U350(
    .din0(data_16_val),
    .din1(mul_ln73_3_fu_391_p1),
    .dout(mul_ln73_3_fu_391_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U351(
    .din0(data_2_val),
    .din1(mul_ln42_2_fu_392_p1),
    .dout(mul_ln42_2_fu_392_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U352(
    .din0(data_28_val),
    .din1(mul_ln42_15_fu_393_p1),
    .dout(mul_ln42_15_fu_393_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U353(
    .din0(data_18_val),
    .din1(mul_ln42_13_fu_394_p1),
    .dout(mul_ln42_13_fu_394_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_12_reg_5187 <= add_ln58_12_fu_5035_p2;
        add_ln58_17_reg_5192 <= add_ln58_17_fu_5053_p2;
        add_ln58_1_reg_5167 <= add_ln58_1_fu_4987_p2;
        add_ln58_20_reg_5197 <= add_ln58_20_fu_5071_p2;
        add_ln58_22_reg_5202 <= add_ln58_22_fu_5077_p2;
        add_ln58_23_reg_5207 <= add_ln58_23_fu_5083_p2;
        add_ln58_28_reg_5212 <= add_ln58_28_fu_5107_p2;
        add_ln58_5_reg_5172 <= add_ln58_5_fu_5005_p2;
        add_ln58_7_reg_5177 <= add_ln58_7_fu_5011_p2;
        add_ln58_8_reg_5182 <= add_ln58_8_fu_5017_p2;
        add_ln58_reg_5162 <= add_ln58_fu_4981_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_idle_pp0_0to0 == 1'b1)) begin
        ap_reset_init_pp0 = 1'b1;
    end else begin
        ap_reset_init_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_10_fu_5023_p2 = (trunc_ln42_11_fu_4665_p4 + trunc_ln42_12_fu_4680_p4);

assign add_ln58_11_fu_5029_p2 = (trunc_ln42_13_fu_4695_p4 + trunc_ln42_14_fu_4710_p4);

assign add_ln58_12_fu_5035_p2 = (add_ln58_11_fu_5029_p2 + add_ln58_10_fu_5023_p2);

assign add_ln58_13_fu_5126_p2 = (add_ln58_12_reg_5187 + add_ln58_9_fu_5122_p2);

assign add_ln58_14_fu_5131_p2 = (add_ln58_13_fu_5126_p2 + add_ln58_6_fu_5117_p2);

assign add_ln58_15_fu_5041_p2 = (trunc_ln42_15_fu_4725_p4 + trunc_ln42_16_fu_4740_p4);

assign add_ln58_16_fu_5047_p2 = (trunc_ln42_17_fu_4755_p4 + trunc_ln42_18_fu_4770_p4);

assign add_ln58_17_fu_5053_p2 = (add_ln58_16_fu_5047_p2 + add_ln58_15_fu_5041_p2);

assign add_ln58_18_fu_5059_p2 = (trunc_ln42_19_fu_4785_p4 + trunc_ln42_20_fu_4800_p4);

assign add_ln58_19_fu_5065_p2 = ($signed(sext_ln42_16_fu_4838_p1) + $signed(trunc_ln42_22_fu_4847_p4));

assign add_ln58_1_fu_4987_p2 = ($signed(trunc_ln42_2_fu_4482_p4) + $signed(sext_ln42_3_fu_4507_p1));

assign add_ln58_20_fu_5071_p2 = (add_ln58_19_fu_5065_p2 + add_ln58_18_fu_5059_p2);

assign add_ln58_21_fu_5137_p2 = (add_ln58_20_reg_5197 + add_ln58_17_reg_5192);

assign add_ln58_22_fu_5077_p2 = (trunc_ln42_23_fu_4862_p4 + trunc_ln42_24_fu_4877_p4);

assign add_ln58_23_fu_5083_p2 = (trunc_ln42_25_fu_4892_p4 + trunc_ln42_26_fu_4907_p4);

assign add_ln58_24_fu_5141_p2 = (add_ln58_23_reg_5207 + add_ln58_22_reg_5202);

assign add_ln58_25_fu_5089_p2 = (trunc_ln42_27_fu_4922_p4 + trunc_ln42_28_fu_4937_p4);

assign add_ln58_26_fu_5095_p2 = (trunc_ln42_30_fu_4971_p4 + 16'd100);

assign add_ln58_27_fu_5101_p2 = ($signed(add_ln58_26_fu_5095_p2) + $signed(sext_ln42_20_fu_4962_p1));

assign add_ln58_28_fu_5107_p2 = (add_ln58_27_fu_5101_p2 + add_ln58_25_fu_5089_p2);

assign add_ln58_29_fu_5145_p2 = (add_ln58_28_reg_5212 + add_ln58_24_fu_5141_p2);

assign add_ln58_2_fu_5113_p2 = (add_ln58_1_reg_5167 + add_ln58_reg_5162);

assign add_ln58_30_fu_5150_p2 = (add_ln58_29_fu_5145_p2 + add_ln58_21_fu_5137_p2);

assign add_ln58_3_fu_4993_p2 = (trunc_ln42_4_fu_4516_p4 + trunc_ln42_5_fu_4531_p4);

assign add_ln58_4_fu_4999_p2 = (trunc_ln42_6_fu_4546_p4 + trunc_ln42_7_fu_4561_p4);

assign add_ln58_5_fu_5005_p2 = (add_ln58_4_fu_4999_p2 + add_ln58_3_fu_4993_p2);

assign add_ln58_6_fu_5117_p2 = (add_ln58_5_reg_5172 + add_ln58_2_fu_5113_p2);

assign add_ln58_7_fu_5011_p2 = ($signed(sext_ln42_7_fu_4611_p1) + $signed(trunc_ln42_9_fu_4620_p4));

assign add_ln58_8_fu_5017_p2 = (trunc_ln42_s_fu_4635_p4 + trunc_ln42_10_fu_4650_p4);

assign add_ln58_9_fu_5122_p2 = (add_ln58_8_reg_5182 + add_ln58_7_reg_5177);

assign add_ln58_fu_4981_p2 = (trunc_ln_fu_4452_p4 + trunc_ln42_1_fu_4467_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = (add_ln58_30_fu_5150_p2 + add_ln58_14_fu_5131_p2);

assign mul_ln42_10_fu_364_p1 = 26'd1224;

assign mul_ln42_11_fu_370_p1 = 26'd67108229;

assign mul_ln42_12_fu_387_p1 = 26'd67108258;

assign mul_ln42_13_fu_394_p1 = 26'd67107879;

assign mul_ln42_14_fu_375_p1 = 26'd775;

assign mul_ln42_15_fu_393_p1 = 26'd932;

assign mul_ln42_16_fu_367_p1 = 26'd67108287;

assign mul_ln42_17_fu_385_p1 = 26'd840;

assign mul_ln42_1_fu_374_p1 = 26'd67108234;

assign mul_ln42_2_fu_392_p1 = 26'd67108026;

assign mul_ln42_3_fu_381_p1 = 26'd647;

assign mul_ln42_4_fu_380_p1 = 26'd1326;

assign mul_ln42_5_fu_388_p1 = 26'd67108231;

assign mul_ln42_6_fu_366_p1 = 26'd67107193;

assign mul_ln42_7_fu_373_p1 = 26'd566;

assign mul_ln42_8_fu_386_p1 = 26'd1257;

assign mul_ln42_9_fu_365_p1 = 26'd67107493;

assign mul_ln42_fu_376_p1 = 26'd67107706;

assign mul_ln73_10_fu_390_p1 = 26'd403;

assign mul_ln73_11_fu_379_p1 = 25'd33554226;

assign mul_ln73_1_fu_368_p1 = 26'd287;

assign mul_ln73_2_fu_383_p1 = 26'd300;

assign mul_ln73_3_fu_391_p1 = 26'd502;

assign mul_ln73_4_fu_372_p1 = 26'd67108580;

assign mul_ln73_5_fu_378_p1 = 26'd374;

assign mul_ln73_6_fu_371_p1 = 26'd67108422;

assign mul_ln73_7_fu_382_p1 = 26'd67108365;

assign mul_ln73_8_fu_384_p1 = 26'd67108457;

assign mul_ln73_9_fu_369_p1 = 26'd67108427;

assign mul_ln73_fu_377_p1 = 25'd33554274;

assign sext_ln42_16_fu_4838_p1 = $signed(trunc_ln42_21_fu_4828_p4);

assign sext_ln42_20_fu_4962_p1 = $signed(trunc_ln42_29_fu_4952_p4);

assign sext_ln42_3_fu_4507_p1 = $signed(trunc_ln42_3_fu_4497_p4);

assign sext_ln42_7_fu_4611_p1 = $signed(trunc_ln42_8_fu_4601_p4);

assign sext_ln73_1_fu_4591_p1 = $signed(tmp_5_fu_4583_p3);

assign sext_ln73_2_fu_4818_p1 = $signed(tmp_6_fu_4810_p3);

assign sext_ln73_fu_4579_p1 = $signed(tmp_fu_4571_p3);

assign sub_ln73_1_fu_4822_p2 = ($signed(24'd0) - $signed(sext_ln73_2_fu_4818_p1));

assign sub_ln73_fu_4595_p2 = ($signed(sext_ln73_1_fu_4591_p1) - $signed(sext_ln73_fu_4579_p1));

assign tmp_5_fu_4583_p3 = {{data_8_val}, {5'd0}};

assign tmp_6_fu_4810_p3 = {{data_22_val}, {7'd0}};

assign tmp_fu_4571_p3 = {{data_8_val}, {8'd0}};

assign trunc_ln42_10_fu_4650_p4 = {{mul_ln42_8_fu_386_p2[25:10]}};

assign trunc_ln42_11_fu_4665_p4 = {{mul_ln42_9_fu_365_p2[25:10]}};

assign trunc_ln42_12_fu_4680_p4 = {{mul_ln42_10_fu_364_p2[25:10]}};

assign trunc_ln42_13_fu_4695_p4 = {{mul_ln42_11_fu_370_p2[25:10]}};

assign trunc_ln42_14_fu_4710_p4 = {{mul_ln73_2_fu_383_p2[25:10]}};

assign trunc_ln42_15_fu_4725_p4 = {{mul_ln73_3_fu_391_p2[25:10]}};

assign trunc_ln42_16_fu_4740_p4 = {{mul_ln42_12_fu_387_p2[25:10]}};

assign trunc_ln42_17_fu_4755_p4 = {{mul_ln42_13_fu_394_p2[25:10]}};

assign trunc_ln42_18_fu_4770_p4 = {{mul_ln73_4_fu_372_p2[25:10]}};

assign trunc_ln42_19_fu_4785_p4 = {{mul_ln73_5_fu_378_p2[25:10]}};

assign trunc_ln42_1_fu_4467_p4 = {{mul_ln42_1_fu_374_p2[25:10]}};

assign trunc_ln42_20_fu_4800_p4 = {{mul_ln73_6_fu_371_p2[25:10]}};

assign trunc_ln42_21_fu_4828_p4 = {{sub_ln73_1_fu_4822_p2[23:10]}};

assign trunc_ln42_22_fu_4847_p4 = {{mul_ln73_7_fu_382_p2[25:10]}};

assign trunc_ln42_23_fu_4862_p4 = {{mul_ln73_8_fu_384_p2[25:10]}};

assign trunc_ln42_24_fu_4877_p4 = {{mul_ln73_9_fu_369_p2[25:10]}};

assign trunc_ln42_25_fu_4892_p4 = {{mul_ln42_14_fu_375_p2[25:10]}};

assign trunc_ln42_26_fu_4907_p4 = {{mul_ln73_10_fu_390_p2[25:10]}};

assign trunc_ln42_27_fu_4922_p4 = {{mul_ln42_15_fu_393_p2[25:10]}};

assign trunc_ln42_28_fu_4937_p4 = {{mul_ln42_16_fu_367_p2[25:10]}};

assign trunc_ln42_29_fu_4952_p4 = {{mul_ln73_11_fu_379_p2[24:10]}};

assign trunc_ln42_2_fu_4482_p4 = {{mul_ln42_2_fu_392_p2[25:10]}};

assign trunc_ln42_30_fu_4971_p4 = {{mul_ln42_17_fu_385_p2[25:10]}};

assign trunc_ln42_3_fu_4497_p4 = {{mul_ln73_fu_377_p2[24:10]}};

assign trunc_ln42_4_fu_4516_p4 = {{mul_ln73_1_fu_368_p2[25:10]}};

assign trunc_ln42_5_fu_4531_p4 = {{mul_ln42_3_fu_381_p2[25:10]}};

assign trunc_ln42_6_fu_4546_p4 = {{mul_ln42_4_fu_380_p2[25:10]}};

assign trunc_ln42_7_fu_4561_p4 = {{mul_ln42_5_fu_388_p2[25:10]}};

assign trunc_ln42_8_fu_4601_p4 = {{sub_ln73_fu_4595_p2[24:10]}};

assign trunc_ln42_9_fu_4620_p4 = {{mul_ln42_6_fu_366_p2[25:10]}};

assign trunc_ln42_s_fu_4635_p4 = {{mul_ln42_7_fu_373_p2[25:10]}};

assign trunc_ln_fu_4452_p4 = {{mul_ln42_fu_376_p2[25:10]}};

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s
