// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module myproject_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_s_w2_66_ROM_NPbkb (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 1020;
parameter AddressWidth = 3;
parameter AddressRange = 5;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
(* rom_style = "block" *)reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("./myproject_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_32u_config2_s_w2_66_ROM_NPbkb.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

