-- ==============================================================
-- Generated by Vitis HLS v2023.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer8_out_dout : IN STD_LOGIC_VECTOR (79 downto 0);
    layer8_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer8_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer8_out_empty_n : IN STD_LOGIC;
    layer8_out_read : OUT STD_LOGIC;
    layer9_out_TDATA : OUT STD_LOGIC_VECTOR (79 downto 0);
    layer9_out_TVALID : OUT STD_LOGIC;
    layer9_out_TREADY : IN STD_LOGIC );
end;


architecture behav of myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal exp_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce0 : STD_LOGIC;
    signal exp_table_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce1 : STD_LOGIC;
    signal exp_table_q1 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce2 : STD_LOGIC;
    signal exp_table_q2 : STD_LOGIC_VECTOR (10 downto 0);
    signal invert_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table_ce0 : STD_LOGIC;
    signal invert_table_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal layer8_out_blk_n : STD_LOGIC;
    signal layer9_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal trunc_ln198_fu_233_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln198_reg_575 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln198_3_reg_581 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln198_4_reg_587 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_592 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_reg_598 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_reg_604 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln213_fu_287_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln213_reg_610 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln213_2_reg_615 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln213_3_reg_620 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln213_4_reg_625 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln66_fu_331_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_reg_630 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal select_ln66_1_fu_347_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_1_reg_636 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_2_fu_363_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_2_reg_642 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal select_ln66_3_fu_382_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln66_3_reg_648 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_5_reg_657 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_7_reg_662 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_9_reg_667 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_reg_672 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_reg_677 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal exp_table_load_reg_692 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal exp_table_load_2_reg_703 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_1_reg_719 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal exp_table_load_3_reg_725 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_4_reg_731 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln51_fu_485_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_reg_737 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_reg_742 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal inv_exp_sum_reg_752 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal sext_ln241_fu_539_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln241_reg_757 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal zext_ln241_fu_543_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_213_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln3_reg_768 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal zext_ln241_1_fu_547_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal zext_ln241_2_fu_551_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln241_1_reg_783 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal grp_fu_223_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_2_reg_788 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln241_3_fu_555_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal zext_ln241_4_fu_559_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal zext_ln223_fu_459_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_2_fu_463_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_1_fu_467_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_3_fu_471_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_4_fu_475_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln232_fu_535_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal grp_fu_177_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_177_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_178_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_178_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_177_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_178_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal icmp_ln66_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_1_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_1_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_2_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_2_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_3_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_3_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_fu_379_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_fu_389_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_5_fu_393_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_6_fu_397_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_7_fu_401_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_8_fu_405_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln141_fu_479_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln141_2_fu_482_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln141_1_fu_491_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_1_fu_500_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln141_3_fu_494_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln51_fu_497_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_2_fu_509_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln51_2_fu_515_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln51_1_fu_505_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln51_3_fu_519_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_177_ce : STD_LOGIC;
    signal grp_fu_178_ce : STD_LOGIC;
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_18s_11ns_26_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s_exp_tablefYi IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s_invert_tag8j IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    exp_table_U : component myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s_exp_tablefYi
    generic map (
        DataWidth => 11,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table_address0,
        ce0 => exp_table_ce0,
        q0 => exp_table_q0,
        address1 => exp_table_address1,
        ce1 => exp_table_ce1,
        q1 => exp_table_q1,
        address2 => exp_table_address2,
        ce2 => exp_table_ce2,
        q2 => exp_table_q2);

    invert_table_U : component myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s_invert_tag8j
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table_address0,
        ce0 => invert_table_ce0,
        q0 => invert_table_q0);

    mul_18s_11ns_26_2_1_U1124 : component myproject_mul_18s_11ns_26_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_177_p0,
        din1 => grp_fu_177_p1,
        ce => grp_fu_177_ce,
        dout => grp_fu_177_p2);

    mul_18s_11ns_26_2_1_U1125 : component myproject_mul_18s_11ns_26_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_178_p0,
        din1 => grp_fu_178_p1,
        ce => grp_fu_178_ce,
        dout => grp_fu_178_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                add_ln51_reg_737 <= add_ln51_fu_485_p2;
                exp_table_load_1_reg_719 <= exp_table_q2;
                exp_table_load_3_reg_725 <= exp_table_q1;
                exp_table_load_4_reg_731 <= exp_table_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                exp_table_load_2_reg_703 <= exp_table_q0;
                exp_table_load_reg_692 <= exp_table_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                inv_exp_sum_reg_752 <= invert_table_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                select_ln66_1_reg_636 <= select_ln66_1_fu_347_p3;
                select_ln66_reg_630 <= select_ln66_fu_331_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                select_ln66_2_reg_642 <= select_ln66_2_fu_363_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                select_ln66_3_reg_648 <= select_ln66_3_fu_382_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                sext_ln241_reg_757 <= sext_ln241_fu_539_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                tmp_1_reg_598 <= layer8_out_dout(47 downto 32);
                tmp_6_reg_604 <= layer8_out_dout(78 downto 64);
                tmp_reg_592 <= layer8_out_dout(31 downto 16);
                trunc_ln198_3_reg_581 <= layer8_out_dout(63 downto 48);
                trunc_ln198_4_reg_587 <= layer8_out_dout(79 downto 64);
                trunc_ln198_reg_575 <= trunc_ln198_fu_233_p1;
                trunc_ln213_2_reg_615 <= layer8_out_dout(30 downto 16);
                trunc_ln213_3_reg_620 <= layer8_out_dout(46 downto 32);
                trunc_ln213_4_reg_625 <= layer8_out_dout(62 downto 48);
                trunc_ln213_reg_610 <= trunc_ln213_fu_287_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                tmp_2_reg_742 <= add_ln51_3_fu_519_p2(12 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                tmp_4_reg_677 <= d_xi_xmax_8_fu_405_p2(14 downto 5);
                tmp_5_reg_657 <= d_xi_xmax_fu_389_p2(14 downto 5);
                tmp_7_reg_662 <= d_xi_xmax_5_fu_393_p2(14 downto 5);
                tmp_9_reg_667 <= d_xi_xmax_6_fu_397_p2(14 downto 5);
                tmp_s_reg_672 <= d_xi_xmax_7_fu_401_p2(14 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                trunc_ln241_1_reg_783 <= grp_fu_177_p2(25 downto 10);
                trunc_ln241_2_reg_788 <= grp_fu_178_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                trunc_ln3_reg_768 <= grp_fu_177_p2(25 downto 10);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, layer8_out_empty_n, layer9_out_TREADY, ap_CS_fsm_state15)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((layer8_out_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                if (((layer9_out_TREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln51_1_fu_500_p2 <= std_logic_vector(unsigned(add_ln51_reg_737) + unsigned(zext_ln141_1_fu_491_p1));
    add_ln51_2_fu_509_p2 <= std_logic_vector(unsigned(zext_ln141_3_fu_494_p1) + unsigned(zext_ln51_fu_497_p1));
    add_ln51_3_fu_519_p2 <= std_logic_vector(unsigned(zext_ln51_2_fu_515_p1) + unsigned(zext_ln51_1_fu_505_p1));
    add_ln51_fu_485_p2 <= std_logic_vector(unsigned(zext_ln141_fu_479_p1) + unsigned(zext_ln141_2_fu_482_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;

    ap_ST_fsm_state15_blk_assign_proc : process(layer9_out_TREADY)
    begin
        if ((layer9_out_TREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state15_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state15_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state16_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, layer8_out_empty_n)
    begin
        if (((layer8_out_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, layer8_out_empty_n)
    begin
                ap_block_state1 <= ((layer8_out_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    d_xi_xmax_5_fu_393_p2 <= std_logic_vector(unsigned(select_ln66_3_reg_648) - unsigned(trunc_ln213_2_reg_615));
    d_xi_xmax_6_fu_397_p2 <= std_logic_vector(unsigned(select_ln66_3_reg_648) - unsigned(trunc_ln213_3_reg_620));
    d_xi_xmax_7_fu_401_p2 <= std_logic_vector(unsigned(select_ln66_3_reg_648) - unsigned(trunc_ln213_4_reg_625));
    d_xi_xmax_8_fu_405_p2 <= std_logic_vector(unsigned(select_ln66_3_reg_648) - unsigned(tmp_6_reg_604));
    d_xi_xmax_fu_389_p2 <= std_logic_vector(unsigned(select_ln66_3_reg_648) - unsigned(trunc_ln213_reg_610));

    exp_table_address0_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7, zext_ln223_2_fu_463_p1, zext_ln223_4_fu_475_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            exp_table_address0 <= zext_ln223_4_fu_475_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            exp_table_address0 <= zext_ln223_2_fu_463_p1(10 - 1 downto 0);
        else 
            exp_table_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    exp_table_address1_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7, zext_ln223_fu_459_p1, zext_ln223_3_fu_471_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            exp_table_address1 <= zext_ln223_3_fu_471_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            exp_table_address1 <= zext_ln223_fu_459_p1(10 - 1 downto 0);
        else 
            exp_table_address1 <= "XXXXXXXXXX";
        end if; 
    end process;

    exp_table_address2 <= zext_ln223_1_fu_467_p1(10 - 1 downto 0);

    exp_table_ce0_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            exp_table_ce0 <= ap_const_logic_1;
        else 
            exp_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce1_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            exp_table_ce1 <= ap_const_logic_1;
        else 
            exp_table_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce2_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            exp_table_ce2 <= ap_const_logic_1;
        else 
            exp_table_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_177_ce_assign_proc : process(layer9_out_TREADY, ap_CS_fsm_state15, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((layer9_out_TREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state15)))) then 
            grp_fu_177_ce <= ap_const_logic_1;
        else 
            grp_fu_177_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_177_p0_assign_proc : process(sext_ln241_fu_539_p1, sext_ln241_reg_757, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            grp_fu_177_p0 <= sext_ln241_reg_757(18 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_177_p0 <= sext_ln241_fu_539_p1(18 - 1 downto 0);
        else 
            grp_fu_177_p0 <= "XXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_177_p1_assign_proc : process(ap_CS_fsm_state12, zext_ln241_fu_543_p1, ap_CS_fsm_state13, zext_ln241_1_fu_547_p1, ap_CS_fsm_state14, zext_ln241_3_fu_555_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            grp_fu_177_p1 <= zext_ln241_3_fu_555_p1(11 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_177_p1 <= zext_ln241_1_fu_547_p1(11 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_177_p1 <= zext_ln241_fu_543_p1(11 - 1 downto 0);
        else 
            grp_fu_177_p1 <= "XXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_178_ce_assign_proc : process(layer9_out_TREADY, ap_CS_fsm_state15, ap_CS_fsm_state13, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or ((layer9_out_TREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state15)))) then 
            grp_fu_178_ce <= ap_const_logic_1;
        else 
            grp_fu_178_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_178_p0 <= sext_ln241_reg_757(18 - 1 downto 0);

    grp_fu_178_p1_assign_proc : process(ap_CS_fsm_state13, zext_ln241_2_fu_551_p1, ap_CS_fsm_state14, zext_ln241_4_fu_559_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            grp_fu_178_p1 <= zext_ln241_4_fu_559_p1(11 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_178_p1 <= zext_ln241_2_fu_551_p1(11 - 1 downto 0);
        else 
            grp_fu_178_p1 <= "XXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_213_p4 <= grp_fu_177_p2(25 downto 10);
    grp_fu_223_p4 <= grp_fu_178_p2(25 downto 10);
    icmp_ln66_1_fu_337_p2 <= "1" when (signed(tmp_1_reg_598) < signed(trunc_ln198_3_reg_581)) else "0";
    icmp_ln66_2_fu_353_p2 <= "1" when (signed(select_ln66_reg_630) < signed(select_ln66_1_reg_636)) else "0";
    icmp_ln66_3_fu_369_p2 <= "1" when (signed(select_ln66_2_reg_642) < signed(trunc_ln198_4_reg_587)) else "0";
    icmp_ln66_fu_321_p2 <= "1" when (signed(trunc_ln198_reg_575) < signed(tmp_reg_592)) else "0";
    invert_table_address0 <= zext_ln232_fu_535_p1(10 - 1 downto 0);

    invert_table_ce0_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            invert_table_ce0 <= ap_const_logic_1;
        else 
            invert_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    layer8_out_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, layer8_out_empty_n)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer8_out_blk_n <= layer8_out_empty_n;
        else 
            layer8_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer8_out_read_assign_proc : process(ap_start, ap_CS_fsm_state1, layer8_out_empty_n)
    begin
        if ((not(((layer8_out_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer8_out_read <= ap_const_logic_1;
        else 
            layer8_out_read <= ap_const_logic_0;
        end if; 
    end process;

    layer9_out_TDATA <= ((((grp_fu_223_p4 & grp_fu_213_p4) & trunc_ln241_2_reg_788) & trunc_ln241_1_reg_783) & trunc_ln3_reg_768);

    layer9_out_TDATA_blk_n_assign_proc : process(layer9_out_TREADY, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            layer9_out_TDATA_blk_n <= layer9_out_TREADY;
        else 
            layer9_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer9_out_TVALID_assign_proc : process(layer9_out_TREADY, ap_CS_fsm_state15)
    begin
        if (((layer9_out_TREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then 
            layer9_out_TVALID <= ap_const_logic_1;
        else 
            layer9_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    select_ln66_1_fu_347_p3 <= 
        tmp_1_reg_598 when (xor_ln66_1_fu_341_p2(0) = '1') else 
        trunc_ln198_3_reg_581;
    select_ln66_2_fu_363_p3 <= 
        select_ln66_reg_630 when (xor_ln66_2_fu_357_p2(0) = '1') else 
        select_ln66_1_reg_636;
    select_ln66_3_fu_382_p3 <= 
        trunc_ln66_fu_379_p1 when (xor_ln66_3_fu_373_p2(0) = '1') else 
        tmp_6_reg_604;
    select_ln66_fu_331_p3 <= 
        trunc_ln198_reg_575 when (xor_ln66_fu_325_p2(0) = '1') else 
        tmp_reg_592;
        sext_ln241_fu_539_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inv_exp_sum_reg_752),26));

    trunc_ln198_fu_233_p1 <= layer8_out_dout(16 - 1 downto 0);
    trunc_ln213_fu_287_p1 <= layer8_out_dout(15 - 1 downto 0);
    trunc_ln66_fu_379_p1 <= select_ln66_2_reg_642(15 - 1 downto 0);
    xor_ln66_1_fu_341_p2 <= (icmp_ln66_1_fu_337_p2 xor ap_const_lv1_1);
    xor_ln66_2_fu_357_p2 <= (icmp_ln66_2_fu_353_p2 xor ap_const_lv1_1);
    xor_ln66_3_fu_373_p2 <= (icmp_ln66_3_fu_369_p2 xor ap_const_lv1_1);
    xor_ln66_fu_325_p2 <= (icmp_ln66_fu_321_p2 xor ap_const_lv1_1);
    zext_ln141_1_fu_491_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_1_reg_719),12));
    zext_ln141_2_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_2_reg_703),12));
    zext_ln141_3_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_3_reg_725),12));
    zext_ln141_fu_479_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_reg_692),12));
    zext_ln223_1_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_reg_662),64));
    zext_ln223_2_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_reg_667),64));
    zext_ln223_3_fu_471_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_reg_672),64));
    zext_ln223_4_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_reg_677),64));
    zext_ln223_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_reg_657),64));
    zext_ln232_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_reg_742),64));
    zext_ln241_1_fu_547_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_1_reg_719),26));
    zext_ln241_2_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_2_reg_703),26));
    zext_ln241_3_fu_555_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_3_reg_725),26));
    zext_ln241_4_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_4_reg_731),26));
    zext_ln241_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_reg_692),26));
    zext_ln51_1_fu_505_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln51_1_fu_500_p2),13));
    zext_ln51_2_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln51_2_fu_509_p2),13));
    zext_ln51_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_4_reg_731),12));
end behav;
