-- ==============================================================
-- Generated by Vitis HLS v2023.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config7_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer6_out_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    layer6_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer6_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer6_out_empty_n : IN STD_LOGIC;
    layer6_out_read : OUT STD_LOGIC;
    layer7_out_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer7_out_full_n : IN STD_LOGIC;
    layer7_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100000";
    constant ap_const_lv32_1EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111101111";
    constant ap_const_lv32_1F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111110000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_5E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011110";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_8E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001110";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_9E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011110";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_AE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101110";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111110";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_CE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001110";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_DE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011110";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_EE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101110";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_FE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111110";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_10F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001111";
    constant ap_const_lv32_10E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001110";
    constant ap_const_lv32_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_11E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011110";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_12F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101111";
    constant ap_const_lv32_12E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101110";
    constant ap_const_lv32_130 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_13E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111110";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_14F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001111";
    constant ap_const_lv32_14E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001110";
    constant ap_const_lv32_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010000";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_15E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011110";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_16F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101111";
    constant ap_const_lv32_16E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101110";
    constant ap_const_lv32_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_17E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111110";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_18F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001111";
    constant ap_const_lv32_18E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001110";
    constant ap_const_lv32_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010000";
    constant ap_const_lv32_19F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011111";
    constant ap_const_lv32_19E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011110";
    constant ap_const_lv32_1A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110100000";
    constant ap_const_lv32_1AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101111";
    constant ap_const_lv32_1AE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101110";
    constant ap_const_lv32_1B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111110";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111001111";
    constant ap_const_lv32_1CE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111001110";
    constant ap_const_lv32_1D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111010000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";
    constant ap_const_lv32_1DE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011110";
    constant ap_const_lv32_1EE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111101110";
    constant ap_const_lv32_1FE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111110";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer6_out_blk_n : STD_LOGIC;
    signal layer7_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal in_data_fu_227_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal in_data_reg_1404 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal trunc_ln44_2_fu_231_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln44_2_reg_1409 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln44_65_reg_1414 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_66_reg_1419 : STD_LOGIC_VECTOR (15 downto 0);
    signal in_data_10_reg_1424 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_s_reg_1429 : STD_LOGIC_VECTOR (14 downto 0);
    signal in_data_11_reg_1434 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_67_reg_1439 : STD_LOGIC_VECTOR (14 downto 0);
    signal in_data_12_reg_1444 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_68_reg_1449 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_reg_1454 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_69_reg_1459 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_s_reg_1464 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_70_reg_1469 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_57_reg_1474 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_71_reg_1479 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_58_reg_1484 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_72_reg_1489 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_59_reg_1494 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_73_reg_1499 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_60_reg_1504 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_74_reg_1509 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_61_reg_1514 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_75_reg_1519 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_62_reg_1524 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_76_reg_1529 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_63_reg_1534 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_77_reg_1539 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_64_reg_1544 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_78_reg_1549 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_65_reg_1554 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_79_reg_1559 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_66_reg_1564 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_80_reg_1569 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_67_reg_1574 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_81_reg_1579 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_68_reg_1584 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_82_reg_1589 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_69_reg_1594 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_83_reg_1599 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_70_reg_1604 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_84_reg_1609 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_71_reg_1614 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_85_reg_1619 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_72_reg_1624 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_86_reg_1629 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_73_reg_1634 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_87_reg_1639 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_74_reg_1644 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_88_reg_1649 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_75_reg_1654 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_89_reg_1659 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_76_reg_1664 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_90_reg_1669 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_77_reg_1674 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_91_reg_1679 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_78_reg_1684 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_92_reg_1689 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_79_reg_1694 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_93_reg_1699 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_80_reg_1704 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_94_reg_1709 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln44_95_reg_1714 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln_reg_1719 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_fu_860_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_reg_1724 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal select_ln51_64_fu_872_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_64_reg_1729 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_65_fu_884_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_65_reg_1734 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_66_fu_896_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_66_reg_1739 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_67_fu_908_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_67_reg_1744 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_68_fu_920_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_68_reg_1749 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_69_fu_932_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_69_reg_1754 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_70_fu_944_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_70_reg_1759 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_71_fu_956_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_71_reg_1764 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_72_fu_968_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_72_reg_1769 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_73_fu_980_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_73_reg_1774 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_74_fu_992_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_74_reg_1779 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_75_fu_1004_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_75_reg_1784 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_76_fu_1016_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_76_reg_1789 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_77_fu_1028_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_77_reg_1794 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_78_fu_1040_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_78_reg_1799 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_79_fu_1052_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_79_reg_1804 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_80_fu_1064_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_80_reg_1809 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_81_fu_1076_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_81_reg_1814 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_82_fu_1088_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_82_reg_1819 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_83_fu_1100_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_83_reg_1824 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_84_fu_1112_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_84_reg_1829 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_85_fu_1124_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_85_reg_1834 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_86_fu_1136_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_86_reg_1839 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_87_fu_1148_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_87_reg_1844 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_88_fu_1160_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_88_reg_1849 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_89_fu_1172_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_89_reg_1854 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_90_fu_1184_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_90_reg_1859 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_91_fu_1196_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_91_reg_1864 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_92_fu_1208_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_92_reg_1869 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_93_fu_1220_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_93_reg_1874 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_94_fu_1232_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_94_reg_1879 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln51_fu_855_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_64_fu_867_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_65_fu_879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_66_fu_891_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_67_fu_903_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_68_fu_915_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_69_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_70_fu_939_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_71_fu_951_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_72_fu_963_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_73_fu_975_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_74_fu_987_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_75_fu_999_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_76_fu_1011_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_77_fu_1023_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_78_fu_1035_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_79_fu_1047_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_80_fu_1059_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_81_fu_1071_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_82_fu_1083_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_83_fu_1095_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_84_fu_1107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_85_fu_1119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_86_fu_1131_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_87_fu_1143_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_88_fu_1155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_89_fu_1167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_90_fu_1179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_91_fu_1191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_92_fu_1203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_93_fu_1215_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_94_fu_1227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln51_93_fu_1329_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_92_fu_1326_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_91_fu_1323_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_90_fu_1320_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_89_fu_1317_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_88_fu_1314_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_87_fu_1311_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_86_fu_1308_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_85_fu_1305_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_84_fu_1302_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_83_fu_1299_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_82_fu_1296_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_81_fu_1293_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_80_fu_1290_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_79_fu_1287_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_78_fu_1284_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_77_fu_1281_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_76_fu_1278_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_75_fu_1275_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_74_fu_1272_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_73_fu_1269_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_72_fu_1266_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_71_fu_1263_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_70_fu_1260_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_69_fu_1257_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_68_fu_1254_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_67_fu_1251_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_66_fu_1248_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_65_fu_1245_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_64_fu_1242_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_fu_1239_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln57_s_fu_1332_p33 : STD_LOGIC_VECTOR (510 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((real_start = ap_const_logic_0) or (layer6_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                in_data_10_reg_1424 <= layer6_out_dout(31 downto 16);
                in_data_11_reg_1434 <= layer6_out_dout(47 downto 32);
                in_data_12_reg_1444 <= layer6_out_dout(63 downto 48);
                in_data_reg_1404 <= in_data_fu_227_p1;
                tmp_57_reg_1474 <= layer6_out_dout(111 downto 96);
                tmp_58_reg_1484 <= layer6_out_dout(127 downto 112);
                tmp_59_reg_1494 <= layer6_out_dout(143 downto 128);
                tmp_60_reg_1504 <= layer6_out_dout(159 downto 144);
                tmp_61_reg_1514 <= layer6_out_dout(175 downto 160);
                tmp_62_reg_1524 <= layer6_out_dout(191 downto 176);
                tmp_63_reg_1534 <= layer6_out_dout(207 downto 192);
                tmp_64_reg_1544 <= layer6_out_dout(223 downto 208);
                tmp_65_reg_1554 <= layer6_out_dout(239 downto 224);
                tmp_66_reg_1564 <= layer6_out_dout(255 downto 240);
                tmp_67_reg_1574 <= layer6_out_dout(271 downto 256);
                tmp_68_reg_1584 <= layer6_out_dout(287 downto 272);
                tmp_69_reg_1594 <= layer6_out_dout(303 downto 288);
                tmp_70_reg_1604 <= layer6_out_dout(319 downto 304);
                tmp_71_reg_1614 <= layer6_out_dout(335 downto 320);
                tmp_72_reg_1624 <= layer6_out_dout(351 downto 336);
                tmp_73_reg_1634 <= layer6_out_dout(367 downto 352);
                tmp_74_reg_1644 <= layer6_out_dout(383 downto 368);
                tmp_75_reg_1654 <= layer6_out_dout(399 downto 384);
                tmp_76_reg_1664 <= layer6_out_dout(415 downto 400);
                tmp_77_reg_1674 <= layer6_out_dout(431 downto 416);
                tmp_78_reg_1684 <= layer6_out_dout(447 downto 432);
                tmp_79_reg_1694 <= layer6_out_dout(463 downto 448);
                tmp_80_reg_1704 <= layer6_out_dout(479 downto 464);
                tmp_reg_1454 <= layer6_out_dout(79 downto 64);
                tmp_s_reg_1464 <= layer6_out_dout(95 downto 80);
                trunc_ln44_2_reg_1409 <= trunc_ln44_2_fu_231_p1;
                trunc_ln44_65_reg_1414 <= layer6_out_dout(495 downto 480);
                trunc_ln44_66_reg_1419 <= layer6_out_dout(511 downto 496);
                trunc_ln44_67_reg_1439 <= layer6_out_dout(46 downto 32);
                trunc_ln44_68_reg_1449 <= layer6_out_dout(62 downto 48);
                trunc_ln44_69_reg_1459 <= layer6_out_dout(78 downto 64);
                trunc_ln44_70_reg_1469 <= layer6_out_dout(94 downto 80);
                trunc_ln44_71_reg_1479 <= layer6_out_dout(110 downto 96);
                trunc_ln44_72_reg_1489 <= layer6_out_dout(126 downto 112);
                trunc_ln44_73_reg_1499 <= layer6_out_dout(142 downto 128);
                trunc_ln44_74_reg_1509 <= layer6_out_dout(158 downto 144);
                trunc_ln44_75_reg_1519 <= layer6_out_dout(174 downto 160);
                trunc_ln44_76_reg_1529 <= layer6_out_dout(190 downto 176);
                trunc_ln44_77_reg_1539 <= layer6_out_dout(206 downto 192);
                trunc_ln44_78_reg_1549 <= layer6_out_dout(222 downto 208);
                trunc_ln44_79_reg_1559 <= layer6_out_dout(238 downto 224);
                trunc_ln44_80_reg_1569 <= layer6_out_dout(254 downto 240);
                trunc_ln44_81_reg_1579 <= layer6_out_dout(270 downto 256);
                trunc_ln44_82_reg_1589 <= layer6_out_dout(286 downto 272);
                trunc_ln44_83_reg_1599 <= layer6_out_dout(302 downto 288);
                trunc_ln44_84_reg_1609 <= layer6_out_dout(318 downto 304);
                trunc_ln44_85_reg_1619 <= layer6_out_dout(334 downto 320);
                trunc_ln44_86_reg_1629 <= layer6_out_dout(350 downto 336);
                trunc_ln44_87_reg_1639 <= layer6_out_dout(366 downto 352);
                trunc_ln44_88_reg_1649 <= layer6_out_dout(382 downto 368);
                trunc_ln44_89_reg_1659 <= layer6_out_dout(398 downto 384);
                trunc_ln44_90_reg_1669 <= layer6_out_dout(414 downto 400);
                trunc_ln44_91_reg_1679 <= layer6_out_dout(430 downto 416);
                trunc_ln44_92_reg_1689 <= layer6_out_dout(446 downto 432);
                trunc_ln44_93_reg_1699 <= layer6_out_dout(462 downto 448);
                trunc_ln44_94_reg_1709 <= layer6_out_dout(478 downto 464);
                trunc_ln44_95_reg_1714 <= layer6_out_dout(494 downto 480);
                trunc_ln44_s_reg_1429 <= layer6_out_dout(30 downto 16);
                trunc_ln_reg_1719 <= layer6_out_dout(510 downto 496);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                select_ln51_64_reg_1729 <= select_ln51_64_fu_872_p3;
                select_ln51_65_reg_1734 <= select_ln51_65_fu_884_p3;
                select_ln51_66_reg_1739 <= select_ln51_66_fu_896_p3;
                select_ln51_67_reg_1744 <= select_ln51_67_fu_908_p3;
                select_ln51_68_reg_1749 <= select_ln51_68_fu_920_p3;
                select_ln51_69_reg_1754 <= select_ln51_69_fu_932_p3;
                select_ln51_70_reg_1759 <= select_ln51_70_fu_944_p3;
                select_ln51_71_reg_1764 <= select_ln51_71_fu_956_p3;
                select_ln51_72_reg_1769 <= select_ln51_72_fu_968_p3;
                select_ln51_73_reg_1774 <= select_ln51_73_fu_980_p3;
                select_ln51_74_reg_1779 <= select_ln51_74_fu_992_p3;
                select_ln51_75_reg_1784 <= select_ln51_75_fu_1004_p3;
                select_ln51_76_reg_1789 <= select_ln51_76_fu_1016_p3;
                select_ln51_77_reg_1794 <= select_ln51_77_fu_1028_p3;
                select_ln51_78_reg_1799 <= select_ln51_78_fu_1040_p3;
                select_ln51_79_reg_1804 <= select_ln51_79_fu_1052_p3;
                select_ln51_80_reg_1809 <= select_ln51_80_fu_1064_p3;
                select_ln51_81_reg_1814 <= select_ln51_81_fu_1076_p3;
                select_ln51_82_reg_1819 <= select_ln51_82_fu_1088_p3;
                select_ln51_83_reg_1824 <= select_ln51_83_fu_1100_p3;
                select_ln51_84_reg_1829 <= select_ln51_84_fu_1112_p3;
                select_ln51_85_reg_1834 <= select_ln51_85_fu_1124_p3;
                select_ln51_86_reg_1839 <= select_ln51_86_fu_1136_p3;
                select_ln51_87_reg_1844 <= select_ln51_87_fu_1148_p3;
                select_ln51_88_reg_1849 <= select_ln51_88_fu_1160_p3;
                select_ln51_89_reg_1854 <= select_ln51_89_fu_1172_p3;
                select_ln51_90_reg_1859 <= select_ln51_90_fu_1184_p3;
                select_ln51_91_reg_1864 <= select_ln51_91_fu_1196_p3;
                select_ln51_92_reg_1869 <= select_ln51_92_fu_1208_p3;
                select_ln51_93_reg_1874 <= select_ln51_93_fu_1220_p3;
                select_ln51_94_reg_1879 <= select_ln51_94_fu_1232_p3;
                select_ln51_reg_1724 <= select_ln51_fu_860_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, layer6_out_empty_n, layer7_out_full_n, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (layer6_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg, layer6_out_empty_n)
    begin
        if (((real_start = ap_const_logic_0) or (layer6_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(layer7_out_full_n)
    begin
        if ((layer7_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer6_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer6_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer7_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    icmp_ln51_64_fu_867_p2 <= "1" when (signed(in_data_10_reg_1424) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_65_fu_879_p2 <= "1" when (signed(in_data_11_reg_1434) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_66_fu_891_p2 <= "1" when (signed(in_data_12_reg_1444) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_67_fu_903_p2 <= "1" when (signed(tmp_reg_1454) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_68_fu_915_p2 <= "1" when (signed(tmp_s_reg_1464) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_69_fu_927_p2 <= "1" when (signed(tmp_57_reg_1474) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_70_fu_939_p2 <= "1" when (signed(tmp_58_reg_1484) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_71_fu_951_p2 <= "1" when (signed(tmp_59_reg_1494) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_72_fu_963_p2 <= "1" when (signed(tmp_60_reg_1504) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_73_fu_975_p2 <= "1" when (signed(tmp_61_reg_1514) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_74_fu_987_p2 <= "1" when (signed(tmp_62_reg_1524) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_75_fu_999_p2 <= "1" when (signed(tmp_63_reg_1534) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_76_fu_1011_p2 <= "1" when (signed(tmp_64_reg_1544) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_77_fu_1023_p2 <= "1" when (signed(tmp_65_reg_1554) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_78_fu_1035_p2 <= "1" when (signed(tmp_66_reg_1564) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_79_fu_1047_p2 <= "1" when (signed(tmp_67_reg_1574) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_80_fu_1059_p2 <= "1" when (signed(tmp_68_reg_1584) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_81_fu_1071_p2 <= "1" when (signed(tmp_69_reg_1594) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_82_fu_1083_p2 <= "1" when (signed(tmp_70_reg_1604) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_83_fu_1095_p2 <= "1" when (signed(tmp_71_reg_1614) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_84_fu_1107_p2 <= "1" when (signed(tmp_72_reg_1624) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_85_fu_1119_p2 <= "1" when (signed(tmp_73_reg_1634) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_86_fu_1131_p2 <= "1" when (signed(tmp_74_reg_1644) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_87_fu_1143_p2 <= "1" when (signed(tmp_75_reg_1654) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_88_fu_1155_p2 <= "1" when (signed(tmp_76_reg_1664) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_89_fu_1167_p2 <= "1" when (signed(tmp_77_reg_1674) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_90_fu_1179_p2 <= "1" when (signed(tmp_78_reg_1684) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_91_fu_1191_p2 <= "1" when (signed(tmp_79_reg_1694) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_92_fu_1203_p2 <= "1" when (signed(tmp_80_reg_1704) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_93_fu_1215_p2 <= "1" when (signed(trunc_ln44_65_reg_1414) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_94_fu_1227_p2 <= "1" when (signed(trunc_ln44_66_reg_1419) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_fu_855_p2 <= "1" when (signed(in_data_reg_1404) > signed(ap_const_lv16_0)) else "0";
    in_data_fu_227_p1 <= layer6_out_dout(16 - 1 downto 0);

    internal_ap_ready_assign_proc : process(layer7_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer6_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer6_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer6_out_blk_n <= layer6_out_empty_n;
        else 
            layer6_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer6_out_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer6_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (layer6_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer6_out_read <= ap_const_logic_1;
        else 
            layer6_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer7_out_blk_n_assign_proc : process(layer7_out_full_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer7_out_blk_n <= layer7_out_full_n;
        else 
            layer7_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer7_out_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln57_s_fu_1332_p33),512));

    layer7_out_write_assign_proc : process(layer7_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer7_out_write <= ap_const_logic_1;
        else 
            layer7_out_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln57_s_fu_1332_p33 <= (((((((((((((((((((((((((((((((select_ln51_94_reg_1879 & zext_ln51_93_fu_1329_p1) & zext_ln51_92_fu_1326_p1) & zext_ln51_91_fu_1323_p1) & zext_ln51_90_fu_1320_p1) & zext_ln51_89_fu_1317_p1) & zext_ln51_88_fu_1314_p1) & zext_ln51_87_fu_1311_p1) & zext_ln51_86_fu_1308_p1) & zext_ln51_85_fu_1305_p1) & zext_ln51_84_fu_1302_p1) & zext_ln51_83_fu_1299_p1) & zext_ln51_82_fu_1296_p1) & zext_ln51_81_fu_1293_p1) & zext_ln51_80_fu_1290_p1) & zext_ln51_79_fu_1287_p1) & zext_ln51_78_fu_1284_p1) & zext_ln51_77_fu_1281_p1) & zext_ln51_76_fu_1278_p1) & zext_ln51_75_fu_1275_p1) & zext_ln51_74_fu_1272_p1) & zext_ln51_73_fu_1269_p1) & zext_ln51_72_fu_1266_p1) & zext_ln51_71_fu_1263_p1) & zext_ln51_70_fu_1260_p1) & zext_ln51_69_fu_1257_p1) & zext_ln51_68_fu_1254_p1) & zext_ln51_67_fu_1251_p1) & zext_ln51_66_fu_1248_p1) & zext_ln51_65_fu_1245_p1) & zext_ln51_64_fu_1242_p1) & zext_ln51_fu_1239_p1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln51_64_fu_872_p3 <= 
        trunc_ln44_s_reg_1429 when (icmp_ln51_64_fu_867_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_65_fu_884_p3 <= 
        trunc_ln44_67_reg_1439 when (icmp_ln51_65_fu_879_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_66_fu_896_p3 <= 
        trunc_ln44_68_reg_1449 when (icmp_ln51_66_fu_891_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_67_fu_908_p3 <= 
        trunc_ln44_69_reg_1459 when (icmp_ln51_67_fu_903_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_68_fu_920_p3 <= 
        trunc_ln44_70_reg_1469 when (icmp_ln51_68_fu_915_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_69_fu_932_p3 <= 
        trunc_ln44_71_reg_1479 when (icmp_ln51_69_fu_927_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_70_fu_944_p3 <= 
        trunc_ln44_72_reg_1489 when (icmp_ln51_70_fu_939_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_71_fu_956_p3 <= 
        trunc_ln44_73_reg_1499 when (icmp_ln51_71_fu_951_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_72_fu_968_p3 <= 
        trunc_ln44_74_reg_1509 when (icmp_ln51_72_fu_963_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_73_fu_980_p3 <= 
        trunc_ln44_75_reg_1519 when (icmp_ln51_73_fu_975_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_74_fu_992_p3 <= 
        trunc_ln44_76_reg_1529 when (icmp_ln51_74_fu_987_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_75_fu_1004_p3 <= 
        trunc_ln44_77_reg_1539 when (icmp_ln51_75_fu_999_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_76_fu_1016_p3 <= 
        trunc_ln44_78_reg_1549 when (icmp_ln51_76_fu_1011_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_77_fu_1028_p3 <= 
        trunc_ln44_79_reg_1559 when (icmp_ln51_77_fu_1023_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_78_fu_1040_p3 <= 
        trunc_ln44_80_reg_1569 when (icmp_ln51_78_fu_1035_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_79_fu_1052_p3 <= 
        trunc_ln44_81_reg_1579 when (icmp_ln51_79_fu_1047_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_80_fu_1064_p3 <= 
        trunc_ln44_82_reg_1589 when (icmp_ln51_80_fu_1059_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_81_fu_1076_p3 <= 
        trunc_ln44_83_reg_1599 when (icmp_ln51_81_fu_1071_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_82_fu_1088_p3 <= 
        trunc_ln44_84_reg_1609 when (icmp_ln51_82_fu_1083_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_83_fu_1100_p3 <= 
        trunc_ln44_85_reg_1619 when (icmp_ln51_83_fu_1095_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_84_fu_1112_p3 <= 
        trunc_ln44_86_reg_1629 when (icmp_ln51_84_fu_1107_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_85_fu_1124_p3 <= 
        trunc_ln44_87_reg_1639 when (icmp_ln51_85_fu_1119_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_86_fu_1136_p3 <= 
        trunc_ln44_88_reg_1649 when (icmp_ln51_86_fu_1131_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_87_fu_1148_p3 <= 
        trunc_ln44_89_reg_1659 when (icmp_ln51_87_fu_1143_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_88_fu_1160_p3 <= 
        trunc_ln44_90_reg_1669 when (icmp_ln51_88_fu_1155_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_89_fu_1172_p3 <= 
        trunc_ln44_91_reg_1679 when (icmp_ln51_89_fu_1167_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_90_fu_1184_p3 <= 
        trunc_ln44_92_reg_1689 when (icmp_ln51_90_fu_1179_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_91_fu_1196_p3 <= 
        trunc_ln44_93_reg_1699 when (icmp_ln51_91_fu_1191_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_92_fu_1208_p3 <= 
        trunc_ln44_94_reg_1709 when (icmp_ln51_92_fu_1203_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_93_fu_1220_p3 <= 
        trunc_ln44_95_reg_1714 when (icmp_ln51_93_fu_1215_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_94_fu_1232_p3 <= 
        trunc_ln_reg_1719 when (icmp_ln51_94_fu_1227_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_fu_860_p3 <= 
        trunc_ln44_2_reg_1409 when (icmp_ln51_fu_855_p2(0) = '1') else 
        ap_const_lv15_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln44_2_fu_231_p1 <= layer6_out_dout(15 - 1 downto 0);
    zext_ln51_64_fu_1242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_64_reg_1729),16));
    zext_ln51_65_fu_1245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_65_reg_1734),16));
    zext_ln51_66_fu_1248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_66_reg_1739),16));
    zext_ln51_67_fu_1251_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_67_reg_1744),16));
    zext_ln51_68_fu_1254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_68_reg_1749),16));
    zext_ln51_69_fu_1257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_69_reg_1754),16));
    zext_ln51_70_fu_1260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_70_reg_1759),16));
    zext_ln51_71_fu_1263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_71_reg_1764),16));
    zext_ln51_72_fu_1266_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_72_reg_1769),16));
    zext_ln51_73_fu_1269_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_73_reg_1774),16));
    zext_ln51_74_fu_1272_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_74_reg_1779),16));
    zext_ln51_75_fu_1275_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_75_reg_1784),16));
    zext_ln51_76_fu_1278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_76_reg_1789),16));
    zext_ln51_77_fu_1281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_77_reg_1794),16));
    zext_ln51_78_fu_1284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_78_reg_1799),16));
    zext_ln51_79_fu_1287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_79_reg_1804),16));
    zext_ln51_80_fu_1290_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_80_reg_1809),16));
    zext_ln51_81_fu_1293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_81_reg_1814),16));
    zext_ln51_82_fu_1296_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_82_reg_1819),16));
    zext_ln51_83_fu_1299_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_83_reg_1824),16));
    zext_ln51_84_fu_1302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_84_reg_1829),16));
    zext_ln51_85_fu_1305_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_85_reg_1834),16));
    zext_ln51_86_fu_1308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_86_reg_1839),16));
    zext_ln51_87_fu_1311_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_87_reg_1844),16));
    zext_ln51_88_fu_1314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_88_reg_1849),16));
    zext_ln51_89_fu_1317_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_89_reg_1854),16));
    zext_ln51_90_fu_1320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_90_reg_1859),16));
    zext_ln51_91_fu_1323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_91_reg_1864),16));
    zext_ln51_92_fu_1326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_92_reg_1869),16));
    zext_ln51_93_fu_1329_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_93_reg_1874),16));
    zext_ln51_fu_1239_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_reg_1724),16));
end behav;
