// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer4_out_dout,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_empty_n,
        layer4_out_read,
        layer5_out_TDATA,
        layer5_out_TVALID,
        layer5_out_TREADY
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] layer4_out_dout;
input  [1:0] layer4_out_num_data_valid;
input  [1:0] layer4_out_fifo_cap;
input   layer4_out_empty_n;
output   layer4_out_read;
output  [15:0] layer5_out_TDATA;
output   layer5_out_TVALID;
input   layer5_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer4_out_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] sigmoid_table_address0;
reg    sigmoid_table_ce0;
wire   [9:0] sigmoid_table_q0;
reg    layer4_out_blk_n;
reg    layer5_out_TDATA_blk_n;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [15:0] in_data_reg_235;
reg    ap_block_state1;
reg   [11:0] tmp_2_reg_240;
wire   [0:0] icmp_ln90_1_fu_112_p2;
reg   [0:0] icmp_ln90_1_reg_245;
wire   [12:0] data_round_fu_147_p3;
reg   [12:0] data_round_reg_250;
wire    ap_CS_fsm_state2;
wire   [12:0] index_fu_155_p2;
reg   [12:0] index_reg_256;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln94_fu_170_p2;
reg   [0:0] icmp_ln94_reg_262;
wire   [9:0] index_1_fu_218_p3;
reg   [9:0] index_1_reg_267;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln96_fu_226_p1;
wire   [3:0] trunc_ln90_fu_100_p1;
wire   [9:0] tmp_1_fu_104_p3;
wire   [25:0] shl_ln_fu_118_p3;
wire  signed [12:0] sext_ln90_fu_125_p1;
wire   [12:0] add_ln90_fu_134_p2;
wire   [0:0] icmp_ln90_fu_128_p2;
wire   [12:0] select_ln90_fu_140_p3;
wire   [2:0] tmp_3_fu_160_p4;
wire   [9:0] trunc_ln91_fu_176_p1;
wire   [0:0] tmp_4_fu_192_p3;
wire   [0:0] xor_ln92_fu_199_p2;
wire   [0:0] tmp_fu_185_p3;
wire   [0:0] or_ln92_fu_213_p2;
wire   [9:0] select_ln92_fu_205_p3;
wire   [9:0] xor_ln91_fu_179_p2;
wire    regslice_both_layer5_out_U_apdone_blk;
reg    ap_block_state7;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire   [15:0] layer5_out_TDATA_int_regslice;
reg    layer5_out_TVALID_int_regslice;
wire    layer5_out_TREADY_int_regslice;
wire    regslice_both_layer5_out_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
end

myproject_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_s_sigmoid_table_ROdEe #(
    .DataWidth( 10 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
sigmoid_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sigmoid_table_address0),
    .ce0(sigmoid_table_ce0),
    .q0(sigmoid_table_q0)
);

myproject_regslice_both #(
    .DataWidth( 16 ))
regslice_both_layer5_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(layer5_out_TDATA_int_regslice),
    .vld_in(layer5_out_TVALID_int_regslice),
    .ack_in(layer5_out_TREADY_int_regslice),
    .data_out(layer5_out_TDATA),
    .vld_out(regslice_both_layer5_out_U_vld_out),
    .ack_out(layer5_out_TREADY),
    .apdone_blk(regslice_both_layer5_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((layer5_out_TREADY_int_regslice == 1'b0) | (regslice_both_layer5_out_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        data_round_reg_250 <= data_round_fu_147_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((layer4_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln90_1_reg_245 <= icmp_ln90_1_fu_112_p2;
        in_data_reg_235 <= layer4_out_dout;
        tmp_2_reg_240 <= {{layer4_out_dout[15:4]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln94_reg_262 <= icmp_ln94_fu_170_p2;
        index_reg_256 <= index_fu_155_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        index_1_reg_267 <= index_1_fu_218_p3;
    end
end

always @ (*) begin
    if (((layer4_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((layer5_out_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer5_out_TREADY_int_regslice == 1'b0) | (regslice_both_layer5_out_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((layer5_out_TREADY_int_regslice == 1'b0) | (regslice_both_layer5_out_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((layer5_out_TREADY_int_regslice == 1'b0) | (regslice_both_layer5_out_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_blk_n = layer4_out_empty_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((layer4_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_read = 1'b1;
    end else begin
        layer4_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        layer5_out_TDATA_blk_n = layer5_out_TREADY_int_regslice;
    end else begin
        layer5_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer5_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        layer5_out_TVALID_int_regslice = 1'b1;
    end else begin
        layer5_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        sigmoid_table_ce0 = 1'b1;
    end else begin
        sigmoid_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((layer4_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((layer5_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((layer5_out_TREADY_int_regslice == 1'b0) | (regslice_both_layer5_out_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln90_fu_134_p2 = ($signed(sext_ln90_fu_125_p1) + $signed(13'd1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((layer4_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((layer5_out_TREADY_int_regslice == 1'b0) | (regslice_both_layer5_out_U_apdone_blk == 1'b1));
end

assign data_round_fu_147_p3 = ((icmp_ln90_fu_128_p2[0:0] == 1'b1) ? select_ln90_fu_140_p3 : sext_ln90_fu_125_p1);

assign icmp_ln90_1_fu_112_p2 = ((tmp_1_fu_104_p3 == 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_128_p2 = (($signed(shl_ln_fu_118_p3) < $signed(26'd67108849)) ? 1'b1 : 1'b0);

assign icmp_ln94_fu_170_p2 = ((tmp_3_fu_160_p4 != 3'd0) ? 1'b1 : 1'b0);

assign index_1_fu_218_p3 = ((or_ln92_fu_213_p2[0:0] == 1'b1) ? select_ln92_fu_205_p3 : xor_ln91_fu_179_p2);

assign index_fu_155_p2 = (data_round_reg_250 + 13'd512);

assign layer5_out_TDATA_int_regslice = sigmoid_table_q0;

assign layer5_out_TVALID = regslice_both_layer5_out_U_vld_out;

assign or_ln92_fu_213_p2 = (tmp_fu_185_p3 | icmp_ln94_reg_262);

assign select_ln90_fu_140_p3 = ((icmp_ln90_1_reg_245[0:0] == 1'b1) ? sext_ln90_fu_125_p1 : add_ln90_fu_134_p2);

assign select_ln92_fu_205_p3 = ((xor_ln92_fu_199_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign sext_ln90_fu_125_p1 = $signed(tmp_2_reg_240);

assign shl_ln_fu_118_p3 = {{in_data_reg_235}, {10'd0}};

assign sigmoid_table_address0 = zext_ln96_fu_226_p1;

assign tmp_1_fu_104_p3 = {{trunc_ln90_fu_100_p1}, {6'd0}};

assign tmp_3_fu_160_p4 = {{index_fu_155_p2[12:10]}};

assign tmp_4_fu_192_p3 = index_reg_256[32'd12];

assign tmp_fu_185_p3 = index_reg_256[32'd12];

assign trunc_ln90_fu_100_p1 = layer4_out_dout[3:0];

assign trunc_ln91_fu_176_p1 = data_round_reg_250[9:0];

assign xor_ln91_fu_179_p2 = (trunc_ln91_fu_176_p1 ^ 10'd512);

assign xor_ln92_fu_199_p2 = (tmp_4_fu_192_p3 ^ 1'd1);

assign zext_ln96_fu_226_p1 = index_1_reg_267;

endmodule //myproject_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config5_s
