// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer4_out_dout,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_empty_n,
        layer4_out_read,
        layer5_out_din,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer5_out_full_n,
        layer5_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] layer4_out_dout;
input  [1:0] layer4_out_num_data_valid;
input  [1:0] layer4_out_fifo_cap;
input   layer4_out_empty_n;
output   layer4_out_read;
output  [511:0] layer5_out_din;
input  [1:0] layer5_out_num_data_valid;
input  [1:0] layer5_out_fifo_cap;
input   layer5_out_full_n;
output   layer5_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer4_out_read;
reg layer5_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer4_out_blk_n;
reg    layer5_out_blk_n;
wire    ap_CS_fsm_state3;
wire   [15:0] in_data_fu_227_p1;
reg   [15:0] in_data_reg_1404;
reg    ap_block_state1;
wire   [14:0] trunc_ln44_3_fu_231_p1;
reg   [14:0] trunc_ln44_3_reg_1409;
reg   [15:0] trunc_ln44_96_reg_1414;
reg   [15:0] trunc_ln44_97_reg_1419;
reg   [15:0] in_data_16_reg_1424;
reg   [14:0] trunc_ln44_s_reg_1429;
reg   [15:0] in_data_17_reg_1434;
reg   [14:0] trunc_ln44_98_reg_1439;
reg   [15:0] in_data_18_reg_1444;
reg   [14:0] trunc_ln44_99_reg_1449;
reg   [15:0] tmp_reg_1454;
reg   [14:0] trunc_ln44_100_reg_1459;
reg   [15:0] tmp_s_reg_1464;
reg   [14:0] trunc_ln44_101_reg_1469;
reg   [15:0] tmp_81_reg_1474;
reg   [14:0] trunc_ln44_102_reg_1479;
reg   [15:0] tmp_82_reg_1484;
reg   [14:0] trunc_ln44_103_reg_1489;
reg   [15:0] tmp_83_reg_1494;
reg   [14:0] trunc_ln44_104_reg_1499;
reg   [15:0] tmp_84_reg_1504;
reg   [14:0] trunc_ln44_105_reg_1509;
reg   [15:0] tmp_85_reg_1514;
reg   [14:0] trunc_ln44_106_reg_1519;
reg   [15:0] tmp_86_reg_1524;
reg   [14:0] trunc_ln44_107_reg_1529;
reg   [15:0] tmp_87_reg_1534;
reg   [14:0] trunc_ln44_108_reg_1539;
reg   [15:0] tmp_88_reg_1544;
reg   [14:0] trunc_ln44_109_reg_1549;
reg   [15:0] tmp_89_reg_1554;
reg   [14:0] trunc_ln44_110_reg_1559;
reg   [15:0] tmp_90_reg_1564;
reg   [14:0] trunc_ln44_111_reg_1569;
reg   [15:0] tmp_91_reg_1574;
reg   [14:0] trunc_ln44_112_reg_1579;
reg   [15:0] tmp_92_reg_1584;
reg   [14:0] trunc_ln44_113_reg_1589;
reg   [15:0] tmp_93_reg_1594;
reg   [14:0] trunc_ln44_114_reg_1599;
reg   [15:0] tmp_94_reg_1604;
reg   [14:0] trunc_ln44_115_reg_1609;
reg   [15:0] tmp_95_reg_1614;
reg   [14:0] trunc_ln44_116_reg_1619;
reg   [15:0] tmp_96_reg_1624;
reg   [14:0] trunc_ln44_117_reg_1629;
reg   [15:0] tmp_97_reg_1634;
reg   [14:0] trunc_ln44_118_reg_1639;
reg   [15:0] tmp_98_reg_1644;
reg   [14:0] trunc_ln44_119_reg_1649;
reg   [15:0] tmp_99_reg_1654;
reg   [14:0] trunc_ln44_120_reg_1659;
reg   [15:0] tmp_100_reg_1664;
reg   [14:0] trunc_ln44_121_reg_1669;
reg   [15:0] tmp_101_reg_1674;
reg   [14:0] trunc_ln44_122_reg_1679;
reg   [15:0] tmp_102_reg_1684;
reg   [14:0] trunc_ln44_123_reg_1689;
reg   [15:0] tmp_103_reg_1694;
reg   [14:0] trunc_ln44_124_reg_1699;
reg   [15:0] tmp_104_reg_1704;
reg   [14:0] trunc_ln44_125_reg_1709;
reg   [14:0] trunc_ln44_126_reg_1714;
reg   [14:0] trunc_ln_reg_1719;
wire   [14:0] select_ln51_fu_860_p3;
reg   [14:0] select_ln51_reg_1724;
wire    ap_CS_fsm_state2;
wire   [14:0] select_ln51_95_fu_872_p3;
reg   [14:0] select_ln51_95_reg_1729;
wire   [14:0] select_ln51_96_fu_884_p3;
reg   [14:0] select_ln51_96_reg_1734;
wire   [14:0] select_ln51_97_fu_896_p3;
reg   [14:0] select_ln51_97_reg_1739;
wire   [14:0] select_ln51_98_fu_908_p3;
reg   [14:0] select_ln51_98_reg_1744;
wire   [14:0] select_ln51_99_fu_920_p3;
reg   [14:0] select_ln51_99_reg_1749;
wire   [14:0] select_ln51_100_fu_932_p3;
reg   [14:0] select_ln51_100_reg_1754;
wire   [14:0] select_ln51_101_fu_944_p3;
reg   [14:0] select_ln51_101_reg_1759;
wire   [14:0] select_ln51_102_fu_956_p3;
reg   [14:0] select_ln51_102_reg_1764;
wire   [14:0] select_ln51_103_fu_968_p3;
reg   [14:0] select_ln51_103_reg_1769;
wire   [14:0] select_ln51_104_fu_980_p3;
reg   [14:0] select_ln51_104_reg_1774;
wire   [14:0] select_ln51_105_fu_992_p3;
reg   [14:0] select_ln51_105_reg_1779;
wire   [14:0] select_ln51_106_fu_1004_p3;
reg   [14:0] select_ln51_106_reg_1784;
wire   [14:0] select_ln51_107_fu_1016_p3;
reg   [14:0] select_ln51_107_reg_1789;
wire   [14:0] select_ln51_108_fu_1028_p3;
reg   [14:0] select_ln51_108_reg_1794;
wire   [14:0] select_ln51_109_fu_1040_p3;
reg   [14:0] select_ln51_109_reg_1799;
wire   [14:0] select_ln51_110_fu_1052_p3;
reg   [14:0] select_ln51_110_reg_1804;
wire   [14:0] select_ln51_111_fu_1064_p3;
reg   [14:0] select_ln51_111_reg_1809;
wire   [14:0] select_ln51_112_fu_1076_p3;
reg   [14:0] select_ln51_112_reg_1814;
wire   [14:0] select_ln51_113_fu_1088_p3;
reg   [14:0] select_ln51_113_reg_1819;
wire   [14:0] select_ln51_114_fu_1100_p3;
reg   [14:0] select_ln51_114_reg_1824;
wire   [14:0] select_ln51_115_fu_1112_p3;
reg   [14:0] select_ln51_115_reg_1829;
wire   [14:0] select_ln51_116_fu_1124_p3;
reg   [14:0] select_ln51_116_reg_1834;
wire   [14:0] select_ln51_117_fu_1136_p3;
reg   [14:0] select_ln51_117_reg_1839;
wire   [14:0] select_ln51_118_fu_1148_p3;
reg   [14:0] select_ln51_118_reg_1844;
wire   [14:0] select_ln51_119_fu_1160_p3;
reg   [14:0] select_ln51_119_reg_1849;
wire   [14:0] select_ln51_120_fu_1172_p3;
reg   [14:0] select_ln51_120_reg_1854;
wire   [14:0] select_ln51_121_fu_1184_p3;
reg   [14:0] select_ln51_121_reg_1859;
wire   [14:0] select_ln51_122_fu_1196_p3;
reg   [14:0] select_ln51_122_reg_1864;
wire   [14:0] select_ln51_123_fu_1208_p3;
reg   [14:0] select_ln51_123_reg_1869;
wire   [14:0] select_ln51_124_fu_1220_p3;
reg   [14:0] select_ln51_124_reg_1874;
wire   [14:0] select_ln51_125_fu_1232_p3;
reg   [14:0] select_ln51_125_reg_1879;
wire   [0:0] icmp_ln51_fu_855_p2;
wire   [0:0] icmp_ln51_95_fu_867_p2;
wire   [0:0] icmp_ln51_96_fu_879_p2;
wire   [0:0] icmp_ln51_97_fu_891_p2;
wire   [0:0] icmp_ln51_98_fu_903_p2;
wire   [0:0] icmp_ln51_99_fu_915_p2;
wire   [0:0] icmp_ln51_100_fu_927_p2;
wire   [0:0] icmp_ln51_101_fu_939_p2;
wire   [0:0] icmp_ln51_102_fu_951_p2;
wire   [0:0] icmp_ln51_103_fu_963_p2;
wire   [0:0] icmp_ln51_104_fu_975_p2;
wire   [0:0] icmp_ln51_105_fu_987_p2;
wire   [0:0] icmp_ln51_106_fu_999_p2;
wire   [0:0] icmp_ln51_107_fu_1011_p2;
wire   [0:0] icmp_ln51_108_fu_1023_p2;
wire   [0:0] icmp_ln51_109_fu_1035_p2;
wire   [0:0] icmp_ln51_110_fu_1047_p2;
wire   [0:0] icmp_ln51_111_fu_1059_p2;
wire   [0:0] icmp_ln51_112_fu_1071_p2;
wire   [0:0] icmp_ln51_113_fu_1083_p2;
wire   [0:0] icmp_ln51_114_fu_1095_p2;
wire   [0:0] icmp_ln51_115_fu_1107_p2;
wire   [0:0] icmp_ln51_116_fu_1119_p2;
wire   [0:0] icmp_ln51_117_fu_1131_p2;
wire   [0:0] icmp_ln51_118_fu_1143_p2;
wire   [0:0] icmp_ln51_119_fu_1155_p2;
wire   [0:0] icmp_ln51_120_fu_1167_p2;
wire   [0:0] icmp_ln51_121_fu_1179_p2;
wire   [0:0] icmp_ln51_122_fu_1191_p2;
wire   [0:0] icmp_ln51_123_fu_1203_p2;
wire   [0:0] icmp_ln51_124_fu_1215_p2;
wire   [0:0] icmp_ln51_125_fu_1227_p2;
wire   [15:0] zext_ln51_123_fu_1329_p1;
wire   [15:0] zext_ln51_122_fu_1326_p1;
wire   [15:0] zext_ln51_121_fu_1323_p1;
wire   [15:0] zext_ln51_120_fu_1320_p1;
wire   [15:0] zext_ln51_119_fu_1317_p1;
wire   [15:0] zext_ln51_118_fu_1314_p1;
wire   [15:0] zext_ln51_117_fu_1311_p1;
wire   [15:0] zext_ln51_116_fu_1308_p1;
wire   [15:0] zext_ln51_115_fu_1305_p1;
wire   [15:0] zext_ln51_114_fu_1302_p1;
wire   [15:0] zext_ln51_113_fu_1299_p1;
wire   [15:0] zext_ln51_112_fu_1296_p1;
wire   [15:0] zext_ln51_111_fu_1293_p1;
wire   [15:0] zext_ln51_110_fu_1290_p1;
wire   [15:0] zext_ln51_109_fu_1287_p1;
wire   [15:0] zext_ln51_108_fu_1284_p1;
wire   [15:0] zext_ln51_107_fu_1281_p1;
wire   [15:0] zext_ln51_106_fu_1278_p1;
wire   [15:0] zext_ln51_105_fu_1275_p1;
wire   [15:0] zext_ln51_104_fu_1272_p1;
wire   [15:0] zext_ln51_103_fu_1269_p1;
wire   [15:0] zext_ln51_102_fu_1266_p1;
wire   [15:0] zext_ln51_101_fu_1263_p1;
wire   [15:0] zext_ln51_100_fu_1260_p1;
wire   [15:0] zext_ln51_99_fu_1257_p1;
wire   [15:0] zext_ln51_98_fu_1254_p1;
wire   [15:0] zext_ln51_97_fu_1251_p1;
wire   [15:0] zext_ln51_96_fu_1248_p1;
wire   [15:0] zext_ln51_95_fu_1245_p1;
wire   [15:0] zext_ln51_94_fu_1242_p1;
wire   [15:0] zext_ln51_fu_1239_p1;
wire   [510:0] or_ln57_s_fu_1332_p33;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (layer4_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        in_data_16_reg_1424 <= {{layer4_out_dout[31:16]}};
        in_data_17_reg_1434 <= {{layer4_out_dout[47:32]}};
        in_data_18_reg_1444 <= {{layer4_out_dout[63:48]}};
        in_data_reg_1404 <= in_data_fu_227_p1;
        tmp_100_reg_1664 <= {{layer4_out_dout[415:400]}};
        tmp_101_reg_1674 <= {{layer4_out_dout[431:416]}};
        tmp_102_reg_1684 <= {{layer4_out_dout[447:432]}};
        tmp_103_reg_1694 <= {{layer4_out_dout[463:448]}};
        tmp_104_reg_1704 <= {{layer4_out_dout[479:464]}};
        tmp_81_reg_1474 <= {{layer4_out_dout[111:96]}};
        tmp_82_reg_1484 <= {{layer4_out_dout[127:112]}};
        tmp_83_reg_1494 <= {{layer4_out_dout[143:128]}};
        tmp_84_reg_1504 <= {{layer4_out_dout[159:144]}};
        tmp_85_reg_1514 <= {{layer4_out_dout[175:160]}};
        tmp_86_reg_1524 <= {{layer4_out_dout[191:176]}};
        tmp_87_reg_1534 <= {{layer4_out_dout[207:192]}};
        tmp_88_reg_1544 <= {{layer4_out_dout[223:208]}};
        tmp_89_reg_1554 <= {{layer4_out_dout[239:224]}};
        tmp_90_reg_1564 <= {{layer4_out_dout[255:240]}};
        tmp_91_reg_1574 <= {{layer4_out_dout[271:256]}};
        tmp_92_reg_1584 <= {{layer4_out_dout[287:272]}};
        tmp_93_reg_1594 <= {{layer4_out_dout[303:288]}};
        tmp_94_reg_1604 <= {{layer4_out_dout[319:304]}};
        tmp_95_reg_1614 <= {{layer4_out_dout[335:320]}};
        tmp_96_reg_1624 <= {{layer4_out_dout[351:336]}};
        tmp_97_reg_1634 <= {{layer4_out_dout[367:352]}};
        tmp_98_reg_1644 <= {{layer4_out_dout[383:368]}};
        tmp_99_reg_1654 <= {{layer4_out_dout[399:384]}};
        tmp_reg_1454 <= {{layer4_out_dout[79:64]}};
        tmp_s_reg_1464 <= {{layer4_out_dout[95:80]}};
        trunc_ln44_100_reg_1459 <= {{layer4_out_dout[78:64]}};
        trunc_ln44_101_reg_1469 <= {{layer4_out_dout[94:80]}};
        trunc_ln44_102_reg_1479 <= {{layer4_out_dout[110:96]}};
        trunc_ln44_103_reg_1489 <= {{layer4_out_dout[126:112]}};
        trunc_ln44_104_reg_1499 <= {{layer4_out_dout[142:128]}};
        trunc_ln44_105_reg_1509 <= {{layer4_out_dout[158:144]}};
        trunc_ln44_106_reg_1519 <= {{layer4_out_dout[174:160]}};
        trunc_ln44_107_reg_1529 <= {{layer4_out_dout[190:176]}};
        trunc_ln44_108_reg_1539 <= {{layer4_out_dout[206:192]}};
        trunc_ln44_109_reg_1549 <= {{layer4_out_dout[222:208]}};
        trunc_ln44_110_reg_1559 <= {{layer4_out_dout[238:224]}};
        trunc_ln44_111_reg_1569 <= {{layer4_out_dout[254:240]}};
        trunc_ln44_112_reg_1579 <= {{layer4_out_dout[270:256]}};
        trunc_ln44_113_reg_1589 <= {{layer4_out_dout[286:272]}};
        trunc_ln44_114_reg_1599 <= {{layer4_out_dout[302:288]}};
        trunc_ln44_115_reg_1609 <= {{layer4_out_dout[318:304]}};
        trunc_ln44_116_reg_1619 <= {{layer4_out_dout[334:320]}};
        trunc_ln44_117_reg_1629 <= {{layer4_out_dout[350:336]}};
        trunc_ln44_118_reg_1639 <= {{layer4_out_dout[366:352]}};
        trunc_ln44_119_reg_1649 <= {{layer4_out_dout[382:368]}};
        trunc_ln44_120_reg_1659 <= {{layer4_out_dout[398:384]}};
        trunc_ln44_121_reg_1669 <= {{layer4_out_dout[414:400]}};
        trunc_ln44_122_reg_1679 <= {{layer4_out_dout[430:416]}};
        trunc_ln44_123_reg_1689 <= {{layer4_out_dout[446:432]}};
        trunc_ln44_124_reg_1699 <= {{layer4_out_dout[462:448]}};
        trunc_ln44_125_reg_1709 <= {{layer4_out_dout[478:464]}};
        trunc_ln44_126_reg_1714 <= {{layer4_out_dout[494:480]}};
        trunc_ln44_3_reg_1409 <= trunc_ln44_3_fu_231_p1;
        trunc_ln44_96_reg_1414 <= {{layer4_out_dout[495:480]}};
        trunc_ln44_97_reg_1419 <= {{layer4_out_dout[511:496]}};
        trunc_ln44_98_reg_1439 <= {{layer4_out_dout[46:32]}};
        trunc_ln44_99_reg_1449 <= {{layer4_out_dout[62:48]}};
        trunc_ln44_s_reg_1429 <= {{layer4_out_dout[30:16]}};
        trunc_ln_reg_1719 <= {{layer4_out_dout[510:496]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln51_100_reg_1754 <= select_ln51_100_fu_932_p3;
        select_ln51_101_reg_1759 <= select_ln51_101_fu_944_p3;
        select_ln51_102_reg_1764 <= select_ln51_102_fu_956_p3;
        select_ln51_103_reg_1769 <= select_ln51_103_fu_968_p3;
        select_ln51_104_reg_1774 <= select_ln51_104_fu_980_p3;
        select_ln51_105_reg_1779 <= select_ln51_105_fu_992_p3;
        select_ln51_106_reg_1784 <= select_ln51_106_fu_1004_p3;
        select_ln51_107_reg_1789 <= select_ln51_107_fu_1016_p3;
        select_ln51_108_reg_1794 <= select_ln51_108_fu_1028_p3;
        select_ln51_109_reg_1799 <= select_ln51_109_fu_1040_p3;
        select_ln51_110_reg_1804 <= select_ln51_110_fu_1052_p3;
        select_ln51_111_reg_1809 <= select_ln51_111_fu_1064_p3;
        select_ln51_112_reg_1814 <= select_ln51_112_fu_1076_p3;
        select_ln51_113_reg_1819 <= select_ln51_113_fu_1088_p3;
        select_ln51_114_reg_1824 <= select_ln51_114_fu_1100_p3;
        select_ln51_115_reg_1829 <= select_ln51_115_fu_1112_p3;
        select_ln51_116_reg_1834 <= select_ln51_116_fu_1124_p3;
        select_ln51_117_reg_1839 <= select_ln51_117_fu_1136_p3;
        select_ln51_118_reg_1844 <= select_ln51_118_fu_1148_p3;
        select_ln51_119_reg_1849 <= select_ln51_119_fu_1160_p3;
        select_ln51_120_reg_1854 <= select_ln51_120_fu_1172_p3;
        select_ln51_121_reg_1859 <= select_ln51_121_fu_1184_p3;
        select_ln51_122_reg_1864 <= select_ln51_122_fu_1196_p3;
        select_ln51_123_reg_1869 <= select_ln51_123_fu_1208_p3;
        select_ln51_124_reg_1874 <= select_ln51_124_fu_1220_p3;
        select_ln51_125_reg_1879 <= select_ln51_125_fu_1232_p3;
        select_ln51_95_reg_1729 <= select_ln51_95_fu_872_p3;
        select_ln51_96_reg_1734 <= select_ln51_96_fu_884_p3;
        select_ln51_97_reg_1739 <= select_ln51_97_fu_896_p3;
        select_ln51_98_reg_1744 <= select_ln51_98_fu_908_p3;
        select_ln51_99_reg_1749 <= select_ln51_99_fu_920_p3;
        select_ln51_reg_1724 <= select_ln51_fu_860_p3;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (layer4_out_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((layer5_out_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_blk_n = layer4_out_empty_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (layer4_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_read = 1'b1;
    end else begin
        layer4_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer5_out_blk_n = layer5_out_full_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer5_out_write = 1'b1;
    end else begin
        layer5_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (layer4_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer4_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_100_fu_927_p2 = (($signed(tmp_81_reg_1474) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_101_fu_939_p2 = (($signed(tmp_82_reg_1484) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_102_fu_951_p2 = (($signed(tmp_83_reg_1494) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_103_fu_963_p2 = (($signed(tmp_84_reg_1504) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_104_fu_975_p2 = (($signed(tmp_85_reg_1514) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_105_fu_987_p2 = (($signed(tmp_86_reg_1524) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_106_fu_999_p2 = (($signed(tmp_87_reg_1534) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_107_fu_1011_p2 = (($signed(tmp_88_reg_1544) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_108_fu_1023_p2 = (($signed(tmp_89_reg_1554) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_109_fu_1035_p2 = (($signed(tmp_90_reg_1564) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_110_fu_1047_p2 = (($signed(tmp_91_reg_1574) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_111_fu_1059_p2 = (($signed(tmp_92_reg_1584) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_112_fu_1071_p2 = (($signed(tmp_93_reg_1594) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_113_fu_1083_p2 = (($signed(tmp_94_reg_1604) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_114_fu_1095_p2 = (($signed(tmp_95_reg_1614) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_115_fu_1107_p2 = (($signed(tmp_96_reg_1624) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_116_fu_1119_p2 = (($signed(tmp_97_reg_1634) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_117_fu_1131_p2 = (($signed(tmp_98_reg_1644) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_118_fu_1143_p2 = (($signed(tmp_99_reg_1654) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_119_fu_1155_p2 = (($signed(tmp_100_reg_1664) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_120_fu_1167_p2 = (($signed(tmp_101_reg_1674) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_121_fu_1179_p2 = (($signed(tmp_102_reg_1684) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_122_fu_1191_p2 = (($signed(tmp_103_reg_1694) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_123_fu_1203_p2 = (($signed(tmp_104_reg_1704) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_124_fu_1215_p2 = (($signed(trunc_ln44_96_reg_1414) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_125_fu_1227_p2 = (($signed(trunc_ln44_97_reg_1419) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_95_fu_867_p2 = (($signed(in_data_16_reg_1424) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_96_fu_879_p2 = (($signed(in_data_17_reg_1434) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_97_fu_891_p2 = (($signed(in_data_18_reg_1444) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_98_fu_903_p2 = (($signed(tmp_reg_1454) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_99_fu_915_p2 = (($signed(tmp_s_reg_1464) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_855_p2 = (($signed(in_data_reg_1404) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign in_data_fu_227_p1 = layer4_out_dout[15:0];

assign layer5_out_din = or_ln57_s_fu_1332_p33;

assign or_ln57_s_fu_1332_p33 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_125_reg_1879}, {zext_ln51_123_fu_1329_p1}}, {zext_ln51_122_fu_1326_p1}}, {zext_ln51_121_fu_1323_p1}}, {zext_ln51_120_fu_1320_p1}}, {zext_ln51_119_fu_1317_p1}}, {zext_ln51_118_fu_1314_p1}}, {zext_ln51_117_fu_1311_p1}}, {zext_ln51_116_fu_1308_p1}}, {zext_ln51_115_fu_1305_p1}}, {zext_ln51_114_fu_1302_p1}}, {zext_ln51_113_fu_1299_p1}}, {zext_ln51_112_fu_1296_p1}}, {zext_ln51_111_fu_1293_p1}}, {zext_ln51_110_fu_1290_p1}}, {zext_ln51_109_fu_1287_p1}}, {zext_ln51_108_fu_1284_p1}}, {zext_ln51_107_fu_1281_p1}}, {zext_ln51_106_fu_1278_p1}}, {zext_ln51_105_fu_1275_p1}}, {zext_ln51_104_fu_1272_p1}}, {zext_ln51_103_fu_1269_p1}}, {zext_ln51_102_fu_1266_p1}}, {zext_ln51_101_fu_1263_p1}}, {zext_ln51_100_fu_1260_p1}}, {zext_ln51_99_fu_1257_p1}}, {zext_ln51_98_fu_1254_p1}}, {zext_ln51_97_fu_1251_p1}}, {zext_ln51_96_fu_1248_p1}}, {zext_ln51_95_fu_1245_p1}}, {zext_ln51_94_fu_1242_p1}}, {zext_ln51_fu_1239_p1}};

assign select_ln51_100_fu_932_p3 = ((icmp_ln51_100_fu_927_p2[0:0] == 1'b1) ? trunc_ln44_102_reg_1479 : 15'd0);

assign select_ln51_101_fu_944_p3 = ((icmp_ln51_101_fu_939_p2[0:0] == 1'b1) ? trunc_ln44_103_reg_1489 : 15'd0);

assign select_ln51_102_fu_956_p3 = ((icmp_ln51_102_fu_951_p2[0:0] == 1'b1) ? trunc_ln44_104_reg_1499 : 15'd0);

assign select_ln51_103_fu_968_p3 = ((icmp_ln51_103_fu_963_p2[0:0] == 1'b1) ? trunc_ln44_105_reg_1509 : 15'd0);

assign select_ln51_104_fu_980_p3 = ((icmp_ln51_104_fu_975_p2[0:0] == 1'b1) ? trunc_ln44_106_reg_1519 : 15'd0);

assign select_ln51_105_fu_992_p3 = ((icmp_ln51_105_fu_987_p2[0:0] == 1'b1) ? trunc_ln44_107_reg_1529 : 15'd0);

assign select_ln51_106_fu_1004_p3 = ((icmp_ln51_106_fu_999_p2[0:0] == 1'b1) ? trunc_ln44_108_reg_1539 : 15'd0);

assign select_ln51_107_fu_1016_p3 = ((icmp_ln51_107_fu_1011_p2[0:0] == 1'b1) ? trunc_ln44_109_reg_1549 : 15'd0);

assign select_ln51_108_fu_1028_p3 = ((icmp_ln51_108_fu_1023_p2[0:0] == 1'b1) ? trunc_ln44_110_reg_1559 : 15'd0);

assign select_ln51_109_fu_1040_p3 = ((icmp_ln51_109_fu_1035_p2[0:0] == 1'b1) ? trunc_ln44_111_reg_1569 : 15'd0);

assign select_ln51_110_fu_1052_p3 = ((icmp_ln51_110_fu_1047_p2[0:0] == 1'b1) ? trunc_ln44_112_reg_1579 : 15'd0);

assign select_ln51_111_fu_1064_p3 = ((icmp_ln51_111_fu_1059_p2[0:0] == 1'b1) ? trunc_ln44_113_reg_1589 : 15'd0);

assign select_ln51_112_fu_1076_p3 = ((icmp_ln51_112_fu_1071_p2[0:0] == 1'b1) ? trunc_ln44_114_reg_1599 : 15'd0);

assign select_ln51_113_fu_1088_p3 = ((icmp_ln51_113_fu_1083_p2[0:0] == 1'b1) ? trunc_ln44_115_reg_1609 : 15'd0);

assign select_ln51_114_fu_1100_p3 = ((icmp_ln51_114_fu_1095_p2[0:0] == 1'b1) ? trunc_ln44_116_reg_1619 : 15'd0);

assign select_ln51_115_fu_1112_p3 = ((icmp_ln51_115_fu_1107_p2[0:0] == 1'b1) ? trunc_ln44_117_reg_1629 : 15'd0);

assign select_ln51_116_fu_1124_p3 = ((icmp_ln51_116_fu_1119_p2[0:0] == 1'b1) ? trunc_ln44_118_reg_1639 : 15'd0);

assign select_ln51_117_fu_1136_p3 = ((icmp_ln51_117_fu_1131_p2[0:0] == 1'b1) ? trunc_ln44_119_reg_1649 : 15'd0);

assign select_ln51_118_fu_1148_p3 = ((icmp_ln51_118_fu_1143_p2[0:0] == 1'b1) ? trunc_ln44_120_reg_1659 : 15'd0);

assign select_ln51_119_fu_1160_p3 = ((icmp_ln51_119_fu_1155_p2[0:0] == 1'b1) ? trunc_ln44_121_reg_1669 : 15'd0);

assign select_ln51_120_fu_1172_p3 = ((icmp_ln51_120_fu_1167_p2[0:0] == 1'b1) ? trunc_ln44_122_reg_1679 : 15'd0);

assign select_ln51_121_fu_1184_p3 = ((icmp_ln51_121_fu_1179_p2[0:0] == 1'b1) ? trunc_ln44_123_reg_1689 : 15'd0);

assign select_ln51_122_fu_1196_p3 = ((icmp_ln51_122_fu_1191_p2[0:0] == 1'b1) ? trunc_ln44_124_reg_1699 : 15'd0);

assign select_ln51_123_fu_1208_p3 = ((icmp_ln51_123_fu_1203_p2[0:0] == 1'b1) ? trunc_ln44_125_reg_1709 : 15'd0);

assign select_ln51_124_fu_1220_p3 = ((icmp_ln51_124_fu_1215_p2[0:0] == 1'b1) ? trunc_ln44_126_reg_1714 : 15'd0);

assign select_ln51_125_fu_1232_p3 = ((icmp_ln51_125_fu_1227_p2[0:0] == 1'b1) ? trunc_ln_reg_1719 : 15'd0);

assign select_ln51_95_fu_872_p3 = ((icmp_ln51_95_fu_867_p2[0:0] == 1'b1) ? trunc_ln44_s_reg_1429 : 15'd0);

assign select_ln51_96_fu_884_p3 = ((icmp_ln51_96_fu_879_p2[0:0] == 1'b1) ? trunc_ln44_98_reg_1439 : 15'd0);

assign select_ln51_97_fu_896_p3 = ((icmp_ln51_97_fu_891_p2[0:0] == 1'b1) ? trunc_ln44_99_reg_1449 : 15'd0);

assign select_ln51_98_fu_908_p3 = ((icmp_ln51_98_fu_903_p2[0:0] == 1'b1) ? trunc_ln44_100_reg_1459 : 15'd0);

assign select_ln51_99_fu_920_p3 = ((icmp_ln51_99_fu_915_p2[0:0] == 1'b1) ? trunc_ln44_101_reg_1469 : 15'd0);

assign select_ln51_fu_860_p3 = ((icmp_ln51_fu_855_p2[0:0] == 1'b1) ? trunc_ln44_3_reg_1409 : 15'd0);

assign start_out = real_start;

assign trunc_ln44_3_fu_231_p1 = layer4_out_dout[14:0];

assign zext_ln51_100_fu_1260_p1 = select_ln51_101_reg_1759;

assign zext_ln51_101_fu_1263_p1 = select_ln51_102_reg_1764;

assign zext_ln51_102_fu_1266_p1 = select_ln51_103_reg_1769;

assign zext_ln51_103_fu_1269_p1 = select_ln51_104_reg_1774;

assign zext_ln51_104_fu_1272_p1 = select_ln51_105_reg_1779;

assign zext_ln51_105_fu_1275_p1 = select_ln51_106_reg_1784;

assign zext_ln51_106_fu_1278_p1 = select_ln51_107_reg_1789;

assign zext_ln51_107_fu_1281_p1 = select_ln51_108_reg_1794;

assign zext_ln51_108_fu_1284_p1 = select_ln51_109_reg_1799;

assign zext_ln51_109_fu_1287_p1 = select_ln51_110_reg_1804;

assign zext_ln51_110_fu_1290_p1 = select_ln51_111_reg_1809;

assign zext_ln51_111_fu_1293_p1 = select_ln51_112_reg_1814;

assign zext_ln51_112_fu_1296_p1 = select_ln51_113_reg_1819;

assign zext_ln51_113_fu_1299_p1 = select_ln51_114_reg_1824;

assign zext_ln51_114_fu_1302_p1 = select_ln51_115_reg_1829;

assign zext_ln51_115_fu_1305_p1 = select_ln51_116_reg_1834;

assign zext_ln51_116_fu_1308_p1 = select_ln51_117_reg_1839;

assign zext_ln51_117_fu_1311_p1 = select_ln51_118_reg_1844;

assign zext_ln51_118_fu_1314_p1 = select_ln51_119_reg_1849;

assign zext_ln51_119_fu_1317_p1 = select_ln51_120_reg_1854;

assign zext_ln51_120_fu_1320_p1 = select_ln51_121_reg_1859;

assign zext_ln51_121_fu_1323_p1 = select_ln51_122_reg_1864;

assign zext_ln51_122_fu_1326_p1 = select_ln51_123_reg_1869;

assign zext_ln51_123_fu_1329_p1 = select_ln51_124_reg_1874;

assign zext_ln51_94_fu_1242_p1 = select_ln51_95_reg_1729;

assign zext_ln51_95_fu_1245_p1 = select_ln51_96_reg_1734;

assign zext_ln51_96_fu_1248_p1 = select_ln51_97_reg_1739;

assign zext_ln51_97_fu_1251_p1 = select_ln51_98_reg_1744;

assign zext_ln51_98_fu_1254_p1 = select_ln51_99_reg_1749;

assign zext_ln51_99_fu_1257_p1 = select_ln51_100_reg_1754;

assign zext_ln51_fu_1239_p1 = select_ln51_reg_1724;

endmodule //myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config5_s
